### ISSUE TITLE
WSGI config

### ISSUE THREAD

**Issue by Jmos** [jam-py/jam-py#10]
I would like try with apache wsgi module but i didn't found any config sample. Can you describe in wiki

**Comment by jam-py** [comment]
I'am sorry, I've never used it with apache. I think it must be the same way as with Django. The WSGI application module is in wsgi.py. You can try it. Please info me about the result.

**Comment by Jmos** [comment]
problem seams to be the admin.sqlite file in apache environment got empty result set.
i will return back try solving later

**Comment by Jmos** [comment]
Problem partially solved admin.html working in wsgi.py before import I inserted
os.chdir(os.path.dirname(__file__)) 
because it is a windows host.
Unfortunately index.html is a blank page but all contents are hidden and web browser got the index.html contents but all part is display:none. The browser can download any contens from /js or / or /static directory
Any idea?
How can debug this framework ?

**Comment by Jmos** [comment]
I pressed wrong button sorry

**Comment by jam-py** [comment]
Hi, 
I am using nginx and need to install apache to check. It can take some time (a lot of other work) - a couple of days.
Andrew

**Comment by Jmos** [comment]
O.K. but it is windows host and really didn't found any solution why not
serve correctly the document roots files I thing it some privilege problem
occurred Thanx your help

On Thu, May 26, 2016 at 8:59 AM, jam-py <notifications@github.com> wrote:

> Hi,
> I am using nginx and need to install apache to check. It can take some
> time (a lot of other work) - a couple of days.
> Andrew
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jam-py/jam-py/issues/10#issuecomment-221792861>
>



-- 
-------------------------------------------
mailto:janos.meggyeshazi@gmail.com
+36 20 776 9514

**Comment by jam-py** [comment]
I've released a new version with changes for jam.py to work with apache. I've tested it on windows xp but i think it will work on other versions od windows.

**Comment by Jmos** [comment]
Yes working with new project but demo is not success yet I will try tomorrow
Thank you very much

**Comment by jam-py** [comment]
You must turn off the multy processing connection pool option in the
project parameters.

вторник, 7 июня 2016 г. пользователь Janos Meggyeshazi написал:

**Comment by Jmos** [comment]
Yes it's working Thnx once more Your help !!
