### ISSUE TITLE
Photo from camera

### ISSUE THREAD

**Issue by arisobel** [jam-py/jam-py#100]
Dear Jam-py team / Andrew

I'm trying to get Photo from Camera, but getting message:
```getUserMedia() no longer works on insecure origins```

How to fix?

Thanks

**Comment by jam-py** [comment]
Hi, Ari

The reason can be this:
https://stackoverflow.com/questions/34165614/navigator-mediadevices-getusermedia-is-not-working-and-neither-does-webkitgetuse

Regards,
Andrew

вт, 23 апр. 2019 г. в 17:32, Ari Sobel <notifications@github.com>:
