### ISSUE TITLE
Add open and download button to attachment detail

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#102]
Hi,

One small feature that could benefit the usability would be the possibility of opening an attachment directly from the detail.

For example by having the url being a clickable link or by adding a couple of buttons to the right (new column or simply left aligned in the same column as the link)

![image](https://user-images.githubusercontent.com/9055742/56803969-799db200-6824-11e9-83d0-72f7e1beaa87.png)

**Comment by jam-py** [comment]
Ok, Davide. I'll think how to do it.

**Comment by jam-py** [comment]
Hi, Davide

I added the description of field methods to docs:
http://jam-py.com/docs/refs/client/field/m_download.html and
http://jam-py.com/docs/refs/client/field/m_open.html

There are examples. 
You can add buttons to view_form_created in the detail client module.

**Comment by ddavidebor** [comment]
Thank you very much, it works flawlessly
