### ISSUE TITLE
When using modeless form reference bug

### ISSUE THREAD

**Issue by MaxMorais** [jam-py/jam-py#103]
Hi @jam-py,

First thank you so much for that awesome framework.
I'm learning the basis of the framework, and testing all the possible options Jam-py can offer, and I think I faced one issue.

If I create one form, and set it as modeless, like into the image below, I cant access the attribute `task.pessoa.edit_form`, even the form is properly loaded into the UI

![Application builder](https://user-images.githubusercontent.com/1288676/56838521-ad90cb80-6854-11e9-84fd-748e9c5a4057.png)

I dont know if it's a bug or a feature, but I'm sending also a video, with more details

https://www.loom.com/share/72dfd7cb9705453c8a55dd583b629514

**Comment by jam-py** [comment]
Hi, Maxwell.

Regarding the feature in your video, when the form is modal,
the user can edit only one record at a time.

If the form is modeless, the user can simultaneously edit several records,
and each time the application creates a copy of the item,
opens it for record and then creates an edit form for the copy (not
the item).

This is not reflected in the documentation now. I will update it.
Thank you for the feedback.

Regards,
Andrew Yushev



сб, 27 апр. 2019 г. в 00:56, Maxwell Morais <notifications@github.com>:

**Comment by MaxMorais** [comment]
Hi @jam-py, thank you so much for your fast response!

I'll wait for the documentation update!
Tnx!

**Comment by jam-py** [comment]
Hi, Maxwell.
I reworked some topics of docs.
I took more that I expected, they all are interrelated.
The topic that explains how the edit works is
http://jam-py.com/docs/refs/client/item/m_edit_record.html
