### ISSUE TITLE
lines in the table disappear when resizing the browser or accessing by mobile phone

### ISSUE THREAD

**Issue by oswallcr** [jam-py/jam-py#104]
The detail lines disappear in the table when the browser is resized and also when accessing from a mobile phone.
Only the frame and the labels of the columns in the table are observed.
![mobile_view](https://user-images.githubusercontent.com/24613227/57390875-8a321e80-717a-11e9-9946-cf7e464b68be.png)

**Comment by jam-py** [comment]
Hi, Oswall

I am very sorry, Jam.py at the time do not support mobile devices.
I have plans to add this support, but it will take some time.
I hope to finish this work until the end of the year.
I updated the Jam.py roadmap:
http://jam-py.com/docs/releases/roadmap.html

Best wishes,
Andrew Yushev

ср, 8 мая 2019 г. в 19:18, oswallcr <notifications@github.com>:

**Comment by oswallcr** [comment]
Thank you very much Andrew for your response.
I think it's great to design the view for mobiles, since applications are
currently requested in this way.
I am starting to know your framework, but I can help, with pleasure.
Oswall

**Comment by jam-py** [comment]
Thank you for the offer of help!

**Comment by platipusica** [comment]
Hi Oswall

I've sent you the link to an video, it demonstrates how to run Jam.py server on Apple iPad Pro if you have access to one.

D.

**Comment by oswallcr** [comment]
Thank you. I will watch the video.
Oswall
