### ISSUE TITLE
Many-to-many relationships

### ISSUE THREAD

**Issue by nachtkinder** [jam-py/jam-py#105]
Hi,

This is more of a question rather than an issue really but GitHub seems not to differentiate the two.

I've only been using Jam.py for a couple of days now and am already impressed by its performance and the ease with which views and forms can be created (especially from a pre-existing database).  However, having consulted the documentation, I cannot see how to implement a many-to-many relationship between entities.

One of the use cases I have for this is associating tags to an entity.  One entity can have many tags associated with it just as any given tag can have many associated entities.  A simplified version of the tables would look something like:

__entity__
id  integer primary key
name text

__tag__
id  integer primary key
name text

__entity_to_tag__
id integer primary key (only to facilitate management through Jam.py)
entity_id integer
tag_id integer
reason_for_tag text
date_tagged date
tagged_by text

Is it currently possible to implement many-to-many relationships between database entities that use a join table (with added info columns)?

Regards,
Nachtkinder

**Comment by jam-py** [comment]
Hi Nachtkinder,

Yes, it is possible.
You should use lookup fields entity_id and tag_id in *entity_to_tag.*
If you are going to create *entity_to_tag *then create them
as lookup fields.
If *entity_to_tag* already exists set the manual mode and change these
fields. Open lookup tab and specify lookup item to *entity *and *tag *
respectively
and lookup field to name.

Regards,
Andrew Yushev


ср, 26 июн. 2019 г. в 13:32, Nachtkinder <notifications@github.com>:

**Comment by platipusica** [comment]
Like this?

![Screenshot from 2019-06-26 19-24-39](https://user-images.githubusercontent.com/9026100/60176180-2063f600-9848-11e9-8f11-559f27f26245.png)
[many_1.0.0_5.4.37_2019-06-26_19-25-46.zip](https://github.com/jam-py/jam-py/files/3329741/many_1.0.0_5.4.37_2019-06-26_19-25-46.zip)

**Comment by nachtkinder** [comment]
Hi Both,

Thanks for the quick replies.

@jam-py Do I have to create the entity_to_tag table in a Details group?

@platipusica Almost, except I wish to see rows from _tags_ in the details view rather than from _entity_to_tag_

Regards,
Nachtkinder

**Comment by platipusica** [comment]
Np
Just reshuffle stuff on this example :) Took me 2 mins...

BR

**Comment by jam-py** [comment]
I am sorry, but I think there is no need to create a detail,
just use lookup fields.


ср, 26 июн. 2019 г. в 15:18, platipusica <notifications@github.com>:

**Comment by jam-py** [comment]
Detail is needed if you want to create a one-to-many relationship.


ср, 26 июн. 2019 г. в 15:27, Andrew Yushev <yushevaa@gmail.com>:

**Comment by nachtkinder** [comment]
Hi Both,

Thanks for the help with this.
@jam-py You mentioning "lookup fields" has helped a lot.

I think I'm now close to what I want.

I created a new field "tags" on entity leaving "DB field name" empty.  I then specified the "Lookup item" as _entity_to_type_, "Lookup field" as _type_id_ and "Lookup field 2" as _name_.  I then added the new field to _entity_'s view and edit forms.

Unfortunately I get an error as soon as I select the _entity_ view from the navigation in the app:

"(1054, "Unknown column 'entity.' in 'field list'")"

I'm using a MySQL database to host the  _entity_, _tag_ and _entity_to_tag_ tables if this makes any difference.

Regards,
Nachtkinder

**Comment by jam-py** [comment]
You must not leave "DB field name" empty, if you have field tags set  "DB
field name" to it.
And there is no need for Lookup field 2.
Better try to create a new item *entity_to_tag1  *without manual mode and
try the concept.
You can delete it later.
It won't take much time.

Regards,
Andrew


ср, 26 июн. 2019 г. в 15:52, Nachtkinder <notifications@github.com>:

**Comment by nachtkinder** [comment]
Hi Again,

I have done as you suggested and created a field _tags_ on the _entity_ item and set the "DB field name" to it.  It does not appear to be possible to add more than one _tag_ to an _entity_ though.  What I expect to happen if I have a many-to-many relationship correctly implemented is that:
 - it should be possible to add an arbitrary number of _tags_ to an _entity_ either through the _tags_ field of the _entity_ item or by adding records to the _entity_to_tag_ item.
 - when an _entity_-_tag_ pairing is created by adding a record on _entity_to_tag_ it should show in _entity.tags_
 - when a tag is added to an _entity_ via its _tags_ field a new record should be created in _entity_to_tag_

I appreciate the advice you have offered this far.  Could you please take a look at the attached export and see if I've made any rookie errors?

Thanks,
Nachtkinder

[many_1.0.0_5.4.61_2019-06-26_16-27-01.zip](https://github.com/jam-py/jam-py/files/3330815/many_1.0.0_5.4.61_2019-06-26_16-27-01.zip)

**Comment by jam-py** [comment]
Hi,

I am sorry, I don't quite understand what you want.
I removed the tags field in the entity.
You can create any number of entity to tags record
by selecting entity and tag in the edit form.
If you need one-to-many relationship use details.

[many_1.0.1_5.4.61_2019-06-27_10-19-38.zip](https://github.com/jam-py/jam-py/files/3333410/many_1.0.1_5.4.61_2019-06-27_10-19-38.zip)

Regards,
Andrew

**Comment by nachtkinder** [comment]
Hi,

I'll try to explain better what it is I want to achieve:

I would like that the end user of the application I am developing is able to add multiple _tag_ associations to an _entity_ by editing that _entity_'s record or to associate a tag with one or more _entities_ by editing that _tag_'s record.  

I would like the workflow to be something like the following:

__To associate tags to selected entity__
 - User clicks edit/new from the _entity_ view.
 - User sees a "tags" field on the edit form that allows them to select _tag_s by name that will be associated to the _entity_ being created/edited.
 - Application creates entry (or entries) in _entity_to_tag_ to represent the associations between the _entity_ and its new _tag_s.

The "tags" field should not be created in the DB table storing _entity_ items.


__To associate entities with selected tag__
 - User clicks edit/new from the _tag_ view.
 - User sees an "entities" field that allows them to select _entitites_ by name that will have the edited/created _tag_ associated with them.
 - Application creates entry (or entries) in _entity_to_tag_ to represent the associations between the _entity_ and its new _tag_s.

The "entitites" field should not be created in the DB table storing _tag_ items.

In neither workflow should the user have to be aware of the _entity_to_tag_ item.  To the user they are merely adding _tag_s to _entities_ and vice versa.

At the UI level I imagine that this might work similarly to the one-to-many functionality that is described in the Jam.py docs with the user browsing for _tag_s from the _entity_ form and _entities_ from the _tag_ form.

Is that any clearer?

Thanks again for taking the time to help me with this.

Regards,
Nachtkinder

**Comment by jam-py** [comment]
I think I understand now. 
I include export file.
[many_1.0.2_5.4.61_2019-06-27_14-01-45.zip](https://github.com/jam-py/jam-py/files/3334341/many_1.0.2_5.4.61_2019-06-27_14-01-45.zip)

I added a new item entity_to_tags that have virtual_table attribute set to true
and tags field with KEYS type that can store a list of selected pk fields

Then I added the Add tags to entity button in the entity_to_tag client
module that creates an edit form for entity_to_tags:

```
function on_view_form_created(item) {
    item.add_view_button('Add tags to entity').click(function() {
        task.entity_to_tags.open({open_empty: true});
        task.entity_to_tags.append_record();
    });
}

```
and in the entity_to_tags client module I defined the
on_after_post event handler that adds records to the  
entity_to_tag when OK button is clicked:

```

function on_after_post(item) {
    if (item.tags.value.length) {
        for(var i = 0; i < item.tags.value.length; i++) {
            task.entity_to_tag.append();
            task.entity_to_tag.entity_id.value = item.entity.value;
            task.entity_to_tag.tag_id.value = item.tags.value[i];
            task.entity_to_tag.reason_for_tag.value = item.reason_for_tag.value;
            task.entity_to_tag.tagged_by.value = item.tagged_by.value;
            task.entity_to_tag.date_tagged.value = item.date_tagged.value;
            task.entity_to_tag.post();
        }
        task.entity_to_tag.apply(function() {
            task.entity_to_tag.refresh_page(true);
        });
    }
}

```
I hope that solve the problem.

Regards,
Andrew

**Comment by platipusica** [comment]
"Add tags to entity" produces no such table:

127.0.0.1 - - [28/Jun/2019 09:46:14] "POST /api HTTP/1.1" 200 -

Error: no such table: 
 command: SELECT ""."ID", ""."DELETED", ""."ENTITY", ""."TAGS", ""."TAGGED_BY", ""."REASON_FOR_TAG", ""."DATE_TAGGED", MANY_ENTITY_18."NAME" AS ENTITY_LOOKUP, NULL AS TAGS_LOOKUP FROM "" AS "" OUTER LEFT JOIN "MANY_ENTITY" AS MANY_ENTITY_18 ON ""."ENTITY" = MANY_ENTITY_18."ID" WHERE ""."DELETED"=0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/execute.py", line 158, in execute_sql_connection
    result = execute_command(cursor, db_module, command, params, select, ddl, messages)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/execute.py", line 61, in execute_command
    result = execute_select(cursor, db_module, command)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/execute.py", line 16, in execute_select
    cursor.execute(command)
OperationalError: no such table: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/wsgi.py", line 440, in on_api
    data = self.get_response(item, method, params)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/wsgi.py", line 465, in get_response
    return item.select_records(params, safe=True)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/server_classes.py", line 185, in select_records
    result = self.execute_open(params)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/server_classes.py", line 160, in execute_open
    rows = self.task.select(sqls[0], connection, db_module)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-5.4.52-py2.7.egg/jam/server_classes.py", line 925, in select
    raise Exception(error)
Exception: no such table: 
127.0.0.1 - - [28/Jun/2019 09:46:18] "POST /api HTTP/1.1" 200 -


D.

**Comment by platipusica** [comment]
Nice.

So, how to describe the virtual table? As an intermediate table to store the temporary values (selection)?

Btw, http://jam-py.com/docs/admin/items/item_editor_dialog.html

try to Search :)

**Comment by jam-py** [comment]
Hi, Dean

You are using 5.4.52 version. Please upgrade to latest.
Virtual table means that there is no underlining database.
You can use it to work with in-memory datasets, write code
in modules, create forms to enter, for example, some params
as in this code.

Regards,
Andrew

пт, 28 июн. 2019 г. в 05:15, platipusica <notifications@github.com>:

**Comment by nachtkinder** [comment]
Hi,

@jam-py @platipusica Thank you both for attempting to help me resolve the issues I am having with implementing my desired functionality with Jam.py.

Although Jam.py uses SQLAlchemy to interact with databases, it does not appear to take advantage of SQLAlchemy's declarative functionality which enables fields to be added to table-based classes without the need for a supporting database column.  Below, I have included links to SQLAlchemy's documentation of many-to-many relationships in the hope that it better explains what I was trying to achieve than I did ;)

https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#many-to-many


I thank you both again for the assistance but now believe that I cannot achieve my current goal with Jam.py in its current form.

A couple of ideas that could be explored that might make working with many-to-many relationships easier in Jam.py:

 - Allow virtual columns (with no supporting DB column to be added to an item.
 - Allow virtual table items to extend items based on database tables with virtual columns.

@jam-py With your permission I'd like to expand upon these ideas in additional issues.

Regards,
Nachtkinder

**Comment by jam-py** [comment]
I was wrong when I objected to Dean and Nachtkinder proposal to use
details for creating many-to-many relationships. It is the most natural
way to create them.

I knew the many-to-many concept, but didn't realize that I use it
constantly in my Jam.py applications. For example the invoice_table
in the Details group of the demo app sets relationship between customers
and tracks.

I created the Library app to demonstarate it.
[lib_1.0.0_5.4.61_2019-07-01_13-58-03.zip](https://github.com/jam-py/jam-py/files/3345342/lib_1.0.0_5.4.61_2019-07-01_13-58-03.zip)

It has two catalogs:

"Readers" with the Name field and
"Books" that also has the Name field

one jounal "Readers log" used to register readers visits with the following fields:

Visit date
Librarian
Reader

And one detail "Readers books"

Visit date
Reader
Book
Librarian

And linked it to the "Readers log" and allowed to edit it in the edit from.

The only thing to do to make the "Readers books" to support many-to-many
relationship is to add this event handler to the client module of the
"Readers log"

```

function on_before_post(item) {
    var rec_no = item.readers_books.rec_no;
    item.readers_books.each(function(rb) {
        rb.edit();
        rb.reader.value = item.reader.value;
        rb.librarian.value = item.librarian.value;
        rb.visit_date.value = item.visit_date.value;
        rb.post();
    });
    item.readers_books.rec_no = rec_no;
}

```

The on_before_post is triggered before the results of editing is saved
in the memory. In it I go through readers_books detail and set it
fields to the corresponding fields of readers_log. Also
I save the position of the cursor of the dataset and restore it after
setting the field values to avoid the jerking the cursor.

I also add the 'Select books' button to select books while editing
"Readers log".

```

function on_view_form_created(item) {
    var btn = item.add_view_button('Select books');
    btn.click(function() {
        item.select_records('book');
        item.alert('Select books and close the form to add them.');
    });
}

```

Nachtkinder, it is a pity that you don't like Jam.py.
If you have ideas to improve it they are welcomed.

Regards,
Andrew Yushev

**Comment by nachtkinder** [comment]
Hi,

@jam-py It's not that I "don't like" Jam.py (I do) but more that it doesn't fit my particular use case.

The end users of my application want to see (and edit) all information related to an _item_ in one place.  That place being the edit/view page of the item itself.  They do nor wish to, nor should they have to, interact with every join table that may associate another _item_ to the one they are interested in.  The _item_s I have specified for the examples are orders of magnitude simpler than the real ones.

I shall certainly keep an eye on Jam.py as it very nearly ticks all the boxes.

Regards,
Nachtkinder

**Comment by platipusica** [comment]
Hi Nachtkinder, 

on Demo, there is the option which is False by default, and that is:
    item.table_options.editable_fields = ['quantity'];

The Jam Doc is a bit outdated: http://jam-py.com/docs/refs/client/item/m_create_table.html
and it interferes with Double Click, which is True on Demo (Journal/Invoices/View Form)

Hence, set D.Click to False there and set on Client Module:
```
function on_view_form_created(item) {
    item.table_options.editable_fields = ['quantity'];
    .
    .
```

This will enable online update of quantity or any other integer, as per:

http://jam-py.com/docs/refs/client/item/at_table_options.html

Have a look at the new vid in here https://www.facebook.com/groups/jam.py/

Thoughts?

**Comment by tagwato** [comment]
> I was wrong when I objected to Dean and Nachtkinder proposal to use
> details for creating many-to-many relationships. It is the most natural
> way to create them.
> 
> I knew the many-to-many concept, but didn't realize that I use it
> constantly in my Jam.py applications. For example the invoice_table
> in the Details group of the demo app sets relationship between customers
> and tracks.
> 
> I created the Library app to demonstarate it.
> [lib_1.0.0_5.4.61_2019-07-01_13-58-03.zip](https://github.com/jam-py/jam-py/files/3345342/lib_1.0.0_5.4.61_2019-07-01_13-58-03.zip)
> 
> It has two catalogs:
> 
> "Readers" with the Name field and
> "Books" that also has the Name field
> 
> one jounal "Readers log" used to register readers visits with the following fields:
> 
> Visit date
> Librarian
> Reader
> 
> And one detail "Readers books"
> 
> Visit date
> Reader
> Book
> Librarian
> 
> And linked it to the "Readers log" and allowed to edit it in the edit from.
> 
> The only thing to do to make the "Readers books" to support many-to-many
> relationship is to add this event handler to the client module of the
> "Readers log"
> 
> ```
> 
> function on_before_post(item) {
>     var rec_no = item.readers_books.rec_no;
>     item.readers_books.each(function(rb) {
>         rb.edit();
>         rb.reader.value = item.reader.value;
>         rb.librarian.value = item.librarian.value;
>         rb.visit_date.value = item.visit_date.value;
>         rb.post();
>     });
>     item.readers_books.rec_no = rec_no;
> }
> ```
> 
> The on_before_post is triggered before the results of editing is saved
> in the memory. In it I go through readers_books detail and set it
> fields to the corresponding fields of readers_log. Also
> I save the position of the cursor of the dataset and restore it after
> setting the field values to avoid the jerking the cursor.
> 
> I also add the 'Select books' button to select books while editing
> "Readers log".
> 
> ```
> 
> function on_view_form_created(item) {
>     var btn = item.add_view_button('Select books');
>     btn.click(function() {
>         item.select_records('book');
>         item.alert('Select books and close the form to add them.');
>     });
> }
> ```
> 
> Nachtkinder, it is a pity that you don't like Jam.py.
> If you have ideas to improve it they are welcomed.
> 
> Regards,
> Andrew Yushev

Hi, testing Jam.py for a couple of hours.
Great work you have done so far, congratulations!
In this Library example, you are copying many values from the parent  record in "Readers log" to the Detail record in "Readers books" (item.reader.value, item.librarian.value, item.visit_date.value).
The problem is: this creates replicated data, which I'd like to avoid.
One possible solution seems to be: define the corresponding fields in "Readers books" as lookup fields of the parent record in "Readers log".
I've tried such alternative, but the results were not good: the fields that are being looked up become empty in the records inserted in "Readers book".
Can anyone help with this situation?

**Comment by platipusica** [comment]
Hi, 
as I can see, the "REaders books" has the lookup values for Book and Reader.
It does not have a lookup value for Librarian.

Is my understanding correct?

![Screenshot from 2019-08-05 11-51-39](https://user-images.githubusercontent.com/9026100/62437851-90369c00-b777-11e9-811f-772fcb599ee5.png)

**Comment by jam-py** [comment]
You have to create Librarians item and then add Librarian as a lookup field.
I is just a demo.

пн, 5 авг. 2019 г. в 06:53, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Correct.

@tagwato, would that work for you?

Thx
