### ISSUE TITLE
Mysql database don't refress on Pythonanywhere

### ISSUE THREAD

**Issue by syslibre** [jam-py/jam-py#108]
Hello,

I have an issue with jam.py on pythonanywhere. I added a catalog on jam.py. The table was created on mysql. a "drescribe table;" show good informations. But whent i want to modify my catalog in jam.py, the catalog's lines are empty.

**Comment by platipusica** [comment]
Hi,

could you please provide a screenshots?


Thx

**Comment by rrad0812** [comment]
Hi,
Hope it's not too late :)
It seems to me that you did not import metadata from your database.
Of course, you first need to tell Jam.py that the database is a 'legacy' system, that is, you want to import existing definitions.

Regards
Radosav
