### ISSUE TITLE
v.5.4.70 builder.html 

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#109]
After creating new project and running server, I got Empty page of builder.html for v.5.4.70 with no error message on console

**Comment by jam-py** [comment]
There was bug on Windows related to upgrade to the latest Werkzeug library
release.
I fixed it. Please upgrade to the version 5.4.71
Thank you for the message!

пт, 9 авг. 2019 г. в 17:06, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
The issue was fixed. Thanks for your prompt reply and response.
