### ISSUE TITLE
non visible item showing on Form

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#11]
Hi Andrew, 

just testing more your demo and found this: when an field is set on Catalogs as available (as per http://jam-py.com/docs/admin/items/edit_fields_dialog.html), the field is still showing on Form Edit?

For example, add a timestamp (datetime) to Tracks, set not to show it, and edit the Track. 
I think it should not be there. What do you think?

Cheers

Dean

**Comment by jam-py** [comment]
I can not repeate it, Dean
Can you send me your demo, I will see into.

Andrew

**Comment by dbabicwa** [comment]
No probs, here it is:
https://dl.dropboxusercontent.com/u/22479113/demo_1.3.37_3.3.1_2016-06-25_10-52-05.zip

Look for Tracks, Timestamp. It is a trigger on Track update:

[demo_1.3.37_3.3.1_2016-06-25_10-52-05.zip](https://github.com/jam-py/jam-py/files/332879/demo_1.3.37_3.3.1_2016-06-25_10-52-05.zip)

Thanks!
D.

**Comment by jam-py** [comment]
Hi, Dean

I am sorry, but I am afraid I don't understand the question. The field Timestamp is set as available and it is shown on the edit form.
As far as trigger is concerned. It is more natural way for the framework to use on_before_update event handler. Just add the following line in the on_before_post function in the client module of the Tracks:

item.timestamp.value = new Date();

**Comment by dbabicwa** [comment]
Ok, 

never mind, I figured out the Edit Form fields visibility! Thanks for the event tip!

Spasiba!

D.

**Comment by jam-py** [comment]
Pojaluista
