### ISSUE TITLE
[v.5.4.73] Master/Details save failed

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#111]
Hi,

After fixed a few issues regarding MSSQL, I applied v.5.4.73 and found some issues with 'Master/details' pages. 

If I tried to create a master record with detail record (e.g. Invoice or P.O. with its details), when I saved the record, it will show the error as attached.

But, if I created a master record without detail record, I can save the record. Then, re-open that master record to add some details, it's working with no error. 

Note: those Master/Details pages were created under v.5.4.62 and worked fine. But, after upgrading to v.5.4.73, the error was displayed on those pages but in DB the records were created.

![err4](https://user-images.githubusercontent.com/53944128/62935174-9d473100-bdf0-11e9-9422-6707ea7b5ced.png)

**Comment by PaulSanZa** [comment]
Note: in previous version 'deleted_flag' seemed to be INTEGER, but in v.5.4.73 it's changed to BOOLEAN

**Comment by PaulSanZa** [comment]
Reverted to v.5.4.62. No error, it worked fine

**Comment by jam-py** [comment]
Hi, @PaulSanZa  
I am sorry for these bugs.
It seems that this bug is not related to MSSQL, it happens before request is executed.
I can not repeat it. Is there some code related to this master-details or
is there something special that you are doing?
The simplest way to fix it if you send me the import file of the project. 
I promise not to use it in any way and delete after I solve the problem.

**Comment by PaulSanZa** [comment]
![err5](https://user-images.githubusercontent.com/53944128/62957915-e82c6d00-be1f-11e9-8eba-7c45bc4af59f.png)
Hi @jam-py,

The only code is to update 'created_by', 'created_date', 'updated_by', 'updated_date'. It worked fine with v.5.4.62 but not with 5.4.73 nor 5.4.74. I attached the image 'record_status is None'

**Comment by jam-py** [comment]
Thank you! It is more clear now.

**Comment by jam-py** [comment]
I am sorry, but can you send me the code of on_apply event handler where
you are doing these updates?


вт, 13 авг. 2019 г. в 19:17, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Now, I couldn't get 5.4.62

**Comment by PaulSanZa** [comment]
now = datetime.datetime.now()
    user_name = item.session['user_info']['user_name']
    
    for d in delta:
        d.edit()
        if d.created_by.value == '':
            d.created_by.value = user_name

        if d.created_date.value == '':
            d.created_date.value = now
            
        d.updated_by.value = user_name
        d.updated_date.value = now
        d.post()

**Comment by jam-py** [comment]
Thank you

**Comment by PaulSanZa** [comment]
Hi @jam-py ,

If I go with Postgres or MySQL, which version should I use? Is MariaDB ok to use?

**Comment by jam-py** [comment]
I would recommend Postgres.
As for this bug I can not repeat it still, but I think I know what change in the code causes it.
I'll correct it tomorrow.

**Comment by PaulSanZa** [comment]
Thanks so much for your advice and effort.

**Comment by platipusica** [comment]
That might be sqlalchemy issue.

I would suggest to create a really simple project with the same
on_apply event handler, try it, and if doesn't work attach it here so
we can try across the Globe.

MSsql patch version might be really an issue here as well.

Cheers

**Comment by PaulSanZa** [comment]
Hi,

After commented out apply(), no error. It works, but not sure whether it's the right way to do.


    if not delta.id.value:
        delta.edit()
        if delta.po_no.value == '':
            delta.po_no.value = po_no
            delta.post()
            #delta.apply()

**Comment by jam-py** [comment]
I tested the library and made a change that can be responsible for the bug.

ср, 14 авг. 2019 г. в 08:34, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Hi @jam-py ,

I upgraded to v.5.4.75 and tested. It worked fine. I also put 'delta.apply()' back to normal and no error at all. Thanks a lot for your support
