### ISSUE TITLE
[Question] : How to get lookup value with condition

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#112]
Hi,

How can I put condition for lookup value? For example, I want only active invoice to show up in the lookup. Or, I want only the pending invoice of a particular customer.

Also, if I want only some certain fields to be displayed. For example, if the logged in user has no permission to see the 'cost' field, then the product cost won't be displayed.

Can I do this? How?

Thank you.

**Comment by jam-py** [comment]
Hi,

Please try on_field_select_value event
http://jam-py.com/docs/refs/client/item/on_field_select_value.html

пт, 16 авг. 2019 г. в 10:50, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
I will try it. Many thanks.
