### ISSUE TITLE
[Report Params] Lookup item

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#113]
Hi,

I found an issue on Report Parameters, the lookup item didn't show anything and no error on console as well.

Another one, the Lookup list is text field.

Note: Python 3.7.3 (Windows), Jam.py v.5.4.75
![err6](https://user-images.githubusercontent.com/53944128/63214355-64d18b00-c141-11e9-9765-f11156f65a5d.png)

**Comment by jam-py** [comment]
Hi,

Thank you I'll correct the bug.

сб, 17 авг. 2019 г. в 18:50, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Appreciated.

**Comment by jam-py** [comment]
I fixed the bug

**Comment by PaulSanZa** [comment]
![err7](https://user-images.githubusercontent.com/53944128/63364434-c2631300-c39f-11e9-81c0-c0837a29a1c4.png)
Thank you for the fixing. Quick question. How to use 'Lookup Value List'?

**Comment by jam-py** [comment]
It was a bug, I fixed it. Please upgrade.

вт, 20 авг. 2019 г. в 19:12, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Thank you.
