### ISSUE TITLE
[Question] Attach image(s) in report dynamically

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#114]
Hi,

How can I attach image(s) e.g. product image into the report? I couldn't insert image object in LibreOffice with name like %(image)s.

**Comment by jam-py** [comment]
Hi,
I am sorry it is impossible now.
I plan to add this feature in future.

вс, 18 авг. 2019 г. в 19:01, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Thank you for your answer, I will find the workaround until then. I'm not sure whether you plan to add the SYSTABLE migration to another RDBMS instead of SQLite and the password encryption field in the table.

**Comment by platipusica** [comment]
Hi,

The sqlite is a base for serverless Apps, ie:


https://jampy-demo.azurewebsites.net/


https://platipusica-jampy-demo.glitch.me/


Is there any particular reason for moving the db?


Thx

**Comment by jam-py** [comment]
Hi,
I don't plan to migrate admin.sqlite to another database.
There is a f_secret_key field in in sys_params table this database.
It is assigned to a random value when project is created and is used 
to encrypt cookies.

**Comment by PaulSanZa** [comment]
No, I didn't request you to change it on your side. Just asked whether I can migrate on my end. I want to encrypt the password (either for application login or DB connection). That's all.
