### ISSUE TITLE
Read only issues

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#115]
Hello,

I have set a column in postgresql with a trigger to automatically generate a UUID inside.

In jampy, if i do the following:
* Create a field in manual db mode of type text, read-only
* Add field to form
* Create a new record

That fields get pupulated with NULL instead of the UUID. I think what is happening is that jampy is writing to the field NULL even if the field is read only when creating a new record

**Comment by jam-py** [comment]
Hello,
When you create a new record on the client, it is populated with nulls.
Read only for fields means that user can not change them in visual
controls.
Using triggers is not recommended in Jam.py.
You can initialize fields in the on_after_append event handler on the
client or
in on_apply on the server.

ср, 21 авг. 2019 г. в 14:45, Davide Bortolami <notifications@github.com>:

**Comment by ddavidebor** [comment]
Thank you :-)
