### ISSUE TITLE
[v.5.4.77] Question

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#116]
Hi,

I have questions on 'Item Group Editor'. In earlier version (e.g. 5.4.62 or 5.4.69), I realized that the 'Deleted flag' and 'Record ID' were treated as INTEGER. But, after upgrading to 5.4.7x, it seemed like something was changed but not being applied to those pre-configured items (e.g. Journal, Catalogs). On the screen, the 'Deleted' and 'ID' were set INTEGER and were linked to 'Primary key field' and 'Deleted flag'. But, if I clicked into 'Deleted flag', I found nothing to choose until I added a dummy BOOLEAN field (see attached image). Then, I see a field to link to 'Deleted flag'. 

Also, when I created some TEXT fields, I could also find them in 'Primary key field' as well. 
![e1](https://user-images.githubusercontent.com/53944128/63505915-9f02aa00-c4fe-11e9-999a-fc8c832e07d1.png)
![e2](https://user-images.githubusercontent.com/53944128/63505916-9f9b4080-c4fe-11e9-9a05-805bfedf5931.png)
![e3](https://user-images.githubusercontent.com/53944128/63505918-9f9b4080-c4fe-11e9-8b81-dd572059493d.png)

**Comment by jam-py** [comment]
Hi, I am sorry for the bug. I'll fix it tomorrow.
чт, 22 авг. 2019 г. в 13:12, PaulSanZa <notifications@github.com>:

**Comment by jam-py** [comment]
I am sorry, it is not a bug. I changed the accepted type of deleted
field to boolean. It is needed to give users ability to work with deleted
records.
Please create a boolean field and set it as deleted flag field.

чт, 22 авг. 2019 г. в 17:46, Andrew Yushev <yushevaa@gmail.com>:

**Comment by PaulSanZa** [comment]
The default deleted flag in Journal, Catalog were INTEGER

**Comment by jam-py** [comment]
The fact is that for jam INTEGER and BOOLEAN fields the corresponding
field in DB table is INTEGER. So as to performance it doesn't matter.
But when you create a filter for the INTEGER and BOOLEAN fields they are
different.

[image: deleted_filter.png]

I plan to enable user to work with deleted records. To view them and
undelete,
if necessary. This is the reason for the change.

You are right I didn't change it for new projects. I'll correct it.

чт, 22 авг. 2019 г. в 19:41, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
I understand it. Thanks for your explanation
