### ISSUE TITLE
[5.4.77] Required flag not working

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#117]
Hi,

I found that 'Required' flag is not working properly. Some items worked fine while some items did not validate the required field(s) at all. 

I created a new  'Supplier' and clicked 'Ok'. It saved empty record without validation and warning for required field(s)

Actually, I faced this issue for a while but couldn't reproduce it since it's quite unpredictable. I create several projects to test this. Only some items got the issue.

Note: I created only 1 item called 'Supplier' in the Catalog'. 

![er1](https://user-images.githubusercontent.com/53944128/63509805-471c7100-c507-11e9-93f8-ff15ebf93a9c.png)
![er2](https://user-images.githubusercontent.com/53944128/63510109-ef323a00-c507-11e9-8519-62145bf41e95.png)

**Comment by PaulSanZa** [comment]
I created 'Customer' and saved. This one got validated.

![e3](https://user-images.githubusercontent.com/53944128/63511288-fe66b700-c50a-11e9-9e83-3dfed8f4005a.png)

**Comment by jam-py** [comment]
Hi, I can not repeat the bug.
I check the code, it is ok.
Is there some errors in the browser debugger?
If you have some test project that has the bug,
can you send me the export file (Export button in the builder).

чт, 22 авг. 2019 г. в 14:31, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
After downloading Apache HTTP Server and tried it instead of using XAMPP. My notebook worked strangely. None of jam.py projects could be run even running through 'server.py'. The browser kept waiting for response. No error in the log files to investigate.

I needed to fix it and will send the export file to you once it's back to normal.

**Comment by PaulSanZa** [comment]
Hi,

I found the error in javasript already.

**Comment by PaulSanZa** [comment]
Hi,

I reopened this. I tested by creating new record, it worked. But, when I edited the existing records and empty the field(s) with 'required flag', it didn't work. It saved the data with empty required field(s).

I guessed it might relate to the Null and '' (empty string).

**Comment by jam-py** [comment]
I'll check it.

пт, 23 авг. 2019 г. в 14:34, PaulSanZa <notifications@github.com>:

**Comment by jam-py** [comment]
Can you specify the type of the field?

пт, 23 авг. 2019 г. в 14:39, Andrew Yushev <yushevaa@gmail.com>:

**Comment by jam-py** [comment]
Checked for all field types, can not reproduce.

пт, 23 авг. 2019 г. в 14:42, Andrew Yushev <yushevaa@gmail.com>:

**Comment by jam-py** [comment]
I tried all field types, can not reproduce.

пт, 23 авг. 2019 г. в 15:45, Andrew Yushev <yushevaa@gmail.com>:

**Comment by PaulSanZa** [comment]
Hi @jam-py,

Sorry for late reply. I accidentally tested it with TEXT, but haven't tried other data types yet. When I created a new record and clicked OK, it'll alert (as image#1). Then, I entered the data and saved it. Data was saved and got back to the list, I double-clicked the record to get back to edit mode. Deleted the data from those required fields (the one marked *) and clicked OK. The data was saved without any alert. The required fields validation was bypassed.

![e001](https://user-images.githubusercontent.com/53944128/63617793-97cdc000-c614-11e9-9dba-ec77065eb9d7.png)

![e002](https://user-images.githubusercontent.com/53944128/63617796-98665680-c614-11e9-916d-1283fb81fe33.png)

**Comment by PaulSanZa** [comment]
Ok, I got closer to the way to reproduce it. You may create an item 'Customer' with a few fields and put some of those fields as required field. Then, go to client side, you will see that the validation will work perfectly either on Insert or Edit mode.

Back to builder.html and add an empty function to .py or .js of that item. Go back to client side and test it. The validation will work only in Insert mode but not in Edit mode.

**Comment by PaulSanZa** [comment]
Hi @jam-py,

I'm sorry, I found the bug in my javascript missing logic to check whether the parameter is empty before Uppercase or Capitalize it. Then, it skipped the rests of the scripts.

Both mistakes (the above before previous closed and this one) caused the XAMPP and Apace freeze. After fixing the javascript issues, the server seems to be normal.

Big apology
