### ISSUE TITLE
Jam.py on XAMPP

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#118]
Hi,

Another strange thing. Today, I just configured jam.py [v.5.4.77] on XAMPP Apache. It was running fine for a while. Then, it seemed not working (not response). I restarted XAMPP Apache service and realized that the port that I configured 8888 was changed to other port number. After restarting, the port was back to 8888 and worked fine for a while and repeated the same for several times.

XAMPP latest version, jam.py latest version, mod_wsgi also the latest one on Windows 10

**Comment by platipusica** [comment]
Hi there,

Thanks for reporting.

Its almost impossible to test every User scenario tho, particularly xampp
which wouldn't be a production platform for many.

D.

**Comment by jam-py** [comment]
I don't think this is related to the web application,
The web application has no access to the server and the port
and can not change it.


чт, 22 авг. 2019 г. в 15:37, platipusica <notifications@github.com>:

> Hi there,
>
> Thanks for reporting.
>
> Its almost impossible to test every User scenario tho, particularly xampp
> which wouldn't be a production platform for many.
>
> D.
>

**Comment by PaulSanZa** [comment]
I switched to Apache HTTP Server. Seemed like it worked at first. After a while with builder.html, no response (same as XAMPP). I opened browser console and saw the attached error. Then, I had to restart Apache service.

![er4](https://user-images.githubusercontent.com/53944128/63538178-89fb3a80-c541-11e9-81e6-5051f88c03fd.png)

**Comment by PaulSanZa** [comment]
I found several article regarding XAMPP port changing. XAMPP developers confirmed that it's not unusual for the port that keep changing.

So, I turned off 'Safe mode'. The application on both sides (builder and client) worked fine even the port changed.

**Comment by platipusica** [comment]
Please read notes here about the Apache and "lazy" applications:
https://github.com/jam-py/jam-py/issues/67

Thanks

**Comment by PaulSanZa** [comment]
Refered to the #117 . After fixing javascript on my side, the server works fine
