### ISSUE TITLE
Duplicate feature

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#119]
One feature I really find missing is "duplicate". I find doing this copy pasting all the time:
* Open two tabs of the browser
* Manually copy fields
* Manually re-create similar details copy-pasting fields

It would be really lovely to have a button that does this

**Comment by jam-py** [comment]
You are right, this feature is needed.
I'll try to implement it.

чт, 22 авг. 2019 г. в 20:45, Davide Bortolami <notifications@github.com>:

**Comment by jam-py** [comment]
I'll add this feature in the 6 version, I am working on now.
