### ISSUE TITLE
Question regarding Summary fields

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#120]
Hi,

I have another question. In previous version, it seemed to count number of records when data type is not numeric. If numeric, it will sum the total. But, this one (as attached), it returned 'true'.

![err1](https://user-images.githubusercontent.com/53944128/63579114-1b0ef780-c5bc-11e9-979f-b9ee936eafc7.png)

**Comment by jam-py** [comment]
I am trying to reproduce this
пт, 23 авг. 2019 г. в 11:40, PaulSanZa <notifications@github.com>:

**Comment by jam-py** [comment]
I reproduced it

пт, 23 авг. 2019 г. в 13:55, Andrew Yushev <yushevaa@gmail.com>:

**Comment by jam-py** [comment]
I fixed the bug

пт, 23 авг. 2019 г. в 13:58, Andrew Yushev <yushevaa@gmail.com>:

**Comment by PaulSanZa** [comment]
Tested. It fixed. Thanks.
