### ISSUE TITLE
Question : Export scripts

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#121]
Hi,

I copied the Export script from the Jam.py example. Some item got 'Dict object is not callable'. Not sure what it meant. Is it any data type that couldn't use this script.

def export_scv(item):
    copy = item.copy()
    copy.open()
    file_name = item.item_name + '.csv'
    path = os.path.join(item.task.work_dir, 'static', 'files', file_name)
    with open(path, 'w', encoding='utf-8') as csvfile:
        fieldnames = []
        for field in copy.fields:
            if not field.system_field():
                fieldnames.append(field.field_name)
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for c in copy:
            dic = {}
            for field in copy.fields:
                if not field.system_field():
                    dic[field.field_name] = field.text
            writer.writerow(dic)
    return file_name

**Comment by jam-py** [comment]
This exception can be raised if you defined dict variable in your code
and overridden python dict function.
https://stackoverflow.com/questions/41605525/typeerror-dict-object-is-not-callable-while-using-dict/41605604
Can you send the traceback?


пт, 23 авг. 2019 г. в 12:33, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Hi,
I didn't have any special code for export.
![e01](https://user-images.githubusercontent.com/53944128/63590250-84e7cb00-c5d5-11e9-8681-fb37b002fbb0.png)
![e02](https://user-images.githubusercontent.com/53944128/63590251-84e7cb00-c5d5-11e9-9164-5d7e4a6dbe0e.png)

**Comment by jam-py** [comment]
I mean the server logs. This bug is on the server

пт, 23 авг. 2019 г. в 14:41, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
![err001](https://user-images.githubusercontent.com/53944128/63591387-e0678800-c5d8-11e9-96b3-82103bbd1d4b.png)

**Comment by PaulSanZa** [comment]
![err001](https://user-images.githubusercontent.com/53944128/63591508-2d4b5e80-c5d9-11e9-870e-0994917b550a.png)

**Comment by jam-py** [comment]
I fixed the bug, please upgrade

пт, 23 авг. 2019 г. в 15:07, PaulSanZa <notifications@github.com>:

**Comment by PaulSanZa** [comment]
Tested. It fixed. Thanks.
