### ISSUE TITLE
[v.5.4.78] Import script error on some items

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#124]
Hi,

I got error trying to import data on some items as attached. BTW, what's new in 5.4.79?

![e1](https://user-images.githubusercontent.com/53944128/64087183-26091b00-cd66-11e9-9a69-61cb27ec120a.png)

**Comment by platipusica** [comment]
Hi,

as before, which Python, OS, DB you importing into...

Thanks

**Comment by jam-py** [comment]
Hi, I am on a vacation now. I will be able to reply in a week.

**Comment by PaulSanZa** [comment]
Hi, no problem. Take your time and have a nice vacation

Note: Python 3.7.4, Windows, MSSQL2017 Express

**Comment by jam-py** [comment]
Hi, 

I fixed the bug

**Comment by PaulSanZa** [comment]
Hi,

Thanks, I'll check it out.
