### ISSUE TITLE
[v.5.4.78] Filters didn't get imported

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#125]
Hi,

I found another issue when I imported the project, the filters didn't get imported and I had to re-created those filters after being imported.

You may try to reproduce in 2 scenarios. Both won't import the filters
1. New server - import project Zip file from another server.
2. Same server - create new project and import project Zip file.

Note: Python 3.7.4, Windows, MSSQL 2017 Express

**Comment by rrad0812** [comment]
HI,
Would you like to try the 5.4.79 version, please

Regards,

**Comment by jam-py** [comment]
There is this bug. I'll try to fix it

**Comment by jam-py** [comment]
Fixed

**Comment by PaulSanZa** [comment]
Thanks
