### ISSUE TITLE
[v.5.4.78] Search didn't work with lookup fields

### ISSUE THREAD

**Issue by PaulSanZa** [jam-py/jam-py#126]
Hi,

Another issue. Search fields linking to the lookup fields (e.g. Product Category) will throw error "'Error converting data type nvarchar to numeric.". I created Product and Product Category items and when I got into Product page to search Product Category, it failed! No matter I input numeric or character(s), it will throw the same error.

I understand that it is linked by Product Category ID.

Also, I couldn't find the place to remove these lookup fields from being listed in Search criteria.

Note: Python 3.7.4, Windows, MSSQL 2017 Express

**Comment by PaulSanZa** [comment]
Filter the lookup field works with Filter Type as 1:1 only, right?

**Comment by rrad0812** [comment]
HI,
Would you like to try the 5.4.79 version, please

Regards,

**Comment by PaulSanZa** [comment]
Hi,

Thanks for your suggestion. Before trying, I'd like to know What's new in 5.4.79.

**Comment by rrad0812** [comment]
Hi,
How to AY says, import of items bug fixed. 

Radosav

**Comment by rrad0812** [comment]
My past hint relates to your previous two writings. 
For this particular one I must say that I do not fully understand the problem.

If you have successfully linked your two objects (Category ID) and selected lookup_value, there should be no problem. As far as I know there is no need for conversion here, the code simply returns the selected lookup_value field for the selected id.

And of course the reverse when searching.

Regarding the selection of the search box, look in the view form settings.

Regards,

**Comment by jam-py** [comment]
You can create IN filter that allows to select records

**Comment by jam-py** [comment]
If this bug is still actual, can you send server log with it,
or if it is on the client the exception from debugger.
