### ISSUE TITLE
on_field_select_value Event Problem

### ISSUE THREAD

**Issue by jptneumann** [jam-py/jam-py#127]
Hi!,

I'm trying to use the event **on_field_select_value**, but  isn´t trigged when I click the right buttom of the input field. I´m using the Jam.py version  5.4.81. Is this event working well?

My field use **Lookup Value List**. Using Typeahead is working well. I need to use with Input Field using **Lookup Value List**.

Simple example of use:

```
function on_field_select_value(field, lookup_item) {
    task.alert('LOOKUP: ' + field.field_name);
}
```

It´s not showing nothing when I click the right buttom of the lookup input field.... 

The on_field_select_value event have some bug?

Do you have any idea what is going on?

**Comment by jam-py** [comment]
Hi,

I checked this Jam.py version and this event works OK.
Can you create a simple project where you repeat this code
and send it to me?
If can also set the breakpoint in the jam.js file in the browser debugger.
Find the line

select_value: function() {

in jam.js and set the breakpoint on the line

this._do_select_value(copy);

and go into it.

Regards

пн, 14 окт. 2019 г. в 01:44, jptneumann <notifications@github.com>:

**Comment by rrad0812** [comment]
Hi there,

on_field_select_value by definition:
>>When user clicks on the button to the right of the field input or uses typeahead, the application >>creates a copy of the lookup item of the field and triggers on_field_select_value event. Use >>on_field_select_value to specify fields that will be displayed, set up filters for the lookup item, before >>it will be opened.

You have not set up values by above definitions.
In general, you should do incremental search with this event handler.

Salute, rrad

**Comment by jam-py** [comment]
@rrad0812,  the issue is about some situation where this event is not triggered at all.

**Comment by jam-py** [comment]
I think the code for the event handler was placed in the wrong module.
For example, the field belongs to the detail that is linked to its master and
the code is placed in the details item that belongs to the detail group.
