### ISSUE TITLE
URL field

### ISSUE THREAD

**Issue by mg64ve** [jam-py/jam-py#129]
Hi @platipusica ,

is it possible to create an URL field with HTML preview?
This field should contain an HTTP URL and display with a link or webpage preview.

Kindly le me know.
Thanks.
Best regards.

**Comment by jam-py** [comment]
Hello,
Can you explain where you want to add the URL
on the page when all forms are closed,
on view form or edit form, please.

вс, 1 дек. 2019 г. в 18:26, itresearch <notifications@github.com>:

**Comment by mg64ve** [comment]
As you can display images instead of file name, I would like to display a field containing an URL as a clickable link or as HTML preview in a different tab.
This it is in Edit View.
Is it possible to define custom field types with different behaviours?
Thanks.

**Comment by jam-py** [comment]
I send you a project.
I has one catalog named Test with two fields url_link and url_name.
In the client module I defined on_field_get_html handler:

`function on_field_get_html(field) {
    let item = field.owner;
    if (field.field_name === 'url_link') {
        return '<a href="' + field.text + '" target="_blank">' + item.url_name.text + '</a>';
    }
}`

[url_field.tar.gz](https://github.com/jam-py/jam-py/files/3910563/url_field.tar.gz)

Regards,
Andrew Yushev

**Comment by rrad0812** [comment]
Hi, there
Just a little extension, this is an old question!
In a lookup field, an html link should be placed that raises some filtered item with a given value of the lookup field.

For example:
If the A item has a lookup field on the L item, clicking on the L html link should raise some C view item, filtered for the value of the L field.

In particular, we have a user item and a field of associated monitor equipment defined in it, which is a lookup on the monitor item. If we put an html link on the value of that lookup field, how to raise the view item of users who have the same monitor, or maybe some item of equipment with monitors that are in some relation, better or worse, however with a given monitor.

This can be a solution for ad-hoc cross-over reports, with further decay into edit mode.

Radosav

**Comment by jam-py** [comment]
Hi, Radosav

If I understand you correctly, clicking on html link in the field won't
open view form to select the record.

Regards,
Andrew

пн, 2 дек. 2019 г. в 22:49, rrad0812 <notifications@github.com>:

**Comment by rrad0812** [comment]
Andrej,
I want to build a field with an html link, which, after clicking, would open the view form of an item filtered with the value of the field where the html link was posted.

Or how to raise the view form of an item, but with a passed parameter, with which would to filter the given item.

Radosav

**Comment by jam-py** [comment]
I'm sorry, Radosav, I didn't quite understand your question.
Can you give a real live example?

вт, 3 дек. 2019 г. в 23:57, rrad0812 <notifications@github.com>:
