### ISSUE TITLE
Edit Invoices Form number of culumns

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#13]
Hi Andrew
I added two fields for Invoices, Audit (updating with user_info), and Timestamp (last update), as per your suggestion.

Now, when Editing the Invoices, this two fields are showing below Total. Is there any way to make this form showing in three columns, so the Audit and Last Update would on the right from Total?

What I am trying is to have a more complex Form.

Thank you!
![screenshot from 2016-07-26 20 30 52](https://cloud.githubusercontent.com/assets/9026100/17137888/1f2fed54-5370-11e6-92e1-298abc8c6a68.png)

**Comment by jam-py** [comment]
Hi, 
You create inputs for fields by using create_inputs method of an item. In the demo it is called in the on_edit_form_created event handler. The method create inputs in the container that is passed as a parameter. You can specify number of columns in the options. 
Using this method you can create quite complex layouts. I want to make a FAQ and write about it in more detail. As soon as I do it I will inform you.

**Comment by dbabicwa** [comment]
Thank you
I was looking for "Interface programming" in the User_guide but no luck. There is some in jam-py-master/doc/programming/interface but I think this is not included in the zip.

Cheers,

D.
