### ISSUE TITLE
more on URL field

### ISSUE THREAD

**Issue by mg64ve** [jam-py/jam-py#131]
Sorry to be again on this topic.
The code you gave me @platipusica works.
However I have defined a field as a TEXT(400).
When I move my mouse over, it tries to display a preview which is an impediment to click the link.
Any idea to remove this back box preview?
Do you get my point?
thanks.

**Comment by jam-py** [comment]
Hello, you can do it by adding the following event handler to the same module:
```
function on_view_form_created(item) {
    item.table_options.show_hints = false;
}
```
Regards

**Comment by mg64ve** [comment]
Thanks @jam-py 
It works.
You can close this issue.
Cheers
