### ISSUE TITLE
Aplication builder: Item editor of any item: Edit any field

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#137]
Hi,
This is error in AppBuilder, when try to edit field definition:

Traceback (most recent call last):
  File "d:\jampy\5489\jam\wsgi.py", line 599, in on_api
    data = self.get_response(item, method, params)
  File "d:\jampy\5489\jam\wsgi.py", line 626, in get_response
    return self.server_func(item, params[0], params[1])
  File "d:\jampy\5489\jam\wsgi.py", line 635, in server_func
    func = getattr(obj, func_name)
AttributeError: 'AdminTask' object has no attribute 'server_valid_field_name'

Regards
rrad

**Comment by rrad0812** [comment]
Hi, again
The memory seems to be leaking
The Tracks interface first has and then does not have the TracksSold field.
No fields, any item, can be edited in AppBulder
The above error see does not occur every time.
The commands in the browser are dead.
5.4.89 is seriously ill.
rrad

**Comment by rrad0812** [comment]
Hi, again third раз :)
Checked in 5.4.87
Everything works, but I don't see where the code that calculates TracksSold is?!?
There is no Calculate tab on the edit field?!?

rrad

**Comment by jam-py** [comment]
Hi, Radosav

I can not repeat the bug.
Can it be related to the browser cache,
because you run version 5 after trying version 6?
Please try to hard reload the browser page.

Regards,
Andrew


сб, 1 февр. 2020 г. в 01:17, rrad0812 <notifications@github.com>:

**Comment by rrad0812** [comment]
Hi, Andrew
I use a slightly modified environment to develop Jam.py applications:
d:\jampy
--- 5481
--- 5483
--- 5487
--- 5489
------- builder
------- demo
------- html
------- jam
--- 601dev
I start by activating the virtual environment in d: \ jampy,
then cd 5489 so i put pythonpath on this directory.
That is how jam lib is linked to me.
Finally cd the demo and start the server.
I have custom batch files and everything goes pretty fast.

When I want to work with the 601dev version I simply change to cd ..\..\601-dev 
and set pythonpath, and again in demo, etc ...

So far, everything has been working properly.
The Demo application itself works fine.
But App Builder does not open the field editor, and also freezes after trying it the browser.
Sometimes the error is already reported and sometimes not.

I can only try the classic installation, but I repeat this has worked flawlessly so far.

Radosav

**Comment by rrad0812** [comment]
This is my command line:
Microsoft Windows [Version 10.0.18363.592]

radosav@DESKTOP-MYPC d:\jampy
> act

(jampy) radosav@DESKTOP-MYPC d:\jampy
> path
PATH=d:\jampy\Scripts;C:\ConEmu\ConEmu\Scripts;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\radosav\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\LibreOffice\program;C:\Program Files\Oracle\VirtualBox;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs;C:\Users\radosav\.bin;C:\Users\radosav\AppData\Local\Microsoft\WindowsApps;

(jampy) radosav@DESKTOP-MYPC d:\jampy
> python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'd:\\jampy\\Scripts\\python37.zip', 'd:\\jampy\\DLLs', 'd:\\jampy\\lib', 'd:\\jampy\\Scripts', 'C:\\Python37\\Lib', 'C:\\Python37\\DLLs', 'd:\\jampy', 'd:\\jampy\\lib\\site-packages']
>>> ^Z


(jampy) radosav@DESKTOP-MYPC d:\jampy
> cd 5489

(jampy) radosav@DESKTOP-MYPC d:\jampy\5489
> ppath
d:\jampy\5489

(jampy) radosav@DESKTOP-MYPC d:\jampy\5489
> python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'd:\\jampy\\5489', 'd:\\jampy\\Scripts\\python37.zip', 'd:\\jampy\\DLLs', 'd:\\jampy\\lib', 'd:\\jampy\\Scripts', 'C:\\Python37\\Lib', 'C:\\Python37\\DLLs', 'd:\\jampy', 'd:\\jampy\\lib\\site-packages']
>>> ^Z


(jampy) radosav@DESKTOP-MYPC d:\jampy\5489
> cd demo

(jampy) radosav@DESKTOP-MYPC d:\jampy\5489\demo
> run 80
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
127.0.0.1 - - [01/Feb/2020 15:02:37] "GET /builder.html HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:37] "GET /jam/css/bootstrap-cerulean.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/bootstrap-responsive.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/bootstrap-modal.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/datepicker.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/jam12.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/bootstrap-cerulean.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/jam.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /css/project.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/css/admin.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /dummy.html HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /dummy.html HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/jquery.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/bootstrap.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/bootstrap-modal.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/bootstrap-modalmanager.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/bootstrap-datepicker.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/jquery.maskedinput.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:38] "GET /jam/js/jam.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "GET /jam/js/md5.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "GET /jam/js/ace/ace.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "GET /js/events.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:39] "GET /js/demo.js HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "GET /jam/js/admin.js HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:40] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:41] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:41] "GET /jam/img/glyphicons-halflings.png HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2020 15:02:42] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:43] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:47] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:47] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:51] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:51] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:53] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:02:54] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2020 15:03:15] "POST /api HTTP/1.1" 200 -
Terminate batch job (Y/N)? n

**Comment by rrad0812** [comment]
But even though I choose no here, the server gets killed.
Could not retry logged in but it was browser out.

Radosav

**Comment by rrad0812** [comment]
Hi Andrew
I installed Jam.py the classic way, with copying the folder from the zip file to the project's root folder.
Everything works as it should.
I apologize.
Seem to Windows doesn't like the common command line for different sets of variables!!! 
My adventure with pythonpath is definitely over.
You can close this issue.

Regards,
Radosav
