### ISSUE TITLE
what/where is the function of  upload image in the demo?

### ISSUE THREAD

**Issue by autodataming** [jam-py/jam-py#138]
in the example 'demo',  for the customers table, I click the new button, then I can upload images as the following figure. 

what/where is the function of  upload image in the demo in the server side programing?

![image](https://user-images.githubusercontent.com/7656130/73802959-4435e400-47fa-11ea-9f83-7834cb258458.png)

**Comment by jam-py** [comment]
There is an upload method of the task that upload files to the server
static/files folder:
https://jam-py.com/docs/refs/client/task/m_upload.html

ср, 5 февр. 2020 г. в 04:32, autodataming <notifications@github.com>:
