### ISSUE TITLE
Moving existing app to jam-py?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#14]
Hi

let's say I have existing DB and would like to move it to jam-py. How would I do that?

Any utils to help in a process? 

Thanks

D.

**Comment by jam-py** [comment]
You create the project as usual and then delete common id and deleted
fields from catalogs and journals groups. Then before creating items set
DB manual mode flag in the Database parameter so the admin won't create
tables and add fields. After that add fields that correspond to your table
fields. Aslo you must specify the primary field. You might as well to add
indexes.

There are no utils now. I think it's possible to make some, but it's
database specific thing and I don't have time for it right now.


2016-08-08 7:09 GMT+03:00 dbabicwa <notifications@github.com>:
