### ISSUE TITLE
Internationalization application

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#140]
Hi,
I need to create field labels in different language. How can I do?
How can I set language for different users?
How can user choice default language?

Thanks.

**Comment by platipusica** [comment]
Hi, 

https://jam-py.com/docs/admin/language_support.html?highlight=translation

https://jam-py.com/docs/admin/language_translation.html?highlight=translation

You can see Lang here on Parameters:
https://demo.jam-py.com/builder.html

Thanks

**Comment by fabiograz** [comment]
Ok, this is to translate the builder interface e setup locale globally. But suppose I create a table Customers, with fields First name, Last name and I have 2 user; 1 Italian e 1 English.  If I set globally the English locale the Italian user sees numbers and date like English.
Furthermore, I want the Italian user sees for Customer table: "Clienti" and for its fileds "Nome", "Cognome", while the English user "Customers" and "First name", "Last name".
And so for Form captions, tabs and band labels, or report labels. 
Where I can translate this elements?
How can I do it?
Exists a user's profile page where they can set their own locale, theme, password, ...?

Thanks..

**Comment by platipusica** [comment]
Jam is not yet supporting multi tenancy.

That would include having addressed currency, localisation, etc. 

D.

**Comment by jam-py** [comment]
Hi,

Jam.py currently do not support Internationalization.

Regards,
Andrew Yushev


чт, 6 февр. 2020 г. в 08:26, platipusica <notifications@github.com>:

**Comment by fabiograz** [comment]
Ok.

Thanks.
