### ISSUE TITLE
Form tabs and bands reorder

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#141]
Hi,
I have created 3 tabs on a form. Now I need to reorder it.
How can I do it, without having to erase everything? 

For bands exists the same problem.

Thanks.

**Comment by jam-py** [comment]
Hi,

You can not do it.
Delete tabs and create new ones

Regards

чт, 6 февр. 2020 г. в 07:45, fabiograz <notifications@github.com>:
