### ISSUE TITLE
Italian Translation version 5.4.89

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#142]
Hi,
I've translated the builder interface in Italian language. I attach it to this issue.

Thanks,
Fabio Graziosi
[Italian_it-IT_2020-02-07_20-08-04.lang.zip](https://github.com/jam-py/jam-py/files/4172561/Italian_it-IT_2020-02-07_20-08-04.lang.zip)

**Comment by platipusica** [comment]
Grazie !

Question, how did you find Jam.py? From where?

Ciao

**Comment by fabiograz** [comment]
On alternativeto.not like alternative to cuba platform. 
This is a very great software, I hope you add some useful features like multi-tenancy and internationalization, and a better support for the user (a profile page, a reset password system, a theme changer by user, user language selection, and so on).

Good work!

**Comment by jam-py** [comment]
Hi, @fabiograz 

Thank you!
I plan to implement these features.

Thanks so much for the translation!
Can I add you to the Jam.py contributors list as the author of Italian translation?
https://jam-py.com/contributors.html
If you don't mind send me how should I mention you, please.
You can answer me using contact form
https://jam-py.com/contact.html

Regards

**Comment by fabiograz** [comment]
Thank,
I've send you a private message through yours contact form.

Best regards,
Fabio
