### ISSUE TITLE
Some buttons are untraslated

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#143]
Hi,
I've translated jam-py in Italian language. I've imported it on demo application, but some buttons are untranslated. In the image below you can see filters -> filtri, but Delete, New, Edit, untranslated.

![immagine](https://user-images.githubusercontent.com/11799153/74117877-64c6bb00-4bb9-11ea-81ba-bf9495a1a1a7.png)

Thanks,
Fabio.

**Comment by jam-py** [comment]
Hi, Fabio

Buttons  text is set when a new project is created.
Please, change buttons text in the index.html file.
In new projects, with package supporting the language, the buttons text
will be OK.

Regards,
Andrew

пн, 10 февр. 2020 г. в 05:59, fabiograz <notifications@github.com>:

**Comment by fabiograz** [comment]
Hi,
I analyzed the index.html and demo.js files to understand how the buttons are created and why the button filter is correctly translated. I noticed that it is builts dynamically inside the demo.js library while the other are coded directly inside index.html, in the footer section.
Wouldn't it be better to also build the footer in the same way, thus giving the possibility to create the buttons dynamically in the current application's language?

Thanks,
Fabio.

**Comment by jam-py** [comment]
Hi,

You are right. I can be done.
All forms are defined in task client module in the
on_view_form_created and on_edit_form_created event handlers.

For example:

    item.view_form.find("#edit-btn").on('click.task', function(e) {
        e.preventDefault();
        item.edit_record();
    });

here you can change the text of the button, for example:

item.view_form.find("#edit-btn").text(task.language.edit)

Here I set the text attribute of the button JQuery object
and task.language.edit is the translation of 'edit' to the currently
selected language.
Instead of text, the html attribute can be used with some html tags.

I'll do it for new projects in new release.

Regards,
Andrew






чт, 13 февр. 2020 г. в 17:40, fabiograz <notifications@github.com>:

**Comment by fabiograz** [comment]
Hi
I noticed that the application title and the menu are also built dynamically. So I think the same logic could also be used for these elements.

I also analyzed the demo, admin and langs databases. I believe that with a few changes the framework could be greatly enhanced.
Here are some changes to make to the system.

First for the admin database.
Modify the SYS_USERS table by adding the F_LANGS field (lookup to SYS_LANGS) which represents the selected user's language. The user management form must also be changed in order to select the language based on those present in the system (or available for the application).

Create two tables with the translations of the records present in the tables SYS_ITEMS, and SYS_FIELDS:
- SYS_ITEMS_LANG (ID, ITEM_ID, LANG_ID, TEXT_IN_LANG)
- SYS_FIELDS_LANG (ID, FIELD_ID, LANG_ID, TEXT_IN_LANG)

When a new element (item or field) is created, a record is inserted in the respective table (SYS_ITEMS_LANG for SYS_ITEM record, SYS_FIELDS_LANG for SYS_FIELDS) with reference to the default language of the project (SYS_PARAMS.F_LANGUAGE value). The description of element in the default language of the project must be stored in this record. For each element it will be possible to add the translation into one of the languages ​​available on the system. This translations ​​can be added from the field or table management form (a button must be provided next to each field to be translated to open the translation management form).

Interface change:
You must make the username clickable (if in safe mode) to open a form where the user can changes the language. In the same form he could changes the password. If not in safe mode the application are in default language (SYS_PARAMS.F_LANGUAGE).

In index.html the string <html lang = "en"> must be generated dynamically according to the selected language (SYS_PARAMS.F_LANGUAGE if not in safe mode).

When the code to be passed to the browser is generated, the server will search for each element in the language selected by the user, if the translation is not present, the default value will be used.

I don't think they are very complicated changes, but they could make the application more flexible and ready to be a valid alternative for building robust business applications.

Unfortunately I am not an expert on python, I am only starting now (I have experience in other programmer languages ​​with which I have created complex business applications), so I am not able to help you with coding. If you want we could discuss the implementation details together.

Best regards,
Fabio.

**Comment by platipusica** [comment]
Hi Fabio, 

Andrew is pushing out the Jam version 6, and all time taken with this work atm so no much left for anything. He does all of that in his free time. For free. 

The Internationalization is a no mean feat and was discussed in #140. 

What Jam needs the most, in my view, is traction. With no traction, will be left as a very niche software. Even with a tons of features...

D.

**Comment by jam-py** [comment]
It is a good idea!
It can be done quite easily.
But the problem remains with translation of item and field captions.
I plan to do it a bit later.

пн, 17 февр. 2020 г. в 05:50, platipusica <notifications@github.com>:
