### ISSUE TITLE
undefined Demo

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#146]
Hi,
in demo project, if I double click on task record  it open a form with title "undefined Demo"

![immagine](https://user-images.githubusercontent.com/11799153/74599413-b1ab0580-5081-11ea-97dd-43610e516e21.png)

It should be only "Demo" or "Task Demo".

Regards,
Fabio.

**Comment by jam-py** [comment]
Thank you!
I will fix the bug

вс, 16 февр. 2020 г. в 08:04, fabiograz <notifications@github.com>:
