### ISSUE TITLE
Inline fields value changes does not save new value

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#147]
Hi,
I create a table and add in "view form" one field as "edit fields".
Now I go into the application, open the table view form and double click on that field, change its value and hit return. When refresh the form the filed has the original value. If I go in edit form and change the value the application ask if I want to save the changed record, if I answer yes it is saved right.

You can reproduce it.

In demo application builder, select Customers Table, Form View, add "address" field to "edit fields". Now in Demo project refresh, go to Customers View Form, double click con address, change the value (add a char) and press return. Refresh form and address field show old value.

May you correct this?

Thanks,
Fabio.

**Comment by jam-py** [comment]
I'll check it

вт, 25 февр. 2020 г. в 06:34, fabiograz <notifications@github.com>:

**Comment by jam-py** [comment]
I fixed it in the 6 version (develop branch).
It is quite complex code and moving it to the 5 version
would require a lot of testing.
I plan to publish a new version in a couple of weeks.


пт, 6 мар. 2020 г. в 02:29, pubmania <notifications@github.com>:

**Comment by fabiograz** [comment]
Ok,
thanks. I'll test when you release the new version (I hope soon), and if ok I'll close the issue.
Thanks for the effort,
Fabio.

**Comment by jam-py** [comment]
Hi, Fabio

I also add new translation phrases in the new version.

Regards,
Andrew

пт, 6 мар. 2020 г. в 12:43, fabiograz <notifications@github.com>:
