### ISSUE TITLE
Mssing type in field definition

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#148]
Hi,
in Jam-py you can define for a field the type "currency". In this manner forex symbol is displayed in front of value.
it might be useful to add the field type "percentage" (based on type float) so it display a "%" after the value in the form.

Thanks,
Fabio.

**Comment by jam-py** [comment]
Hi, Fabio

You can write on_field_get_text event handler to apply any formatting you
need
https://jam-py.com/docs/refs/client/item/on_get_field_text.html

Regards,
Andrew

вт, 25 февр. 2020 г. в 07:57, fabiograz <notifications@github.com>:

**Comment by fabiograz** [comment]
Ok,
thanks. It works.
