### ISSUE TITLE
jam-project.py fails on python 3.8

### ISSUE THREAD

**Issue by pubmania** [jam-py/jam-py#149]
![image](https://user-images.githubusercontent.com/1966557/75872649-7725c480-5e06-11ea-9744-059af2d85c9a.png)

Hi Looks like the current version uses some function time.clock which is not compatible with python 3.8. It works till 3.7 but was deprecated in version 3.3 based on the explanation provided on [stackoverflow](https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8)

**Comment by jam-py** [comment]
I fixed this.
Thanks

ср, 4 мар. 2020 г. в 13:56, pubmania <notifications@github.com>:
