### ISSUE TITLE
New DB module?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#15]
Hello, 

I am struggling to get the cx_Oracle working with jam-py. 
Example:
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> con = cx_Oracle.connect('HR/HR@127.0.0.1/xe')
>>> print con.version
11.2.0.2.0

This is proving that cx is ok.

Than I try an new db module, ie:
.
.
import cx_Oracle

NEED_DATABASE_NAME = True
NEED_LOGIN = True
NEED_PASSWORD = True
NEED_ENCODING = False
NEED_HOST = False
NEED_PORT = False
CAN_CHANGE_TYPE = False
CAN_CHANGE_SIZE = False

def connect(database, user, password): -- this is a problem!
    #def connect(database, user, password, host, port, encoding): -- this is a problem as well!

    #connection = cx_Oracle.connect(database=database, user=user, password=password, host=host, port=port, encoding=encoding)
    connection = cx_Oracle.connect(user,password,database)
    cursor = connection.cursor ()
   .
   .
    cursor.close ()
    connection.close ()
    return connection

Whatever I try with this two examples I can't get it to work. With only db,usr and pass, the jam-py will report:
"connect() takes exactly 3 arguments (6 given)"

If I try with database, user, password, host, port, encoding, jam-py will report:
"maximum recursion depth exceeded"

What do I need to do to pass this point?

Thanks!

**Comment by jam-py** [comment]
Hi.
May be, judging by the

con = cx_Oracle.connect('HR/HR@127.0.0.1/xe')

you should set

NEED_LOGIN = False
NEED_PASSWORD = False


2016-08-24 11:13 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Hi Andrew

I tried a lot of combination, but I think the problem is deeper, ie:

  File "/usr/local/lib/python2.7/dist-packages/jam.py-3.3.1-py2.7.egg/jam/server_classes.py", line 812, in execute_sql
    connection = db_module.connect(db_database, db_user, db_password, db_host, db_port, db_encoding)
TypeError: connect() takes exactly 1 argument (6 given)

Looks like jam-py is always passing 6 args to connection, and this is where cx_Oracle is failing.

**Comment by jam-py** [comment]
I am sorry for the delay. I was on vacation.

Please try the following:

NEED_DATABASE_NAME = True
NEED_LOGIN = False
NEED_PASSWORD = False
NEED_ENCODING = False
NEED_HOST = False
NEED_PORT = False
CAN_CHANGE_TYPE = False
CAN_CHANGE_SIZE = False

def connect(database, user, password, host, port, encoding):
    connection = cx_Oracle.connect(database)
    return connection


2016-08-26 8:57 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Thanks Andrew to look into this.
Yes, figured the above, but now I am stumbling with a SQL, ie:

 * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET / HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /jam/css/bootstrap.css HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /jam/css/bootstrap-responsive.css HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /jam/css/datepicker.css HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /jam/css/bootstrap-modal.css HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /jam/css/jam.css HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /css/project.css HTTP/1.1" 304 -
130.95.255.66 - - [29/Aug/2016 16:57:31] "GET /dummy.html HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/jquery.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/bootstrap.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /dummy.html HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/bootstrap-modalmanager.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/bootstrap-datepicker.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/bootstrap-modal.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/md5.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/jam-typeahead.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/js/jam.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /static/img/j.png HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "POST /api HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /js/demo.js HTTP/1.1" 200 -
130.95.255.66 - - [29/Aug/2016 16:57:32] "GET /jam/img/glyphicons-halflings.png HTTP/1.1" 200 -

Error: ORA-00905: missing keyword

 command: SELECT "demo_invoices"."deleted", "demo_invoices"."id", "demo_invoices"."customer", "demo_invoices"."invoicedate", "demo_invoices"."subtotal", "demo_invoices"."tax", "demo_invoices"."taxrate", "demo_invoices"."total", "demo_customers7"."address" as "billing_address_lookup", "demo_customers7"."city" as "billing_city_lookup", "demo_customers7"."country" as "billing_country_lookup", "demo_customers7"."postalcode" as "billing_postal_code_lookup", "demo_customers7"."state" as "billing_state_lookup", "demo_customers7"."lastname" as "customer_lookup", "demo_customers7"."firstname" as "firstname_lookup" FROM ("demo_invoices" left join "demo_customers" as "demo_customers7" on "demo_invoices"."customer" = "demo_customers7"."id") WHERE "demo_invoices"."invoicedate" >= '2015-08-29' AND "demo_invoices"."deleted"=0 order by "demo_invoices"."invoicedate" desc limit 11 offset 0
 params: None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-3.3.1-py2.7.egg/jam/server_classes.py", line 784, in execute
    result = execute_command(cursor, command, params)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-3.3.1-py2.7.egg/jam/server_classes.py", line 684, in execute_command
    cursor.execute(command)
DatabaseError: ORA-00905: missing keyword


I tried to run the above SQL in sqldeveloper, but no luck. Is it possible that Oracle SQL is way more different than sqlite or mysqlite?

**Comment by jam-py** [comment]
I've never used  Oracle SQL, so I can't answer your question. In any way, I
suppose the differences may be taken into account in the code. To do so I
must to install the Oracle. I will try to do so on the weekend. I will send
you a mesage if I succeed.

2016-08-30 11:34 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Cheers.

I'm using Oracle XE on Linux, and installing python driver cx_oracle is on older link here for the databases. I can provide oracle database dump if you need it since migrated from sqlite -> mysql -> oracle :) Let me know!

**Comment by jam-py** [comment]
Cheers.

I have installed Oracle and cx_Oracle library. The problem with adding
Oracle to the framework is paging in the select statment (limit and
offset). Starting from Oracle 12c, there is a row limiting clause so the
adding may be quite simple. But with lower oracle version it is very
complex. I didn't make it yet because I installed 11g version. Will it suit
you if I do it for versions greater than 12c

2016-08-30 15:57 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Hi Andrew, 
thank you for your time in doing it.
I think it is acceptable to use min 12c for whoever likes to use Oracle.

Dean

**Comment by jam-py** [comment]
There is no xe edition yet for Oracle 12.

2016-09-06 4:18 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by jam-py** [comment]
I hav just found this:

You cannot use Enterprise for development without paying for it. If you use
it under the 'Personal database' rules you may do so provided you and no
one else ever accesses the database or any tools referencing it, but the
moment another person does you are in violation of the licensing
restrictions in the neighborhood of around $40,000.00 USD * number of cores
(multiplied by Oracle Licensing's core multiplier).
May be to wiat until xe 12 is released?


2016-09-06 10:52 GMT+03:00 Andrew Yushev <yushevaa@gmail.com>:

**Comment by dbabicwa** [comment]
I think we can use it for free as developers....XE 11 is missing support for a number of things anyway, and the DB size is limited :(

**Comment by jam-py** [comment]
Ok. I'll try to do this.

2016-09-06 11:16 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
How is it going? Can I help with anything?

**Comment by jam-py** [comment]
I did it. Just have to test it. I will publish next week. I will inform you
then.

2016-09-17 17:22 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Thanks. Let me know and I will try to help with testing.
Cheers!

**Comment by jam-py** [comment]
Hi, Dean.

I've published new virsion of the framework. It supports oracle. It is not
limited to 12 version of the oracle. I worked with oracle xe 11g. I had no
experience with oracle previously and I hope you will test it. Any comments
and suggestions are wellcome.

Andrew

**Comment by dbabicwa** [comment]
Thank you Andrew. 
Will try as soon as I can and report back. 
Cheers
Dean

**Comment by dbabicwa** [comment]
Hi Andrew, 

when creating a new empty project and importing data from DEMO, the import doesn't work, log file:

Import: reading data
Import: checking data integrity
Import: analyzing changes
CREATE TABLE "DEMO_CUSTOMERS"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"FIRSTNAME" TEXT,
"LASTNAME" TEXT,
"COMPANY" TEXT,
"ADDRESS" TEXT,
"CITY" TEXT,
"STATE" TEXT,
"COUNTRY" TEXT,
"POSTALCODE" TEXT,
"PHONE" TEXT,
"FAX" TEXT,
"EMAIL" TEXT,
"SUPPORT_REP_ID" INTEGER)

CREATE TABLE "DEMO_INVOICES"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"CUSTOMER" INTEGER,
"INVOICEDATE" TEXT,
"SUBTOTAL" REAL,
"TAXRATE" REAL,
"TAX" REAL,
"TOTAL" REAL)

CREATE TABLE "DEMO_TRACKS"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"NAME" TEXT,
"ALBUM" INTEGER,
"MEDIA_TYPE" INTEGER,
"GENRE" INTEGER,
"COMPOSER" TEXT,
"MILLISECONDS" INTEGER,
"BYTES" INTEGER,
"UNITPRICE" REAL,
"TRACK" TEXT,
"TRACKS_SOLD" INTEGER)

CREATE TABLE "DEMO_ALBUMS"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"TITLE" TEXT,
"ARTIST" INTEGER)

CREATE TABLE "DEMO_ARTISTS"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"NAME" TEXT)

CREATE TABLE "DEMO_GENRES"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"NAME" TEXT)

CREATE TABLE "DEMO_MEDIA_TYPES"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"NAME" TEXT)

CREATE TABLE "DEMO_INVOICE_TABLE"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"MASTER_ID" INTEGER,
"MASTER_REC_ID" INTEGER,
"TRACK" INTEGER,
"QUANTITY" INTEGER,
"UNITPRICE" REAL,
"AMOUNT" REAL,
"TAX" REAL,
"TOTAL" REAL)

CREATE  INDEX "DEMO_INVOICE_TABLE_IDX" ON "DEMO_INVOICE_TABLE" ("MASTER_ID", "MASTER_REC_ID")
CREATE  INDEX "DEMO_INVOICES_IDX" ON "DEMO_INVOICES" ("DELETED" DESC, "INVOICEDATE" DESC)
None

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/dataset.py", line 170, in get_raw_value
    value = self.get_data()
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/dataset.py", line 57, in get_data
    row = self.get_row()
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/dataset.py", line 54, in get_row
    raise Exception, u'An attempt to get a field value in the empty dataset - item: %s, field: %s ' % (self.owner.item_name, self.field_name)
Exception: An attempt to get a field value in the empty dataset - item: sys_items, field: parent

sys_items error - parent: An attempt to get a field value in the empty dataset - item: sys_items, field: parent
Import error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/adm_server.py", line 1284, in analize
    db_sql.append(indices_insert_sql(task.sys_indices, d, table_name, get_new_fields(d.owner_rec_id.value)))
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/adm_server.py", line 2506, in indices_insert_sql
    return change_foreign_index(delta)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/adm_server.py", line 2496, in change_foreign_index
    fields = get_table_fields(items, it_fields)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/adm_server.py", line 2083, in get_table_fields
    parent_fields.filters.owner_rec_id.value = [fields.owner.parent.value]
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/dataset.py", line 185, in get_value
    value = self.get_raw_value()
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/dataset.py", line 180, in get_raw_value
    self.do_on_error(self.type_error() % (''), e)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/dataset.py", line 461, in do_on_error
    raise TypeError(mess)
TypeError: An attempt to get a field value in the empty dataset - item: sys_items, field: parent

Import: deleteing tmp files


The screen showing:
![jam](https://cloud.githubusercontent.com/assets/9026100/18822148/5dbb6b62-83df-11e6-8249-dec3835d0c02.png)


Hope this helps!

**Comment by jam-py** [comment]
Thank you. I overlooked this error. It is caused by foreign keys creation.
I have corrected it and banned an import for SQlite database while I
rework it.


2016-09-26 6:50 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
No problem. I got MySQL working with demo and now trying Oracle. If I may suggest, please use something else instead of "DEMO_INVOICES"."DATE" since DATE is reserved word in Oracle.

**Comment by jam-py** [comment]
It was called invoicedate before I changed it to date. And it will not be a
problem in Oracle as well.

2016-09-27 11:48 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Moved data to Oracle today. I am getting below when run a project:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/third_party/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/wsgi.py", line 86, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/wsgi.py", line 96, in wsgi_app
    response = getattr(self, 'on_' + endpoint)(request, **values)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/wsgi.py", line 178, in on_api
    return self.create_post_response(request, r)
  File "/usr/local/lib/python2.7/dist-packages/jam.py-4.0.18-py2.7.egg/jam/wsgi.py", line 153, in create_post_response
    buff = json.dumps(result, default=common.json_defaul_handler)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected

This is happening even with a small example like this one attached:


[test_1.0.0_4.0.18_2016-09-28_14-56-24.zip](https://github.com/jam-py/jam-py/files/497293/test_1.0.0_4.0.18_2016-09-28_14-56-24.zip)


Hope this helps!

**Comment by jam-py** [comment]
Unfortunately there is too little information in the error log to find the
problem. I've tried the project and it works fine. Can you describe what
are you doing when this error appears. One other way is to copy jam folder
from package to the project directory and and in jam/wsgi.py add the
following line:

*print result*

before

*buff = json.dumps(result, default=common.json_defaul_handler)*

Thanks for help


2016-09-28 10:01 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by jam-py** [comment]
The error occurs when the request result is converted to json. So I need to
know the result of the request (*print result*) to correct the code. Have
you tried to import the demo?

Andrew

2016-09-28 13:39 GMT+03:00 Andrew Yushev <yushevaa@gmail.com>:

**Comment by dbabicwa** [comment]
Hi Andrew,
the import doesn't work as per above error from a couple of days ago. 
Here is the *print* output.
[print.txt.txt](https://github.com/jam-py/jam-py/files/499744/print.txt.txt)


I have jam on one VM and DB on the other VM, can connect:

sqlplus demo2@MARS
SQL*Plus: Release 11.2.0.2.0 Production on Thu Sep 29 11:57:41 2016
Copyright (c) 1982, 2011, Oracle.  All rights reserved.
Enter password:
Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
SQL> select table_name from user_tables;

TABLE_NAME
------------------------------
DEMO_ALBUMS
DEMO_ARTISTS
DEMO_CUSTOMERS
DEMO_GENRES
DEMO_INVOICES
DEMO_INVOICE_TABLE
DEMO_MEDIA_TYPES
DEMO_TRACKS
8 rows selected.

Here is the oracle dump. You might import this with:
impdp \'/ as sysdba\' directory=data_pump_dir dumpfile=jam.dmp SCHEMAS=demo2.log 
providing data_pump_dir is set to somewhere.

Or, pls send me your demo oracle dump.
Thanks

**Comment by dbabicwa** [comment]
I found it Andrew!

The bug is in:
"Multiprocessing connection pool" and "Persistent connection" checked, Im getting Circular reference detected!

**Comment by jam-py** [comment]
It is not all clear. It takes time and there is a lot of current work. I'll
do it on the weekend.

2016-09-29 9:49 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Not a problem, you are doing great stuff ! Cheers

**Comment by jam-py** [comment]
Hello, Dean

I am sorry for the delay. I found a problem with Oracle blob fields and
wanted to correct it but can't still finish it yet.

You were right about multiprocessing connection pool. It is not connected
to Oracle. There were situations when it happened when server works on
Windows.

Kind regards,
Andrew



2016-09-30 10:37 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Fantastic, no rush at all. I think if you could get it running, this would be a great milestone for the project!
Cheers

**Comment by jam-py** [comment]
Hello, Dean

I published the jam.py on github. It supports blob fields now.

Regards,
Andrew


2016-10-05 10:52 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Excellent news! Let me do some testing and go from there!
