### ISSUE TITLE
strange issue with sorting dates

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#151]
Here is the export and data.

Sort ie by startdate or enddate and then paginate. NOt sure where did dates go? :)

Using Python3.7.4

[t.sqlite.gz](https://github.com/jam-py/jam-py/files/4406217/t.sqlite.gz)

[fivethirtyeight_1.0.0_5.4.93_2020-03-31_09-16-04.zip](https://github.com/jam-py/jam-py/files/4406218/fivethirtyeight_1.0.0_5.4.93_2020-03-31_09-16-04.zip)

**Comment by jam-py** [comment]
Hello

There are records with no date.

вт, 31 мар. 2020 г. в 04:28, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Yes Andrey, 

but try to SORT, wouldn't date appear when sorted up/down?

**Comment by jam-py** [comment]
Dean, I think that If there is no date, there wouldn't be date

вс, 5 апр. 2020 г. в 14:26, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
:)

There is a date Andrey :) If you click on sort startdate (down), the date does not appear, than on next few pages it appears, than not again.

So it's confusing...


![Screenshot from 2020-04-06 09-55-42](https://user-images.githubusercontent.com/9026100/78516628-d7849900-77ec-11ea-98df-3146827b7030.png)

**Comment by rrad0812** [comment]
Hi, there
It's not a date field.

This is ddl for the table:
CREATE TABLE approval_polllist (
    "president" TEXT,
    "subgroup" TEXT,
    "modeldate" TEXT,
    "startdate" TEXT,
    "enddate" TEXT,
    "pollster" TEXT,
    "grade" TEXT,
    "samplesize" REAL,
    "population" TEXT,
    "weight" REAL,
    "influence" REAL,
    "approve" REAL,
    "disapprove" REAL,
    "adjusted_approve" REAL,
    "adjusted_disapprove" REAL,
    "multiversions" TEXT,
    "tracking" TEXT,
    "url" TEXT,
    "poll_id" INTEGER,
    "question_id" INTEGER,
    "createddate" TEXT,
    "timestamp" TEXT, 
    "id" INTEGER);

Regards,
Radosav

**Comment by platipusica** [comment]
Would that matter? ;)

select startdate from approval_polllist order by startdate desc;
.
.
1/1/2018
select count(startdate) from approval_polllist order by startdate desc;
11314
select count(*) from approval_polllist;
11314
select startdate from approval_polllist order by startdate desc;
.
.
1/1/2018
 select startdate from approval_polllist order by startdate asc;
.
.
9/9/2019

select * from approval_polllist where id = 1349;
Donald Trump|All polls|3/17/2020|1/1/2018|1/3/2018|Rasmussen Reports/Pulse Opinion Research|C+|1500.0|lv|0.13831675|0.0|45.0|53.0|39.159259|54.648737||T|http://www.rasmussenreports.com/public_content/politics/trump_administration/trump_approval_index_history|50753|80144|1/4/2018|19:13:27 17 Mar 2020|1349

select startdate from approval_polllist where id = 1349;
1/1/2018


And this record is **NOT** showing in Jam...Why is it not showing?

**Comment by jam-py** [comment]
Hello,

Sqlite does not have data type.
Jam.py stores data values in TEXT fields but
they must be in the following format YYYY-MM-DD.

I must to change the code to take into account this.

вт, 7 апр. 2020 г. в 07:23, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Ok, thanks.
