### ISSUE TITLE
Free sqlite3 DB converted from MS Access

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#153]
https://github.com/jpwhite3/northwind-SQLite3

Did not try it though.

**Comment by platipusica** [comment]
Fantastic tool for MS Access -> sqlite3 and mysql  conversion:

https://github.com/clytras/AccessConverter/releases

**Comment by jam-py** [comment]
Interesting!


вс, 5 апр. 2020 г. в 16:46, platipusica <notifications@github.com>:

**Comment by rrad0812** [comment]
For migrating to/from any of the following database formats: Oracle, MySQL, MariaDB, SQL Server, PostgreSQL, IBM DB2, IBM Informix, InterSystems Caché, Teradata, Visual Foxpro, SQLite, FireBird, InterBase, Microsoft Access, Microsoft Excel, Paradox, Lotus, dBase, CSV/Text and transfer any ODBC DSN data source to them, I used to ESF database migration toolkit. 

And then my trial expired :)

**Comment by platipusica** [comment]
This file:
https://github.com/jpwhite3/northwind-SQLite3/blob/master/Northwind_populate_data.py

nicely populates above Northwind DB Order table with random data. It might be used for testing for someone who is interested.

**Comment by platipusica** [comment]
Sqlite3 at.al database model 

https://gist.github.com/dannguyen/f056d05bb7fec408bb7c14ea1552c349#file-schemacrawler-sqlite-macos-howto-md

Based on:

http://www.schemacrawler.com/diagramming.html

**Comment by platipusica** [comment]
Database model generated by above tool, DB from:
https://cdn.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

Command:
```
java -classpath ../../_schemacrawler/config:$(echo ../../_schemacrawler/lib/*.jar | tr ' ' ':') schemacrawler.Main --server=sqlite --database=chinook.db --user= --password= --info-level=maximum -c=schema --output-format=png -o=chinook.png
```

![Uploading chinook.png…]()

**Comment by platipusica** [comment]
Fantastic tool!

Now, how come there are no foreign keys on Jam.py Demo? :)

**Comment by jam-py** [comment]
Hi, Dean

What do you mean?
Invoices journal has a foreign key.

Regards,
Andrew

чт, 16 апр. 2020 г. в 11:26, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Hi, 

but only one. This DB has 11 :) I thought Jam demo is using chinook as it is. Is there a reason why 10 FK's are dropped?

**Comment by rrad0812** [comment]
Hi,
Just to joke:
Number 10 is the basis of human life.

Radosav

**Comment by jam-py** [comment]
The database of demo app  is quite old.
It can be that there were no foriegn indexes then.
You can add then if you need.

пт, 17 апр. 2020 г. в 10:30, rrad0812 <notifications@github.com>:

**Comment by platipusica** [comment]
Adding more 
[Inventory.pdf](https://github.com/jam-py/jam-py/files/4823201/Inventory.pdf)

**Comment by platipusica** [comment]
Radosav, 

you were right, ESF database migration toolkit is 100% accurate. So, converted all this MS Access databases and created a DB schema diagram with above tool:

MS Access Inventory App:

![Inventory](https://user-images.githubusercontent.com/9026100/85528820-fc93e580-b63e-11ea-8422-ea7661cf8d20.png)

MS Access Real Estate App:

![RealEstate](https://user-images.githubusercontent.com/9026100/85528907-16352d00-b63f-11ea-8803-a205cf70dd1a.png)

MS Access Lending Library App:

![LendingLibrary](https://user-images.githubusercontent.com/9026100/85528953-26e5a300-b63f-11ea-8a2d-08d38dc103af.png)

And finally, Northwind App as PDF:

[Northwind.pdf](https://github.com/jam-py/jam-py/files/4824379/Northwind.pdf)

It won't take long to recreate with Jam :)

**Comment by platipusica** [comment]
[Inventory.pdf](https://github.com/jam-py/jam-py/files/4824386/Inventory.pdf)
[RealEstate.pdf](https://github.com/jam-py/jam-py/files/4824387/RealEstate.pdf)
[LendingLibrary.pdf](https://github.com/jam-py/jam-py/files/4824388/LendingLibrary.pdf)


If anyone interested...

**Comment by platipusica** [comment]
There we go, Inventory to make it prettier :) Took me 1hr from conversion to this:

![Screenshot from 2020-06-25 16-14-46](https://user-images.githubusercontent.com/9026100/85682656-18f75700-b6ff-11ea-82f0-813f3335411a.png)

**Comment by platipusica** [comment]
![](https://user-images.githubusercontent.com/9026100/85682656-18f75700-b6ff-11ea-82f0-813f3335411a.png)

**Comment by platipusica** [comment]
Here are the above databases in sqlite3 format.

[Inventory.sqlite.zip](https://github.com/jam-py/jam-py/files/6187433/Inventory.sqlite.zip)
[RealEstate.sqlite.zip](https://github.com/jam-py/jam-py/files/6187435/RealEstate.sqlite.zip)
[LendingLibrary.sqlite.zip](https://github.com/jam-py/jam-py/files/6187436/LendingLibrary.sqlite.zip)
