### ISSUE TITLE
CSV - Convert Date

### ISSUE THREAD

**Issue by fcotait** [jam-py/jam-py#154]
When use the CSV export (sample code), if there is a DATE field that erros occurs:

```
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jam/dataset.py", line 373, in lookup_text
    result = self.lookup_value
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jam/dataset.py", line 352, in lookup_value
value = self.convert_date(value)
AttributeError: 'DBField' object has no attribute 'convert_date'

```

In the CSV code, I'm using field.display_text, because field.text have the key value

Jam.py version 5.4.93

**Comment by fcotait** [comment]
Important: I'm using field.display_text, because field.text have the key value

**Comment by jam-py** [comment]
Hello,

Thank you for the message!
I fixed the bug, please upgrade the package

Regards,
Andrew Yushev


чт, 9 апр. 2020 г. в 19:41, fcotait <notifications@github.com>:

**Comment by fcotait** [comment]
Thanks and congratulations for this project.

Filipe

**Comment by jam-py** [comment]
Thank you!

Andrew

пн, 13 апр. 2020 г. в 21:22, fcotait <notifications@github.com>:
