### ISSUE TITLE
The table Import and Name/DB Field Name issue 

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#156]
Hi, 

when doing the table Import, it is not great to have Jam renaming DB Field Name as we type input in the Name b/c it's invalid name for Jam.

For example, the DB has "zip/postal code" as TEXT, but Jam Name needs to be changed, which immediately changes the DB Filed Name to "ZIP_POSTAL_CODE" and that is NOT the DB filed, and needs to be changed immediately.
Imagine huge tables and changing this manually all the time.

The solution for Import would be to leave the DB Filed Name as is b/c if we change it, the App wont work.

Thoughts?

**Comment by platipusica** [comment]
[Inventory.sqlite3.zip](https://github.com/jam-py/jam-py/files/4491495/Inventory.sqlite3.zip)

**Comment by platipusica** [comment]
On above DB, I can't Import "Transaction Types" table:

```
Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/wsgi.py", line 599, in on_api
    data = self.get_response(item, method, params)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/wsgi.py", line 626, in get_response
    return self.server_func(item, params[0], params[1])
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/wsgi.py", line 637, in server_func
    result = func(obj, *params)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/admin/builder.py", line 952, in server_import_table
    result = task.task_db_module.get_table_info(connection, table_name, task.task_db_database)
  File "/home/dbabic/Downloads/SAML/saml/lib/python3.6/site-packages/jam/db/sqlite.py", line 165, in get_table_info
    cursor.execute('PRAGMA table_info(%s)' % table_name)
sqlite3.OperationalError: near "Transaction": syntax error
```

Which is a separate issue :)

**Comment by rrad0812** [comment]
Hi,
I think that '/' not a regular sign for identificators in the Python.
As for second, you can see for SQLite Pragma, maybe help.

Radosav

**Comment by platipusica** [comment]
Rad, 
which PRAGMA ;)

CREATE TABLE `Transaction Types` (`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
`Description` VARCHAR(255) DEFAULT '',
`Add/Remove` VARCHAR(255) DEFAULT '');

**Comment by rrad0812** [comment]
SQLite PRAGMA directive!

Poslato iz programa Pošta za Windows 10

Od: platipusica
Poslato: petak, 17. april 2020. 09:49
Za: jam-py/jam-py
Cc: rrad0812; Comment
Tema: Re: [jam-py/jam-py] The table Import and Name/DB Field Name issue(#156)

Rad,
which PRAGMA ;)
CREATE TABLE Transaction Types (ID INTEGER PRIMARY KEY AUTOINCREMENT,
Description VARCHAR(255) DEFAULT '',
Add/Remove VARCHAR(255) DEFAULT '');

**Comment by rrad0812** [comment]
And maybe  ’Transaction Types ’!

Poslato iz programa Pošta za Windows 10

Od: platipusica
Poslato: petak, 17. april 2020. 09:49
Za: jam-py/jam-py
Cc: rrad0812; Comment
Tema: Re: [jam-py/jam-py] The table Import and Name/DB Field Name issue(#156)

Rad,
which PRAGMA ;)
CREATE TABLE Transaction Types (ID INTEGER PRIMARY KEY AUTOINCREMENT,
Description VARCHAR(255) DEFAULT '',
Add/Remove VARCHAR(255) DEFAULT '');

**Comment by jam-py** [comment]
Maybe it is because SQLite do not have VARCHAR type?

пт, 17 апр. 2020 г. в 10:51, rrad0812 <notifications@github.com>:

**Comment by platipusica** [comment]
CREATE TABLE "A B" (ID INTEGER PRIMARY KEY AUTOINCREMENT,
Description VARCHAR(255) DEFAULT '',
"Add/Remove" VARCHAR(255) DEFAULT '');

Try to Import "A B"

Guys....

**Comment by platipusica** [comment]
No worries, not important.

**Comment by platipusica** [comment]
Reopening this.

The sqlite3 is supporting space in the table name, and "/" in column name, hence Jam should be able to support it.

It is only a matter of time when someone will report the same.

Cheers

**Comment by jam-py** [comment]
I'll take it into account.

ср, 3 июн. 2020 г. в 09:23, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
No worries.

What is interesting, we can create a table name with space in it from Jam.
