### ISSUE TITLE
Text field editor

### ISSUE THREAD

**Issue by fabiograz** [jam-py/jam-py#157]
Hi,
I've a text field in a table with more than 100 char and I want to show its content in extend mode (more line). I would like, also, edit it in advanced editor like TinyMCE. 
How can I change the normal behavior of jam.py for the text field?

I think that it may be usefull to have a flag (or more option like, number of line, advanced editor, etc.) in the field definition (or in form parameters) to set an advanced text editor for the text type.

Thanks,
Fabio.

**Comment by fabiograz** [comment]
I found this issue https://github.com/jam-py/jam-py/issues/95#issuecomment-461451848 to set a larger input field. 
I don't know how to use ad advanced editor for the input.

Thanks.

**Comment by jam-py** [comment]
Please, read this:
https://mail.google.com/mail/u/0/#search/TinyMCE/FMfcgxwHMPhrrpklCsZtnrvvFmhWbGSC

пн, 4 мая 2020 г. в 18:53, fabiograz <notifications@github.com>:

**Comment by fabiograz** [comment]
Sorry,
but I can't open link.

**Comment by jam-py** [comment]
I am sorry I added a wrong link.
The correct link is
https://groups.google.com/forum/#!searchin/jam-py/tinymce%7Csort:date/jam-py/vCqgRFuuy-s/Hzz6ncloAwAJ

чт, 7 мая 2020 г. в 10:47, fabiograz <notifications@github.com>:

**Comment by fabiograz** [comment]
Ok, thanks.
I'll try.
