### ISSUE TITLE
how to debug /ext

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#159]
Hi there, 

any ideas how to debug /ext at all? 

The /ext is not covered buy much documentation, so struggling to understand what to do.

Thanks

**Comment by jam-py** [comment]
Hi,

Try to use print function.
For example

def on_ext_request(task, request, params):
   print(request, params)

Regards


вт, 12 мая 2020 г. в 07:10, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
HI Andrey, 

in https://jam-py.com/docs/refs/server/task/on_ext_request.html

can you please demonstrate something like:

    if reqs[2] == 'A':
        return ...
    elif reqs[2] == 'B':
.
.
I'm strugling to understand why the web page is only doing A and not B...
Thanks

**Comment by jam-py** [comment]
because reqs[2] == 'A'

чт, 21 мая 2020 г. в 10:03, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Ok, and how to get to B? :)

**Comment by jam-py** [comment]
You must pass
$.ajax({
   url: "ext/B",

чт, 21 мая 2020 г. в 10:37, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Correct.

it's not getting there, see:

```
127.0.0.1 - - [21/May/2020 15:47:18] "POST /ext/a HTTP/1.0" 200 -
/ext/b None
Traceback (most recent call last):
  File "/usr/local/venvs/py36/lib64/python3.6/site-packages/jam/wsgi.py", line 207, in __call__
    endpoint, values = adapter.match()
  File "/usr/local/venvs/py36/lib/python3.6/site-packages/jam/third_party/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:
.
.
127.0.0.1 - - [21/May/2020 15:48:01] "POST /ext/b HTTP/1.0" 200 -
```

So if first page is POSTing to A, why is it saying /ext/b None and doing a Traceback is unknown...

So it's POST to A, get result and process, POST back to B. No success...

**Comment by jam-py** [comment]
It's strange, if /ext/a is working and /ext/b doesn't.
Send me the project I'll check

чт, 21 мая 2020 г. в 10:59, platipusica <notifications@github.com>:
