### ISSUE TITLE
'ascii' codec can't encode with Oracle (UTF8 problem)

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#16]
Hi 

after successful import to Oracle I am using ISO88592 language and UTF8 and got similar error with both when creating new records:

'ascii' codec can't encode character u'\u0160' in position 0: ordinal not in range(128)

My Oracle language settings:
NLS_CHARACTERSET AL32UTF8
NLS_LANGUAGE AMERICAN

Linux server using:
 env |grep LAN
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en

The data is looking ok in the database when viewing with SqlDeveloper (imported csv's as task.copy_database doesn't work). But the appl is not displaying it right.

The Sqlplus is not showing right as well.

The solution is to set the Oracle NLS variable on Linux before running jam server:

export NLS_LANG=AMERICAN_AMERICA.UTF8

Sqlplus is showing now data correctly, for example:
select lastname from DEMO_CUSTOMERS;
## LASTNAME

Gonçalves
Köhler
Tremblay
Hansen
Wichterlová
Holý

Everything else seems to be working really well Andrew!  

Hope this helps!

D.
[orig_1.3.45_4.0.24_2016-10-13_15-33-45.zip](https://github.com/jam-py/jam-py/files/526488/orig_1.3.45_4.0.24_2016-10-13_15-33-45.zip)

**Comment by jam-py** [comment]
Hi,

I am afraid I can not repeate your settings. Can you execute the same
request
select lastname from DEMO_CUSTOMERS
using xc_Oracle.

Andrew

2016-10-13 11:23 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
It is all good, this is just a reminder for me for the future!

Thank you!

**Comment by jam-py** [comment]
Hi, Dean.
Could you help me? I reworked documentation. Can you check it out? I'm most interested in
Programming Section - http://jam-py.com/docs/programming/index.html. I believe that it will not take much time.
All comments and suggestions are welcome.
It is very important for me.
All the best
Andrew

**Comment by dbabicwa** [comment]
Ok
no probs, will have a look. You want me to look at understanding the documentation or...?

**Comment by jam-py** [comment]
Yes, understanding. What is unclear.

**Comment by dbabicwa** [comment]
Client side programming looks good, a few typos:
http://jam-py.com/docs/programming/interface/forms.html
respectfully – respectively 

http://jam-py.com/docs/programming/interface/form_events.html
The developed- The developer
But it as well, is called -  But it as well called 

http://jam-py.com/docs/programming/interface/form_options.html
will be 800 px. – is it 700 as per example?

http://jam-py.com/docs/programming/interface/data_controls.html
wich  - which
scesifying  - satisfying
usially  - usually   

Will check the rest next week.

**Comment by jam-py** [comment]
Thank you. 
I corrected these errors.

**Comment by dbabicwa** [comment]
I've checked the rest, not many typos, all in all looks good.
http://jam-py.com/docs/programming/data/dataset.html

cient- client
the changes are saves - the changes are saved

http://jam-py.com/docs/programming/data/navigating_datasets.html
If the method returns true
If the method returns true - Is it false?

http://jam-py.com/docs/programming/data/fields.html

float и currency

Now need to build an app, not there just yet :) Cheers!

**Comment by jam-py** [comment]
Thank you.


2016-11-07 4:32 GMT+03:00 dbabicwa <notifications@github.com>:
