### ISSUE TITLE
Paginate set to True

### ISSUE THREAD

**Issue by fcotait** [jam-py/jam-py#160]
Hi, 

I'm using the create_table method to create a table from dataset

When I set the paginate attribute to true, a page/data control is created, but if I click to move the records / page nothing happens. if I click in a column to sort all records disappear.

In my dataset to test there is about 70 records.

I'm doing same thing wrong in the code or ir as issue? When I set the paginate to false, works well, but of course, show all records without a page/data control

Jam.Py version 5.4.93
Python 3.8.2
Firefox 76.0.1 (64-bits) or Chrome 83.0.4103.61

Thanks a lot

My code is (sample)
 
```
var rSales = item.task.reportSales.copy({handlers: false});

rSales.open({open_empty: true}); 
rSales.paginate = true;

while (!sales.eof()) {
	rSales.append();
	rSales.id.value .value   = sales.id.value;
	rSales.client.value      = sales.client.value;
	rSales.quarter.value     = sales.quarter.value;
	rSales.sales_value.value = sales.sales_value.value;
	rSales.post();
        sales.next();
}

rSales.create_table(item.view_form.find('#dashboards-details-table'), {
    fields: ['id', 'client', 'quarter', 'sales_value'], 
    sort_fields:  ['id', 'client', 'quarter', 'sales_value'],
    title_line_count: 2,
    striped   : true,
    show_hints: true
    
});

```

**Comment by jam-py** [comment]
Hello,

When paginate is set and user change the page
the request is send to the server to get the data from database table for
this page.
As you fill records dynamically there is no sense to set the paginate
attribute to true.

Regards,
Andrew Yushev

сб, 30 мая 2020 г. в 02:28, fcotait <notifications@github.com>:

**Comment by jam-py** [comment]
Please note that tables in Jam.py have virtual scrolling.

сб, 30 мая 2020 г. в 11:24, Andrew Yushev <yushevaa@gmail.com>:

**Comment by fcotait** [comment]
I understood! Thanks a lot
