### ISSUE TITLE
A Form From Two Tables

### ISSUE THREAD

**Issue by lrpatterson** [jam-py/jam-py#162]
Hey,

I am work with jam-py to create a case audit system.  I am trying to maintain a somewhat normalized DB.  What tables I am currently working with is a case_table (contains basic info about the case including a case ID), audit_questions (These will not be edited by end-users) and the values_assigned to each question.  So what I hope to end up with is a form that allows for users to enter case data like case number then they could fill a value (1, 2, or 3) next to a question (ex: was the case approved).  How can I link three tables into a form?  I added an example of what the form is suppose to look like.  Tried details but can't get a similar UX.
![image](https://user-images.githubusercontent.com/41905851/84334208-d3b02280-ab5f-11ea-874e-20e2033970b4.png)

**Comment by platipusica** [comment]
HI there, 

you might look at this as an example:
https://sambashares.herokuapp.com/

This are 3 tables with details.

Cheers

**Comment by jam-py** [comment]
Hello

I created a project to demonstrate how to do it

It has 'cases' journal, 'questions' catalog and 'answers' detail.
The 'answers' detail is linked to 'cases'.

in the the 'answers' detail of 'cases' I written the following code
('cases.answers.js' client module)

function on_after_open(item) {
    if (item.owner.is_new()) {
        let quest = task.questions.copy();
        quest.open();
        quest.each(function(q) {
            item.append();
            item.quest.value = q.id.value;
            item.quest.lookup_value = q.quest.value;
            item.post();
        });
    }
}

function on_view_form_created(item) {
    item.view_form.find('.form-footer, .view-detail').hide();
}

function on_view_form_keyup(item, event) {
    return true;
}

When a new 'cases' record is added by clicking the 'New' button,
the 'answers' detail is opened so users can add records to it.
The on_after_open event handler checks if master record is added and
then adds records, setting the 'quest' field from the 'questions' catalog.
To hide 'Delete', 'New', 'Edit' buttons I hidden the form footer from view
form.
And to prevent adding and deleting records I wrote the on_view_form_keyup
event handler.

Alose in the 'cases'  'answers' detail view form I unchecked 'Dblclick
edit' attribute,
added 'answer' field to 'Edit fields' so the answers can be edited in line.

Here is a link to the project
https://drive.google.com/file/d/10N2Cr8idqZAs5LfohRvnw2qWXXKIHyyj/view?usp=sharing

Regards,
Andrew Yushev




чт, 11 июн. 2020 г. в 04:57, platipusica <notifications@github.com>:

**Comment by lrpatterson** [comment]
You are awesome and I love Jam.py! Thank you for your help and for writing this library!

**Comment by platipusica** [comment]
If may I ask, where did you find about Jam.py? 

Cheers

**Comment by lrpatterson** [comment]
@platipusica Sorry for my late reply.  I found it here: https://medium.com/@ljudevitperi/the-ocean-of-web-applications-and-tropical-island-of-jam-py-d86075232b1c.

**Comment by lrpatterson** [comment]
I am getting an `Uncaught TypeError: Cannot set property 'value' of undefined` when I try to use the js code above.  What would cause this?

![image](https://user-images.githubusercontent.com/41905851/90080740-693f6e00-dcd9-11ea-80ce-9a00facec515.png)

![image](https://user-images.githubusercontent.com/41905851/90080755-75c3c680-dcd9-11ea-9c1b-e1b48126ffab.png)


```function on_after_open(item) {
    if (item.owner.is_new()) {
        let quest = task.dsscase_qr_questions.copy();
        quest.open();
        quest.each(function(q) {
            item.append();
            item.quest.value = q.id.value;
            item.quest.lookup_value = q.quest.value;
            item.post();
        });
    }
}

function on_view_form_created(item) {
    item.view_form.find('.form-footer, .view-detail').hide();
}

function on_view_form_keyup(item, event) {
    return true;
}```

**Comment by jam-py** [comment]
Hello, Landon

I wrote the following code in the invoices.invoice_table.js module

function on_after_open(item) {
    if (item.owner.is_new()) {
        let table = task.invoice_table.copy();
        table.open();
        table.each(function(t) {
            item.append();
            item.track.value = t.track.value;
            item.track.lookup_value = t.track.lookup_value;
            item.quantity.value = 1;
            item.unitprice.value = 0.99;
            item.post();
        });
    }
}

and it works

[image: landon.png]

It seems that there is some problem with the quest field in the line

item.quest.value = q.id.value;

Please, try to set the breakpoint there.

Regards,
Andrew Yushev

чт, 13 авг. 2020 г. в 03:25, Landon Patterson <notifications@github.com>:
