### ISSUE TITLE
Multiple documents?

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#163]
Hi, 

would it be possible to demonstrate how to have a number of documents attached to a record?

Cheers

**Comment by jam-py** [comment]
Hi,

You can create a detail to an item to store documents attached to its record

Regards

чт, 11 июн. 2020 г. в 09:39, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Thx, 
I managed to create a project with this scenario. Would be good to document and maybe even attach as a project in documentation.
I do have a suggestion, it would be great to enable somehow multiple files selection for upload.

Also, you can see this here, after the file (not the record), is deleted, the record actually stays there, even tho file does not.
It is the same after file is selected for upload, but immediately cleared, the record will be created as empty.

Cheers 
![Jam_documents](https://user-images.githubusercontent.com/9026100/84468493-8c39ab80-acb1-11ea-9a15-5bb558eb5b0b.png)
[files_1.0.0_5.4.89_2020-06-12_13-35-25.zip](https://github.com/jam-py/jam-py/files/4768941/files_1.0.0_5.4.89_2020-06-12_13-35-25.zip)

**Comment by jam-py** [comment]
Hello,

I'll think about how to upload selected files.
As for deleted files, you must not deleted them r write the code that will
check for it and delete records.

Regards


пт, 12 июн. 2020 г. в 08:36, platipusica <notifications@github.com>:
