### ISSUE TITLE
Overwrite detail query 

### ISSUE THREAD

**Issue by xelomac** [jam-py/jam-py#165]
Hello,
I try to  overwrite the query that selects the records for a detail view form with no success. Is that possible and how? Normally the records are selected by their master_rec_id value. I want to select the detail records by a different integer field.

**Comment by jam-py** [comment]
Hello, for the standard detail you can write the on_before_open event
handler in the detail client module,
the resulting dataset will be filtered by master_id and master_rec_id
and quantity will be greater than 1

function on_before_open(item, params) {
    item.set_where({quantity__gt: 1});
}

вс, 5 июл. 2020 г. в 11:26, xelomac <notifications@github.com>:

**Comment by xelomac** [comment]
Thanks for the quick reply. What I am looking for is a way to avoid the selection of master_id and master_rec_id. I want to attach the same detail to two different master items. Depending on which master item opens the detail view I want to define different selection criteria. In master item A I want to select the detail records where detail field id_a matches with the id of the active item A record. In master item B I want to select the detail records where detail field id_b matches with the id of the active item B record. Is this somehow possible?

**Comment by jam-py** [comment]
It is possible, but standard details are not designed for it.
You have to create some item with fields id_a and id_b and link them to
masters.

вс, 5 июл. 2020 г. в 14:17, xelomac <notifications@github.com>:

**Comment by xelomac** [comment]
Ok - that's what I did before - but then I have to build all the delete-, edit- and new buttons and so every time. I hoped there was a more convenient and less repetitive way of solving this...

**Comment by platipusica** [comment]
Templates?

The buttons in early Jam stages were defined in index.html file...

Maybe Andrew can expand on this a bit more though.

**Comment by jam-py** [comment]
You can link one detail to two or more different items.
Details have master_id and master_rec_id fields.
master_id is the ID
https://jam-py.com/docs/refs/client/abstr_item/at_id.html
of the master and  master_rec_id is the record id of the master.
https://jam-py.com/docs/programming/data/details.html
so you don't have to create A_id and B_id and care about storing their
values.
Of course if each detail record has only one master record.

вс, 5 июл. 2020 г. в 15:41, platipusica <notifications@github.com>:
