### ISSUE TITLE
Generating Docs with Spynx

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#166]
HI Andrew

low on priority, I was wondering if 

/jam/docs $ sphinx-build -b singlehtml . all

can reference anything in "Table of Contents" on the right side of created file? We discussed about this on Mon, Sep 18, 2017 :)

Also, search option is missing completely when created.

Cheers

**Comment by platipusica** [comment]
See:

http://fnch.users.sourceforge.net/sphinxindexinsinglehtml.html

**Comment by platipusica** [comment]
Was reading somewhere that pip install sphinx==1.3.6

and it does work but only till "Creating a project" on Table of Contents. 

Do I need to insert:
.. globalindex::
   :maxdepth: 3

anywhere to get this to work?

**Comment by jam-py** [comment]
Hi, Dean

I didn't get into Sphinx nuances.
I uploaded docs to  Read the Docs site and there it can be downloaded in
different formats.
https://readthedocs.org/projects/jam-py/downloads/

Maybe this will help.

Regards,
Andrew



пн, 6 июл. 2020 г. в 11:34, platipusica <notifications@github.com>:
