### ISSUE TITLE
jam-project.py fails on python 3.8.4

### ISSUE THREAD

**Issue by ruok191** [jam-py/jam-py#167]
![image](https://user-images.githubusercontent.com/16516106/87389894-e0e28600-c5d1-11ea-9ff7-af36cab8aec6.png)

Hi, My Linux is  centos 7 without gui.

**Comment by platipusica** [comment]
Hi, can you post python --version?

Thx

**Comment by platipusica** [comment]
Ah, preferable installation is with pip tho in virtual environment. 

Even for production.

**Comment by ruok191** [comment]
my python is 3.8.4  (latest version)
my   step  of  intallation  
1.  yum install gcc openssl-devel bzip2-devel libffi-devel
2. wget https://www.python.org/ftp/python/3.8.4/Python-3.8.4.tar.xz
3.  tar xvf Python-3.8.4.tar.xz
4. cd  Python-3.8.4
5. ./configure --enable-optimizations
6. make altinstall
7.  wget https://bootstrap.pypa.io/get-pip.py
8. curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
9. cd Python-3.8.4
10.  python setup.py install
  happend  error

**Comment by platipusica** [comment]
Sure, thanks.

just try "pip install jam.py"

Will take some time to fix 3.8.4 issue...

**Comment by jam-py** [comment]
Hello,

try to run

python3.8 -m pip install jam.py


вт, 14 июл. 2020 г. в 11:11, platipusica <notifications@github.com>:

**Comment by ruok191** [comment]
thx for your  assistance.

just try "pip install jam.py"
Will take some time to fix 3.8.4 issue...
-------------------------------------------------------------------------------------------
Due to my misunderstanding ,  the correct step is 
0. cd /tmp
1. yum install gcc openssl-devel bzip2-devel libffi-devel
2. wget https://www.python.org/ftp/python/3.8.4/Python-3.8.4.tar.xz
3. tar xvf Python-3.8.4.tar.xz
4. cd Python-3.8.4
5.  ./configure --enable-optimizations
. make altinstall
7. wget https://bootstrap.pypa.io/get-pip.py //(download files get-pip.py)
8. python get-pip.py
9. ----->download files   jam.py-5.4.96.tar.gz
    wget https://jam-py.com/download/jam.py-5.4.96.tar.gz
10.  pip install jam.py-5.4.96.tar.gz
11. --------> create project for test. Create a new directory.
     --------->Go into the directory and run from command line:
      mkdir  testjam
12. cd testjam
13. jam-project.py
14. ----> To start Jam.py web server run server.py scrip
      ./server.py
15. ------> goto browser  
      http://192.168.1.10:8080/builder.html

![image](https://user-images.githubusercontent.com/16516106/87497974-f498f580-c680-11ea-9c3d-56ea6cc3ac3e.png)


God bless , wish all of everyone has Happiess and Healthy.

**Comment by platipusica** [comment]
cool, thanks for reporting back!

You too, thx
