### ISSUE TITLE
I have some problem 

### ISSUE THREAD

**Issue by sanya-than** [jam-py/jam-py#168]
![image](https://user-images.githubusercontent.com/68261351/87527739-bd453b80-c6b6-11ea-902e-219c1f8d2167.png)

**Comment by platipusica** [comment]
So, you need to install it:

https://jam-py.com/docs/intro/new_project.html

It says:

Please note the following requirements:

to use FireBird database, the python fdb library must be installed
PostgreSQL requires psycopg2 library
MySQL requires MySQLdb library
Oracle requires cx_Oracle library
MSSQL requires pymssql library
to generate reports LibreOffice must be installed

A lot of effort was put in documentation Sanja...

**Comment by sanya-than** [comment]
I have more question to ask you for the capabilities of jam-py to support front-end web application.

as follow


[cid:015e5d44-b30d-4928-8820-1a89471d8ad4]


[cid:c0d86f9f-7959-45c6-834f-87826f30a8d5]

each screen can be link to the others, and need to have API (Application Program Interface ) to databas via web service in such as GET, PUT, POST , DELETE

thanks for your assistance

Best Regards,

Sanya T

________________________________

**Comment by platipusica** [comment]
Pics are missing...

Please read all documentation or ask specific questions. 

Cheers

**Comment by sanya-than** [comment]
Dear Sirs,

I would like to ask you that JAM-PY supports for screen designer in the application(including MENU , microflow etc.)  or not ?
I have read all documents but I cannot find it.

Thanks & Best Regards,

Sanya T.

________________________________

**Comment by ljudva** [comment]
I would suggest to have a look at the movies. Menus are created automatically, or by hand, it's not hard. I have no idea what microflow is, I'm afraid.

Plenty of Demo apps, almost all created automatically with limited or no programming. This is SPA framework. 


Thanks
