### ISSUE TITLE
View form of linked table does not update after calling append_record() or delete_record()

### ISSUE THREAD

**Issue by xelomac** [jam-py/jam-py#169]
Hi folks,

I linked two tables.
I added a "new" and a "delete" button for the linked table in the modal edit form of the master item and defined the following functions for the buttons:
btn_delete.click(function() {
        item.my_linked_table.delete_record();
    });
    btn_new.click(function() {
        item.my_linked_table.append_record();
    });
When I click my new button inside the edit modal of the master item a second modal edit form appears automatically like it does when dealing with normal details. Perfect. I can fill out the form and click ok. But the result (the appended record) is not shown until I reload the web browser.

**Comment by platipusica** [comment]
Hi,

I think you might be missing refresh after append.
Search for it in Demo, it is somewhere if remember well :)

D.

**Comment by jam-py** [comment]
Hello,

Try to define the on_after_apply event handler of the item.my_linked_table
in
the on_view_form_created of the item

function on_view_form_created(item) {
    ....
    item.my_linked_table.on_after_apply = function(lt) {
        on_after_scroll(item)
    }
}

Regards,
Andrew Yushev


сб, 18 июл. 2020 г. в 16:54, platipusica <notifications@github.com>:

**Comment by xelomac** [comment]
Thanks but it did not work. Perhaps I should mention that a manual scroll (changing the master record via mouse click back and forth) which triggers  the on_after_scroll function does also not display recently added records in my_linked_table view. Any other idea?

**Comment by jam-py** [comment]
Perhaps you must set the master field value.
You can do it in on_after_append or on_before_post event handlers,
the same as with on_after_apply

function on_view_form_created(item) {
    ....
    item.my_linked_table.on_after_apply = function(lt) {
        on_after_scroll(item)
    }

    item.my_linked_table.on_before_post = function(lt) {
        it.master_field.value = item.id.value
    }
}

вс, 19 июл. 2020 г. в 09:39, xelomac <notifications@github.com>:
