### ISSUE TITLE
Catalog table record change to update all records in detail table.

### ISSUE THREAD

**Issue by noeldum** [jam-py/jam-py#171]
Using the demo as example here.

Say I modify the unitprice of a track in the catalog tracks table. Let's assume I now want to update all related unitprice also in the details incoice_table table.

Basically all invoices to change the unit prices if they have been changed in the catalog (I know this would not make sense in the specific example of the demo, my case is obviously different and need this).

How should this be done?

I was looking at on_field_changed but don't know how to code this in here. Could also maybe work with on_before_open? i.e. updating the records before they are view would work for me.

**Comment by platipusica** [comment]
Hi there,

And welcome.

I think the server side is for that. Look at the Demo, not quite sure where tho.

Chee

**Comment by jam-py** [comment]
Hello,

One way to do it is to write the on_apply event handler in the tracks
server module:
https://jam-py.com/docs/refs/server/item/on_apply.html

def on_apply(item, delta, params, connection):
for d in delta:
   if d.rec_modified() and d.unitprice.value != d.unitprice.old_value:
       invoice_table = item.task.invoice_table.copy()
       invoice_table.set_where(track=d.id.value)
       invoice_table.open()
       for t in invoice_table:
           t.edit()
           t.unitprice.value = d.unitprice.value
           t.post()
       invoice_table.apply(connection=connection)

Regards,
Andrew Yushev

сб, 25 июл. 2020 г. в 15:46, platipusica <notifications@github.com>:

**Comment by noeldum** [comment]
Thanks a lot. That works well.

**Comment by platipusica** [comment]
HI Andrew,

I am getting Error on any Tracks actions, nothing in the log.

![Screenshot from 2020-07-28 12-59-55](https://user-images.githubusercontent.com/9026100/88621193-64bc6800-d0d2-11ea-8bfc-1ed42569d611.png)


Tracks Server:
```

def set_media_type(item, media_type, selections):
    copy = item.copy()
    copy.set_where(id__in=selections)
    copy.open(fields=['id', 'media_type'])
    for c in copy:
        c.edit()
        c.media_type.value = media_type
        c.post()
    c.apply()
    return True
    
def on_apply(item, delta, params, connection):
    for d in delta:
       if d.rec_modified() and d.unitprice.value != d.unitprice.old_value:
           invoice_table = item.task.invoice_table.copy()
           invoice_table.set_where(track=d.id.value)
           invoice_table.open()
           for t in invoice_table:
               t.edit()
               t.unitprice.value = d.unitprice.value
               t.post()
           invoice_table.apply(connection=connection)
```

Python 3.6.8

Thoughts?

**Comment by platipusica** [comment]
Hi, 

I take this back, getting Error anyway, even when deleted above.

Ignore pls.

**Comment by jam-py** [comment]
Hi,

The problem is that in the set_media_type function the open method is only
for id and media_type fields

copy.open(fields=['id', 'media_type'])

and in the on_apply method the unitprice field is used that do not exists
id the delta dataset
To correct this is to change

copy.open(fields=['id', 'media_type', 'unitprice']) or
copy.open()

or to change

if d.rec_modified() and d.unitprice.value != d.unitprice.old_value:

to

if d.field_by_name('unitprice') and d.rec_modified() and d.unitprice.value
!= d.unitprice.old_value:

Regards,

Andrew Yushev





ср, 29 июл. 2020 г. в 09:02, platipusica <notifications@github.com>:
