### ISSUE TITLE
Builder sorting 

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#174]
Hi, 

it would be very beneficial if Builder has sorting. I have about 100 tables in one item and it's difficult to find them by ID.

Cheers

**Comment by jam-py** [comment]
Hello ,

Please use search Ctrl-F
[image: search.png]

Regards,
Andrew Yushev

чт, 30 июл. 2020 г. в 08:48, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Cool, 

thanks!
