### ISSUE TITLE
Deleted flag on Item Group

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#175]
Hi, 

I can create Primary key field and set it.

But setting Deleted flag does not work. Even on Details Group!

Cheers
D.

**Comment by platipusica** [comment]
Hmm,
this is a bit weird, in the New Group, if I create a new Table, with empty fields, Jam is creating:
CREATE TABLE IF NOT EXISTS "**DEMO_GADGFDHADFHFD**"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER);

But on the Builder, there is no Deleted Flag set. And then when the Table is open, Jam is showing Deleted filed on View, even tho it should be not there!

Bug?

Hence, two different things, one Item Group, and second Table Deleted flag. 

![Screenshot from 2020-07-30 14-32-32](https://user-images.githubusercontent.com/9026100/88888820-9881c400-d271-11ea-9af6-2f9084ac22dd.png)

![Screenshot from 2020-07-30 14-31-57](https://user-images.githubusercontent.com/9026100/88888833-9ddf0e80-d271-11ea-81f5-f5101897d8d0.png)

**Comment by jam-py** [comment]
Hello,

These fields should appear if you created an item in the group that
has these fields. If not so there is a bug that I can not reproduce.

чт, 30 июл. 2020 г. в 09:34, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
No worries, 

I recorded 2 videos. The tables created are:
```
CREATE TABLE IF NOT EXISTS "T_TEST"
(
"T1" INTEGER PRIMARY KEY,
"DEL" INTEGER);
CREATE TABLE IF NOT EXISTS "T_T2"
(
"ID" INTEGER PRIMARY KEY,
"DEL" INTEGER);
```

T2 is created in test2 Item Group. As you see, it inherited "del" but can't set it...
