### ISSUE TITLE
Working on SAML auth

### ISSUE THREAD

**Issue by lrpatterson** [jam-py/jam-py#177]
Working to provide SAML auth to my app.  Seems simple enough as I have a working example in bottle, where the user is presented with a "login here" type of link. If they click the link they are re-directed through the SAML endpoint and auth data is returned.

While this works in other frameworks I cannot seem to get anything like this to work in jam-py.  I have tried to use a combination of `on-open`, werkzeug `request.form`/`redirect` just to make the SAML request happen automatically so that a user can auth through Idaptive (our SAML provider) instead of the jam-py auth system.  Does anyone have any insight into a possible way to complete a SAML auth request?

**Comment by jam-py** [comment]
Hi, Landon

I work on the 6 version and prepare it for release.
I changed the way requests are processed in it.
It can be used for SAML authentication then.

Regards,
Andrew Yushev



пн, 10 авг. 2020 г. в 21:07, Landon Patterson <notifications@github.com>:

**Comment by lrpatterson** [comment]
Okay, appreciate you including this functionality in the next version.  Is there any timeline associated with version 6?  If not I understand.

**Comment by jam-py** [comment]
I plan to release beta version until the end of the month

вт, 11 авг. 2020 г. в 16:07, Landon Patterson <notifications@github.com>:

**Comment by lrpatterson** [comment]
Awesome! Thanks!

**Comment by jam-py** [comment]
Hi, Landon

In the new version it will be possible to use SAML authentication.
But don't have access to SAML so it will be hard for me to write the code
that is needed to support it.
Can you help me with it then?

Regards,
Andrew Yushev


ср, 12 авг. 2020 г. в 15:03, Landon Patterson <notifications@github.com>:

**Comment by jam-py** [comment]
Thank you Landon.

пт, 30 окт. 2020 г. в 20:38, Landon Patterson <notifications@github.com>:

**Comment by matejak** [comment]
Hello, I would also be interested in support of SAML, and I can help with testing, and perhaps also with development to some degree.

**Comment by platipusica** [comment]
Hi Matej,
saml will be fully supported on new major release, you can try how it works from here:

https://groups.google.com/g/jam-py/c/1qciSkILloU/m/JfRncz89BQAJ

If you are keen to develop your own solution, use develop branch. 

Cheers
