### ISSUE TITLE
Report generation on IIS doesn't work

### ISSUE THREAD

**Issue by jgwacyk** [jam-py/jam-py#178]
Hello,

I deployed a jam.py application on windows server with IIS and FastCGI. The report generation doesn't work for the xls and pdf format.
The problem come from the convert_report function in the file server_classes.py. In fact, he comes from this line :
`convertion = Popen([s_office, '--headless', '--convert-to', ext, report.report_filename, '--outdir', os.path.join(self.work_dir, 'static', 'reports')], stderr=STDOUT,stdout=PIPE)`

I had to add this argument `'-env:UserInstallation=file:///C:/Temp/test'` to fix the problem but I know it's not a lasting solution.

It's the same problem described [here](https://ask.libreoffice.org/en/question/182108/not-able-to-launch-soffice-within-an-application-on-the-iis-server/)

**Comment by jam-py** [comment]
Hello,

I am sorry for the delay with the answer.
You can write the on_convert_report event handler where you can write
the code of report conversion:

https://jam-py.com/docs/refs/server/reports/on_convert_report.html

Regards,
Andrew Yushev

ср, 2 сент. 2020 г. в 18:22, jgwacyk <notifications@github.com>:

**Comment by jgwacyk** [comment]
Ok thanks for the answer :)
