### ISSUE TITLE
Add support for oauth2/openid authentication

### ISSUE THREAD

**Issue by Kkeller83** [jam-py/jam-py#179]
Could you add support for this please? 

:)

**Comment by jam-py** [comment]
Hello,

I published an afla release of version 6 in the github develop branch.
I think this kind of authentication is possible now.
But I am not expert in this kind of authentication details.
If you try to implement it I'll be happy to help you.

Regards,
Andrew Yushev



пн, 7 сент. 2020 г. в 13:25, Kkeller83 <notifications@github.com>:

**Comment by alucab** [comment]
@jam-py can you give me some more precise pointers to the alpha code you wrote ?
I have some experience with OAuth and I could try (no commitment :-)  ) to give a look

**Comment by platipusica** [comment]
@alucab 

Just pull devel branch from git. However, there is no any code for Oauth in it.
It
