### ISSUE TITLE
Login to demo

### ISSUE THREAD

**Issue by rabit1** [jam-py/jam-py#18]
Hi,

Downloaded jam.py, ran the demo, but
What is the login and password for the demo?

Thank you,

**Comment by jam-py** [comment]
The login is admin, password is 111

2017-01-07 6:34 GMT+03:00 rabit1 <notifications@github.com>:

**Comment by dbabicwa** [comment]
cd demo
sqlite3 admin.sqlite 
select * from sys_users;
1|0|0||Bob|admin|111|1||1
2|0|0||Tom|user|222|6||


The above :)

**Comment by dbabicwa** [comment]
Hi Andrew,

I think this is interesting question as well. How difficult is to implement md5 passwords?

Cheers

Dean

**Comment by jam-py** [comment]
Hi, Dean,
The md5 passwords are working now.
I published the new version.
Andrew
