### ISSUE TITLE
v6 dev Demo Invoices missing OK

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#184]

**Comment by jam-py** [comment]
The data are saved each time detail changes.
If you need the button it can be added

function on_edit_form_created(item) {
    item.edit_form.find('.form-footer').show();
    item.read_only = item.paid.value;
}

ср, 9 сент. 2020 г. в 06:18, platipusica <notifications@github.com>:

**Comment by jam-py** [comment]
The calculation and validation of invoice is done on the server now.
It is a more secure way.



ср, 9 сент. 2020 г. в 10:22, Andrew Yushev <yushevaa@gmail.com>:

**Comment by platipusica** [comment]
Cool, but the OK button is more natural.
