### ISSUE TITLE
Pls Add Brazilian-Portuguese Translation

### ISSUE THREAD

**Issue by MaxMorais** [jam-py/jam-py#187]
Attached there's the Brazilian Portuguese translation

[Portuguese_pt-BR_2020-10-16_12-28-31.zip](https://github.com/jam-py/jam-py/files/5392636/Portuguese_pt-BR_2020-10-16_12-28-31.zip)

**Comment by jam-py** [comment]
Hi, Maxwell

Thank you!
I'll add your translation to the next release.

Can I add you to Jam.py contributors list?

Regards,
Andrew Yushev

пт, 16 окт. 2020 г. в 18:31, Maxwell Morais <notifications@github.com>:

**Comment by MaxMorais** [comment]
Hi @Andrew, thank you

I really want contribute more into the project. 

So let me know how can I participate for this amazing project

**Comment by platipusica** [comment]
Hi Max, 
if I may, where do you see yourself helping with? Is it developing, testing, or something third? 
Cheers

**Comment by jam-py** [comment]
Hi, Maxwell

Great!
Thank you.

Regards,
Andrew Yushev

пн, 19 окт. 2020 г. в 09:08, platipusica <notifications@github.com>:

**Comment by MaxMorais** [comment]
@platipusica On wathever is available

About me
I do have around 10 years in Python and JavaScript
I'm also member of ERPNext community and Python Brasil

I'm working right now, with another framework called frappe, that share the same vision of jam-py, but it's bigger, and what I love in jam-py is the simplicity and how lightweight the core is.

So, on whatever is available, I'll join for sure.

**Comment by platipusica** [comment]
Cool

here is a thought, enum is a good candidate ;) Instead of creating the Lookup list manually for each enum in the DB, why not having an utility to create this, or import as such?
Or here is another, at the moment Jam does not work great on iPad and on mobile phone. 

For me, the most important is to blog, blog and more blog about how good Jam is. The fully functional examples are needed too.

Cheers

**Comment by MaxMorais** [comment]
@platipusica I'll create an Issue for we start discussing about enums handling in jam-py!
Soon we do have an settlement about what's expected to jam-py handle enums, I'll start working on the PR.

**Comment by arisobel** [comment]
Hi There. That's me entering the chat...

I want to expose that, our very humble friend Maxwell is one of the 9 main
supporters of ERPnext in the world.
One of the biggest pythonstas in Brazil. A guy who knows thinking out of
the box.

Has a vast knowledge in must of IT subjects. Including systems architecture.

Cheers



Em ter., 20 de out. de 2020 às 06:55, platipusica <notifications@github.com>
escreveu:
