### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by MaxMorais** [jam-py/jam-py#188]
@platipusica, @jam-py 

Regarding the enum to code discussion I started here https://groups.google.com/d/msgid/jam-py/f980170f-51f0-4a2e-a2d3-56dfec306a98n%40googlegroups.com, I understand there's 2 possibilities for that.

1 - When importing a legacy database, jam-py should look for enums declared into legacy database, and automatically create the lookup lists
2 - When a lookup list is declared, enums should be defined somewhere into the project, for be used on the py and JS coding.

So, regarding this, both are compatible with jam-py or no?

**Comment by jam-py** [comment]
Hi, Maxwell

I think it is compatible.

The admin.js file in the js folder of package has the import_table function
function import_table(item, imp)
that is called when the user selects a table to be imported.

It calls the server_import_table function defined in the builder.py module
in the admin folder.

Then the get_table_info function is called that returns the table
information.
This function is defined in the corresponding module in the db folder.

You can get the information for enum fields and add the lookup list
to the SYS_LOOKUP_LISTS table in the admin.sqlite.
Then you can set the ID field value of the lookup list as a
value of the f_lookup_values field of the field in the SYS_FIELDS table.

Regards,
Andrew Yushev



вт, 20 окт. 2020 г. в 19:43, Maxwell Morais <notifications@github.com>:

**Comment by MaxMorais** [comment]
Also, there's any reason, why an lookup-list doesn't accept a 0 (zero) value?

For example, this is the documentation of Brazilian Electronical Invoices (NFe), that can be an huge show case for jam-py here in Brasil, develop an issuer for that kind of document, since it's mandatory for any kind of business here.

![Captura de tela de 2020-10-21 22-59-26](https://user-images.githubusercontent.com/1288676/96809778-c2223580-13f1-11eb-8448-dded4f5e715e.png)

I think will be much more transparent in terms of development, if I can define lookup-lists for `tpNF`, and `tpImp` starting at zero, so the info on the database will be the same into the NFe, without mid-translating like

```xml
<tpNF>{{ tasks.item.tpnf.value - 1 }}</tpNF>
```

**Comment by jam-py** [comment]
There is no special reason, The field is integer so the value can be zero.
But I see that it limits the use Jam.py.
Thank you for the comment!
I'll update the code.

чт, 22 окт. 2020 г. в 05:07, Maxwell Morais <notifications@github.com>:

**Comment by MaxMorais** [comment]
Hi Guys!, just to let your both know, I'm having a hard time to understand the core code of jam-py

**Comment by platipusica** [comment]
I think Andrew might help with that after he finishes some urgent issues.

Cheers

**Comment by jam-py** [comment]
Hi, Maxwell

The Jam.py code is not documented and it is practically impossible  to
understand it.
I started to write the code explanation.
I will inform you when it is ready, I think it will take a couple of days.

Regards,
Andrew

ср, 28 окт. 2020 г. в 04:42, platipusica <notifications@github.com>:
