### ISSUE TITLE
New line in report

### ISSUE THREAD

**Issue by dijoux** [jam-py/jam-py#189]
Hi,
In reports, when a variable contains a new line character '\n', it's not converted correctly to be interpreted by calc.
I've fixed it by changing line 646 of `server_classes.py`
from
`d[key] = escape(value)`
to
`d[key] = escape(value).replace('\n', '</text:p><text:p>')`

**Comment by jam-py** [comment]
Hi,

It is an interesting solution, I'll add it to the code.

Regards,
Andrew Yushev

чт, 22 окт. 2020 г. в 13:05, dijoux <notifications@github.com>:
