### ISSUE TITLE
reports template has additional tabs

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#190]
Hi, 

the additional is in red color :)

![Jam_report_list1](https://user-images.githubusercontent.com/9026100/97148147-9910f480-17a5-11eb-91e9-6d09304ba7e1.png)

**Comment by jam-py** [comment]
Hi,

The question is not clear. Can you specify it?

пн, 26 окт. 2020 г. в 11:09, platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Hi, 
on Demo, all reports templates sheets have cyrillic nemes, and this one has List1, List2 and List3 :)

**Comment by jam-py** [comment]
Hi,
I corrected it, it will be in the next upgrade.

пн, 8 февр. 2021 г. в 06:56, platipusica <notifications@github.com>:
