### ISSUE TITLE
Blank Screen in views when tables imported.

### ISSUE THREAD

**Issue by tonyanytime** [jam-py/jam-py#191]
Using Mysql. When I create tables in jam-py everything works create. If I import table from csv or mysql into database, then import into jam-py, works about 50% of the time. Tables are fine, I can access fine with other programs. They seem to import fine. But if I try to view them in Jam-py. But in view, I get a blank view that nothing works.
I have check indexes, datatype, data, etc... If I don't import some fields it does sometimes work, but it does not seem to be consistent. 
May be you can point me to some error log file or some other way to know reason view is falling. I can upload a sample file later but got to clear with boss first.
Thanks

**Comment by platipusica** [comment]
Hello there!
Which version u using tho? And which Python and mysql? 
On many occasions the issue is a browser cache. Using a Private Window for Builder helps. 
Clear the cache first. 
There is no error file as such, only the console log.

Cheers

**Comment by platipusica** [comment]
This might help:
mysqldump [options] db_name [tbl_name ...]

```
-- MySQL dump 10.13  Distrib 5.7.32, for Linux (x86_64)
--
-- Host: localhost    Database: osclass
-- ------------------------------------------------------
-- Server version	5.7.32-0ubuntu0.16.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `oc_t_region`
--

DROP TABLE IF EXISTS `oc_t_region`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oc_t_region` (
  `pk_i_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `fk_c_country_code` char(2) NOT NULL,
  `s_name` varchar(60) NOT NULL,
  `s_slug` varchar(60) NOT NULL DEFAULT '',
  `b_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`pk_i_id`),
  KEY `fk_c_country_code` (`fk_c_country_code`),
  KEY `idx_s_name` (`s_name`),
  KEY `idx_s_slug` (`s_slug`),
  CONSTRAINT `oc_t_region_ibfk_1` FOREIGN KEY (`fk_c_country_code`) REFERENCES `oc_t_country` (`pk_c_code`)
) ENGINE=InnoDB AUTO_INCREMENT=782148 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `oc_t_region`
--

LOCK TABLES `oc_t_region` WRITE;
/*!40000 ALTER TABLE `oc_t_region` DISABLE KEYS */;
INSERT INTO `oc_t_region` VALUES (782126,'hr','Šibensko-Kniniska','sibensko-kniniska',1),(782127,'hr','Bjelovarsko-Bilogorska','bjelovarsko-bilogorska',1),(782128,'hr','Brodsko-Posavska','brodsko-posavska',1),(782129,'hr','Dubrovačko-Neretvanska','dubrovacko-neretvanska',1),(782130,'hr','Istarska','istarska',1),(782131,'hr','Karlovačka','karlovacka',1),(782132,'hr','Koprivničko-Križevačka','koprivnicko-krizevacka',1),(782133,'hr','Krapinsko-Zagorska','krapinsko-zagorska',1),(782134,'hr','Ličko-Senjska','licko-senjska',1),(782135,'hr','Međimurska','medimurska',1),(782136,'hr','Osječko-Baranjska','osjecko-baranjska',1),(782137,'hr','Požeško-Slavonska','pozesko-slavonska',1),(782138,'hr','Primorsko-Goranska','primorsko-goranska',1),(782139,'hr','Sisačko-Moslavačka','sisacko-moslavacka',1),(782140,'hr','Splitsko-Dalmatinska','splitsko-dalmatinska',1),(782141,'hr','Varaždinska','varazdinska',1),(782142,'hr','Virovitičk-Podravska','virovitick-podravska',1),(782143,'hr','Vukovarsko-Srijemska','vukovarsko-srijemska',1),(782144,'hr','Zadarska','zadarska',1),(782145,'hr','Zagreb, Grad','zagreb-grad',1),(782146,'hr','Zagrebačka županija','zagrebacka',1),(782147,'hr','šđžšđšžš','iuuzuz',1);
/*!40000 ALTER TABLE `oc_t_region` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-11-02 14:50:13
```

So, take this table if you like, and try to import in in Jam. Does it work?

**Comment by tonyanytime** [comment]
Python 3.6.9 - 
Server version: 10.1.47-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
Test import you gave me worked fine. 
Thanks I will try above, my data with private browser and double check UTF. I did fix that type so not red, but will do again later and let you know.
Once again thanks for quick comment, and a great program.
tony

**Comment by tonyanytime** [comment]
This is structure of one of the tables that does not work

![Screenshot from 2020-11-02 07-13-35](https://user-images.githubusercontent.com/17663943/97866999-00b1cd00-1cdb-11eb-8d35-d7f748e3ae25.png)

**Comment by platipusica** [comment]
It is normal by the look of it.

Something else is wrong. We would need mysqldump tho, maybe with a few
records only.

Cheers

**Comment by tonyanytime** [comment]
I trimmed the database to a bare minimum and then exported table and re-imported it. Same thing.
See dump below.

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

-- CREATE DATABASE `RR2020` /*!40100 DEFAULT CHARACTER SET utf32 */;
USE `RR2020`;

DROP TABLE IF EXISTS `rr1_customers`;
CREATE TABLE `rr1_customers` (
  `CUSTOMER` varchar(30) DEFAULT NULL,
  `ADDRESS` varchar(30) DEFAULT NULL,
  `CITY` varchar(30) DEFAULT NULL,
  `ST` varchar(2) DEFAULT NULL,
  `ZIP` varchar(11) CHARACTER SET utf32 DEFAULT NULL,
  `CONTACT` varchar(27) DEFAULT NULL,
  `PHONE` varchar(12) DEFAULT NULL,
  `FAX` varchar(12) DEFAULT NULL,
  `MOBILE` varchar(12) DEFAULT NULL,
  `EMAIL` varchar(77) DEFAULT NULL,
  `Active` varchar(1) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=999 DEFAULT CHARSET=utf8;

INSERT INTO `rr1_customers` (`CUSTOMER`, `ADDRESS`, `CITY`, `ST`, `ZIP`, `CONTACT`, `PHONE`, `FAX`, `MOBILE`, `EMAIL`, `Active`, `id`) VALUES
('10TH AVENUE PARTNERS, LLC',   '1212 S. ANDREWS AVENUE, SUITE ',       'FORT LAUDERDALE',      'FL',   '33316',        'John Smith',   '954-832-1115', '954-811-1196', '954-111-6896', 'tony@gmail.com',       'Y',    1),
('4 KIDS OF SOUTH FLORIDA',     '827 SOU11TH ST ROAD 7',  'NORT LAUDERDALE',      'FL',   '33068',        'EMILIO MC ',        '888-888-888',  '888',  'eee',  'gold1en1e@b1111h.net',       'n',    4);

-- 2020-11-02 21:58:34

**Comment by tonyanytime** [comment]
Hold the phone... it may not like the name of field... Active

**Comment by jam-py** [comment]
Hi,

Thank you for the dump!
The problem is that active is a reserved word in Jam.py.
I'll add a check for such fields.

Regards,
Andrew Yushev


вт, 3 нояб. 2020 г. в 01:32, tonyanytime <notifications@github.com>:

**Comment by tonyanytime** [comment]
BTW do you have a reserve word list for Jam.py

**Comment by jam-py** [comment]
Hi,

I made a check on reserved words.
Please, upgrade the package.
There is no limitation on imported table field names.
Just rename jam.py field name, for example, active to active_customer.
[image: rtl.png]

вт, 3 нояб. 2020 г. в 23:51, tonyanytime <notifications@github.com>:

**Comment by tonyanytime** [comment]
Thank you
