### ISSUE TITLE
Can't get Report Templates to work

### ISSUE THREAD

**Issue by tonyanytime** [jam-py/jam-py#192]
Whenever I do a report, I get a blank sheet. I am very probably not doing something correctly.
 I do not understand fully how this works based on the documentation I have for it. 
May be it could be my version LibreOffice Calc which is the latest one. 
My template is very simple. I believe that template is just a sheet, with field for  band in column A, and test and fields in column B.
I get a blank screen back. I don't know if I have to anything else but put it in Reports.

**Comment by platipusica** [comment]
Hi, 
there is an issue with  LO > 6.0.7
D.

**Comment by tonyanytime** [comment]
Imagine.... running on 7.0

**Comment by jam-py** [comment]
Hi,

The reports require some code.
You need to write the on_generate event handler in which
you must fill the cells and print bands.
You must use the code editor
https://jam-py.com/docs/admin/code_editor.html


Regards,
Andrew Yushev

пт, 6 нояб. 2020 г. в 17:29, tonyanytime <notifications@github.com>:
