### ISSUE TITLE
Search characters not showing bold on table

### ISSUE THREAD

**Issue by anton78bon** [jam-py/jam-py#196]
Hi, just found this great framework and try it. I think this is a beginner question, but why the search result not bolded as it supposed to be?

![Screenshot 2020-12-04 194146](https://user-images.githubusercontent.com/2674004/101165160-c5ebdd80-3668-11eb-98fe-ef86c37b92ac.png)

**Comment by platipusica** [comment]
Hi,
Thanks, it was reported already on a mail list.
Version before is ok.

Cheers

**Comment by anton78bon** [comment]
@platipusica Thanks a lot :)
