### ISSUE TITLE
Latest update for extensions doesn't work in a fresh install on windows.

### ISSUE THREAD

**Issue by pwillard** [jam-py/jam-py#197]
Fresh install of v5.4.107 shows the following error on windows (Python 3.75), running builder.html for the first time.

ERROR: Invalid upload file extensions 

...when entering "English" in the language field

https://i.imgur.com/c2C3ho3.jpg

**Comment by platipusica** [comment]
Hi,

Which python tho?

**Comment by jam-py** [comment]
Hi, Pete

I fixed the bug. Please upgrade.
Thank you for the feedback!

Regards,
Andrew Yushev

пн, 4 янв. 2021 г. в 17:31, platipusica <notifications@github.com>:

**Comment by pwillard** [comment]
Yes, this issue is now resolved. thank you
