### ISSUE TITLE
Using Field Name "owner" breaks the system

### ISSUE THREAD

**Issue by alucab** [jam-py/jam-py#198]
I was playing with a new project and i  think i found a bug

Using as field name the word **owner** breaks the system. I think that it substitutes something in the object hierarchy and the table using this field stops working

I see javascript errors about prop.find impossible in the console

I think it should become a reserved word

From the mailing list someone suggests that also **order** should become a reserved word

![image](https://user-images.githubusercontent.com/518399/106430274-dbfcfb00-646b-11eb-9100-f4aaa75a1a3e.png)

**Comment by jam-py** [comment]
Hi,

You are right.
I'll do it.
Thank you for the feedback!

Regards,
Andrew Yushev


пн, 1 февр. 2021 г. в 11:01, Luca Barba <notifications@github.com>:
