### ISSUE TITLE
Is it possible to plugin a different DB?

### ISSUE THREAD

**Issue by saritasa** [jam-py/jam-py#2]
1/ How to use MySQL or Postgresql? 
It looks like modules are dynamically created through admin? 

2/ How to connect to external DB, that is not running on localhost?

**Comment by saritasa** [comment]
3/ How about Mongodb?

**Comment by jam-py** [comment]
You can use it with Sqlite, Postgresql and Firebird. Work is now on adding MySQL. And I think you can add other databases as well. The problem is that project became very big and I work on it alone. I need help.

**Comment by jam-py** [comment]
The modules are static. The developer wites them in admin. I tried to describe it in user guide (in the doc folder of the project)
But SQL queries to database are generated dynamically
To connect to a database the framework uses standard python connect method of the database, Only parameter values are set in the fields when developer creates a project. 
The project was designed for relational databases.

**Comment by jam-py** [comment]
To use it with NoSQL databases additional work is needed
