### ISSUE TITLE
v5,v6 not able to set Deleted Flag on Import...

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#200]
...even though the deleted (INT) is in the table, ie SQLITE3:

```
CREATE TABLE "TEST2" (
    "ID" INTEGER PRIMARY KEY,
    "DELETED" INTEGER,
    "TEXT" TEXT
);
```
In v6, the INTEGER is not recognised on Import, in v5.109 it is recognised.

Thanks

**Comment by jam-py** [comment]
Thank you for the feedback!
I'll check it.

пн, 8 февр. 2021 г. в 06:48, platipusica <notifications@github.com>:
