### ISSUE TITLE
Docs - v5

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#202]
From the maillist:

A Note: The option custom_menu does not described at create_menu Jam.Py documentation (https://jam-py.com/docs/refs/client/task/m_create_menu.html

Cheers

**Comment by jam-py** [comment]
Hi,

I'll add it in the next update.
Thank you for the comment.

Regards

ср, 17 февр. 2021 г. в 10:18, platipusica <notifications@github.com>:
