### ISSUE TITLE
Feature - add Export/Import for Tables

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#203]
Hi, 

I think it would be of great value to add Export/Import feature for the Tables as well. Basically this would open possibility to have solutions like users Authentication simplified.

Thoughts?

Cheers

**Comment by jam-py** [comment]
Hi,

There is an idea to create a visual interface for Export/Import,
where users can specify what they want to export or import.

Regards



ср, 24 февр. 2021 г. в 07:10, platipusica <notifications@github.com>:

**Comment by FSTK-Development** [comment]
После экспорта из sqlite и импорта в mysql таблицы загрузились успешно, но проект не работает. выводит ERROR: "level_id" Что не так?

**Comment by jam-py** [comment]
Павел, хорошо бы увидеть серверный лог.


сб, 10 апр. 2021 г. в 21:23, Plotnikov Pavel ***@***.***>:
