### ISSUE TITLE
[BUG] - No Such Column

### ISSUE THREAD

**Issue by MaxMorais** [jam-py/jam-py#204]
Hi @jam-py 

I'm receiving this `no such column` exception on jam-py

![image](https://user-images.githubusercontent.com/1288676/111653425-aa0ae280-87e6-11eb-8474-aa1f6f6bc296.png)

Here is the table that is causing the issue

![image](https://user-images.githubusercontent.com/1288676/111654093-33221980-87e7-11eb-87b4-044335788a83.png)

Here is a copy of my project

https://drive.google.com/file/d/1UHxqjXtpW1H40NOIZg38_iNrxDlk9Z46/view?usp=sharing

Any idea about what can cause this weird issue?

Note, my project have lots of tables, but this is the unique table, that have this weird issue

**Comment by platipusica** [comment]
Hi Max,

Which DB tho?

**Comment by MaxMorais** [comment]
SQLite3

**Comment by MaxMorais** [comment]
@platipusica @jam-py I'm closing this!
