### ISSUE TITLE
v6 static folder and index.html issue, bug?

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#206]
Hi, 

here is the export:
https://drive.google.com/file/d/1WpSOvEkyrz3l9TD4_wiq-JhP-_EDaF59/view?usp=sharing

Looks like Jam v6.27 will delete the folder /static/internal on startup which is used for this project.

Also looks like index.html will not load below (note **internal** is now not used in the project below, renamed internal to **messages**!!!). The internal is used on above export:
```
        <script>
        $(document).ready(function(){
            task.load();
            $.ajax({
                url: '/static/messages/message.html',
                success: function(result) {
                    if (result) {
                        $('#login-message').html('<h5>Notices</h5>' + result);
                    }
                },
                cache: false
                });
            });
            
        </script>
```
It does load it in v5.

Cheers

**Comment by jam-py** [comment]
Hi

The code in the ready  method is executed.
Please try to set a breakpoint in the debugger.
There is something wrong with ajax call

Regards

пн, 19 апр. 2021 г. в 09:16, platipusica ***@***.***>:

**Comment by jam-py** [comment]
As for the internal folder it is used internally by App builder.
I'll change the code so that the internal folder won't be deleted.
Thank you for your feedback.

вт, 20 апр. 2021 г. в 20:40, Andrew Yushev ***@***.***>:
