### ISSUE TITLE
Use external database for admin e langs

### ISSUE THREAD

**Issue by cannatag** [jam-py/jam-py#208]
I have a production application running in a container on a server cluster. I'd like to keep the admin and langs db outside of the container, possibily on the same postgresql external database where data are stored.  In this case when I update the apps with the builder I don't have to extract the admin.sqlite and langs.sqlite from the container. 

This is because the container is reset to the original admin.sqlite and langs.sqlite every time it starts.

Thanks,
Giovanni

**Comment by platipusica** [comment]
I am afraid we cant advice on this. Jam is designed the way it is for now. Just like the containers are.

**Comment by cannatag** [comment]
Thanks for your fast response! As a second choice is possible to provide a different name for the admin.sqlite file? I have the same configuration for test and production, except for the external database and I need to specify the db connection string at runtime.

**Comment by platipusica** [comment]
In practise you could use a symbolic link:
mv admin.sqlite prod.sqlite
ln -s prod.sqlite admin.sqlite

Hope this helps.

**Comment by cannatag** [comment]
thanks. I've adopted a similar approach in the stackfile for the container. 

Jam.py is really great. An employee in my company is using it and now I must include his application in our company portal. So I'm trying to integrate it in our production system with our SSO authentication. I really appreciate it.

**Comment by platipusica** [comment]
No probs.
Define SSO? ;)

**Comment by cannatag** [comment]
We have different options for SSO. All options derives from our IAM (identity and access management) system. Also the application is "protected" by a reverse proxy that can perform additional operation on every HTTP request/response message.

Ranking from the simplest to the complex, the SSO option are:
- automatic fill of the form login (the user access the first time with a custom user and password and then the SSO automatically handle the login for subsequent sessions). This is the weakest option because is subject to password modification and expiration. 
- "identity injection" in the header of each request. In this case the SSO system handle the authentication for the user and then insert a custom header in each request with information on the indentity (and additional attribute of the user). The application must be capable of reading the http request headers.
- LDAP authntication: the credential of the user are checked against the SSO LDAP repository by the application 
- OAUTH2/OPENID: the application uses the OAUTH2 protocol to authenticate the user
- SAML: the application uses the SAML2 protocol to authenticate the user

I'd like to use the "identity injection" but I don't know if I can read the request headers in the server module (on_login, on open).

Also the application should show to the user only data relevant to him/her. I've found an example of how to do this in your docs: https://jam-py.com/docs/how_to/how_to_multitenancy.html

Thanks,
Giovanni

**Comment by platipusica** [comment]
Injection wont work Im afraid. Not out of box, and not in v5.

SAML is and will be only supported in v7.


Cheers

**Comment by cannatag** [comment]
I was able to do injection from the request headers in the on_login() server module. It was quite simple:
```
user = task.environ['HTTP_USER']  # the USER header is injected by the reverse proxy
```
then I add the other information I need in the returned session of the on_login() 
method:
```
    return {
                'user_id': 2,  # generic user
                'user_name': task.environ['HTTP_NAME'] + ' ' + task.environ['HTTP_SURNAME'],
                'role_id': 2,  # generic role (non Administrator)
                'role_name': 'User',
                'user_dept': task.environ['HTTP_DEPT']
    }
```

Then I retrieve the session in the on_open() server method and filter the data based on the user_dept value (showing only data pertaining to the user department).

In the on_apply() server method I check if added/modified data are relevant to the user department and don't allow any other changes, raising an Expception (as suggested in your documentation). In this case the server (Gunicorn in my case) shows an "Internal Error" and the user application stops running. There is a way to get a message on the user screen, handled by the app, instead of the generic message from the server?

Jam-py docs states that " If the user is editing the record on the client using an edit form he won’t be able to save it and will see the corresponding alert message" raising an Exception in the on_apply() method. But this doesn't happen.

Can you suggest me how to display an alert in the on_apply() method?

Thanks again,
Giovanni

**Comment by platipusica** [comment]
@jam-py maybe to advice?

**Comment by jam-py** [comment]
Hi,

When a developer raises an exception on_open the server processes it and
returns
to the client the information that exception was raised. Please see the
video.
Can you send the code where you raise the exception.

Regards

**Comment by cannatag** [comment]
This is the on_apply() function:

```
def on_apply(item, delta, params, connection):
    if item.session and 'user_info' in item.session:
        depts_id_rw = item.session['user_info']['depts_id_rw']
        if depts_id_rw:
            for d in delta:
                if d.dept_id not in depts_id_rw:
                    raise Exception('You are not allowed to modify data for another department')
```
The on_login() function adds the deps_id_rw list to the user_info dictionary in the user_info user session:

```
def on_login(task, form_data, info):
    depts = task.environ['HTTP_DEPTS_ID_RW'].lower().split(';')  # DEPTS_ID_RW is a string in the the form dept1;dept2;deptN
    depts_db = task.depts
    depts_db.open()
    for rec in depts_db:
        if s.dept_name.value in depts:
            depts_id_rw.append(s.id.value)
    return {
                'user_id': 2,
                'user_name': task.environ['HTTP_NAME'] + ' ' + task.environ['HTTP_SURNAME'],
                'role_id': 2,
                'role_name': 'User',
                'depts_id_rw': depts_id_rw,
    }
```
Our Identity and Access Management system injects the user name, surname and allowed depts in the header of each request. 

If a user tries to modify a record he is not allowed to, the exception in the on_apply() function is raised and the user sees a 500 Internal error without any other information. I'm using gunicorn in a container to serve the application.

**Comment by platipusica** [comment]
It would be great  if u privide a way to simulate this. Im afraid we have no infratructure so not easy to debug.
As we know, it is not Jam which does 500 error. And with Gunicorn its even worse since no logs, correct?
So u mixing a lot of technologies Jam was not tested with. Hence, the community should also contribute with fixing issues on/with their setup.
Just my 2c...

**Comment by jam-py** [comment]
At least I see one bug:
the condition in the line below will never be True because d.dept_id is an
object (should be d.dept_id.value)
if d.dept_id not in depts_id_rw:

Maybe try to export the project to a metadata file, create a project with
SQlite database, import metadata and try to debug the code.

**Comment by cannatag** [comment]
Hi, I've found that the "internal error" message from gunicorn happens only if the "debugging" flag is enabled in the jam-py project parameters. If this flag is not enabled I get the Exception message in the upper right corner of the screen.

Thanks a lot for this framework, it's really great!

**Comment by platipusica** [comment]
Hi @cannatag 

I am puzzled with your approach to this:

"The actual user authentication is managed by our IAM system that simply hits the login button in the login form in a way that is hidden to the user browser."

Could you explain in more details how that works? Is the default Jam login form not used with Safe Mode turned on? 

Thanks

**Comment by cannatag** [comment]
Sorry, I see the description in my previous message was quite obscure. Will try to explain it in a better way.

We have a corporate portal that is made up of many applications from different developers. The portal itself is behind a reverse proxy cluster and the reverse proxy service is driven by our IAM (identity and access management) system that provides a single signon experience to users.

When a user access the main page of the portal the authentication page is shown. This page comes from the IAM system, not from the portal. Once the user is authenticated the reverse proxy (driven by the IAM rules) injects the user credentials in the various applications when the authenticated user accesses them.

Obviously for this to work all the applications behind the corporate portal must be accessed only through the reverse proxy that protect it from unauthorized access.

In the case of the application developed with jam.py the reverse proxy injects the name of the authenticated user (and some other info that are stored in the jam.py user session) in the header of the request, and the on_login() event reads it from the request object. So the user and password fields of the login form are really unused. In a former version I simply hit the ok button on the form, but now I’ve changed the login form to a “welcome form” that shows some useful information to the logged user.

The application is in safe mode, is built inside a container (that contain the OpenOffice calc binaries for reporting) and packed in a Docker swarm service; the DB is on an external Postgres service and uses a gunicorn web server with nginx that accepts connections only from the IPs of the reverse proxy cluster.

The admin.sqlite and the langs.sqlite are injected into the swarm service at runtime, so we can have exactly the same Docker image for the test and the production environment (the whole architecture is duplicated for test and production).

Hope the description is more clear now, sorry for being too terse in my previous messages.

We are going into production on the first of June, with at least 50 users, most of them with readyonly roles and a few with the privilege to modify data.

I would let you know that I really like jam.py framework and its modular approach allowed me to integrate the application in our systems with no hassles!

Thank,
Giovanni

**Comment by platipusica** [comment]
Sounds good, 

Cheers

**Comment by cannatag** [comment]
Tra application works great! The only issue is with the admin.sqlite that must run inside the container, it would be great if it were on an external database, so the container could be restarted with no risk of loosing changes in the configuration.

**Comment by platipusica** [comment]
@cannatag yep, I hear you. Hopefully, the community will contribute.

Ciao

**Comment by platipusica** [comment]
Hi @cannatag 

hope you are well! 
Could you please help us a bit with LDAP search and Jam? I am doing below, but when uidNumber is not found  getting a traceback.

```
# import class and constants
from ldap3 import Server, Connection, ALL

def get_ldap_user(item, uidnumber):
# define the server
    LDAP_SERVER = 'ldap://127.0.0.1:389'
    try:
        conn = Connection(LDAP_SERVER, auto_bind=True, raise_exceptions=False)
        conn.search(
            search_base='ou=users,dc=example,dc=com',
            #search_filter='(uidNumber=)',
            search_filter="(uidNumber="+ uidnumber +")",
            search_scope='SUBTREE',
            attributes = ['cn']
        )
        result = conn.entries[0].cn.values
    except Exception as e:
        print("authentication error")

    return result
```
How to solve this, would you know? So if uidNumber not found, we get empty return.

Thanks

**Comment by cannatag** [comment]
Hi, what is the exception you receive? in the Connection object you can use the return_empty_attributes=False to raise an exception if the searched attribute does not exist, if it is set to True you get an empty list.

Let me know if you need more help on the ldap3 library.

Bye,
Giovanni

**Comment by platipusica** [comment]
Hello Giovanni,
thanks for you time. Appreciated. And of course, thank you for ldap3 lib :)

No matter of return_empty_attributes flag, getting:
```
[Fri Aug 13 02:27:19.472363 2021] [wsgi:error] [pid 203393] [remote 120.16.20.94:52420]   File "LDAP.catalogs.ldap_query", line 20, in get_ldap_user
[Fri Aug 13 02:27:19.472367 2021] [wsgi:error] [pid 203393] [remote 120.16.20.94:52420]     return result
[Fri Aug 13 02:27:19.472382 2021] [wsgi:error] [pid 203393] [remote 120.16.20.94:52420] UnboundLocalError: local variable 'result' referenced before assignment
```
The above code is here:
https://conv.jampyapplicationbuilder.com/ldap2/builder.html

Click on Task/Group/Catalogs/Ldap Query table -> Server Module if you like. So when searching for 10001 or 10002 in here:
https://conv.jampyapplicationbuilder.com/ldap2
this would work. But exception happens with anything else.

Thanks
