### ISSUE TITLE
Automating of Catalogs from existing tables

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#21]
Hi Andrew,

hope you're well.

Some time ago I think we mentioned something like utility to create Catalogs from existing tables in the database. 
Would you have something like this already?
Thanks!

**Comment by jam-py** [comment]
Hi, Dean.
I am Ok.
I can make such utility.
Can you write for the your database the following functions?

def get_tables(connection) - returns list of table names
def get_fields(connection, table_name) returns list fields for the table
def get_primary_field(connection, table_name) returns field name of the
primary key

And it's desirable to have such functions for indexes and foreign keys
And of course it will take sume time.

Regards


2017-01-17 16:30 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Ah, ok, I was hoping you have something :) I am a Linux SysOps, no dev experience unfortunately. 

Cheers

**Comment by jam-py** [comment]
Ok, Dean. Anyway I plan to do this utility. What database do you use?

2017-01-18 16:38 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Hi Andrew, Oracle is what we're using.

**Comment by dbabicwa** [comment]
Cool, lets close it and see how it goes. No worries. Cheers!
