### ISSUE TITLE
Bug in text resize

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#210]
Hi, 
on Demo, resize Albums/Title to 260, and update Title with 200 long, for example:
...And Justice For AllgfdagdsdfgadgdfgdfgdfagdfagadfgdfagdafgdafgdafgdfagadfgfdgdafcxvCXVXCVCXVCXVCXVXCVXCVXCvbnvxjkvhksdhFKJSDHKSDHFjkhsdfhsdkhfkjshFJKSHKfhaskHFHSAJKFHJKSAHfjksahFJKHSAJKFhjskaHFHSJ

Please observe what happens and how it is highlighted in regards to other rows.

Thanks

**Comment by jam-py** [comment]
Hi,

What version do you mean?

вт, 29 июн. 2021 г. в 12:50, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Current.
