### ISSUE TITLE
AttributeError: 'Task' object has no attribute 'safe_mode'

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#211]
Hi, 

the Export is here:
https://github.com/jam-py/jam-py/issues/97

https://github.com/jam-py/jam-py/files/2939956/oracle_hr_schema_1.0.3_5.4.37_2019-03-07_15-31-02.zip

Import into v112 and this will produce a traceback....

Regards

**Comment by jam-py** [comment]
Hi,

Please specify what database you use and send the traceback.

Regards,
Andrew Yushev


чт, 1 июл. 2021 г. в 13:28, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Any Andrey,

Try with sqlite. Just use this export. There is a client part which references safe_mode for changing password for the user. 

Thx

**Comment by jam-py** [comment]
Yes, I see now.
Please replace the can_change_password function in the task server module

def can_change_password(task):
    if task.consts.SAFE_MODE and task.on_login:
        return True

сб, 3 июл. 2021 г. в 03:00, platipusica ***@***.***>:
