### ISSUE TITLE
Create lock item: ORA-00972: identifier is too long

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#212]
Using Oracle XE:

```
ERROR - ORA-00972: identifier is too long
Traceback (most recent call last):
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/server_classes.py", line 248, in apply_changes
    result = self.on_apply(self, delta, params, connection)
TypeError: items_apply_changes() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/execute.py", line 30, in execute
    cursor.execute(command)
cx_Oracle.DatabaseError: ORA-00972: identifier is too long
Traceback (most recent call last):
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/server_classes.py", line 248, in apply_changes
    result = self.on_apply(self, delta, params, connection)
TypeError: items_apply_changes() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/execute.py", line 135, in execute_sql_connection
    result = execute_list(cursor, db_module, command, delta_result, params, select)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/execute.py", line 109, in execute_list
    res = execute_command(cursor, db_module, com, params, select)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/execute.py", line 40, in execute_command
    result = execute(cursor, command, params)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/execute.py", line 30, in execute
    cursor.execute(command)
cx_Oracle.DatabaseError: ORA-00972: identifier is too long
ERROR - While creating an item the following error was raised: Error while creating table: ORA-00972: identifier is too long
Traceback (most recent call last):
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/server_classes.py", line 248, in apply_changes
    result = self.on_apply(self, delta, params, connection)
TypeError: items_apply_changes() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/admin/builder.py", line 1094, in create_system_item
    items.apply(params={'manual_update': False})
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/dataset.py", line 1724, in apply
    self.do_apply(params, safe, connection)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/server_classes.py", line 109, in do_apply
    data, error = self.apply_changes((changes, params), safe, connection)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/server_classes.py", line 252, in apply_changes
    result = self.on_apply(self, delta, params)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/admin/builder.py", line 1425, in items_apply_changes
    result = items_execute_insert(item, delta, manual_update)
  File "/home/.../Downloads/SAML/py38/lib/python3.8/site-packages/jam/admin/builder.py", line 1351, in items_execute_insert
    raise Exception(item.task.language('error_creating_table') % (error))
Exception: Error while creating table: ORA-00972: identifier is too long
127.0.0.1 - - [01/Jul/2021 18:30:00] "POST /api HTTP/1.1" 200 -
```

Placeholder, please leave now for more testing...

Thanks

**Comment by platipusica** [comment]
Yep,
confirmed.

**Comment by jam-py** [comment]
Hi,

Thank you for the feedback!

It seems that some identifier in the table definition exceed 30 characters.
Please change it.

I'll  see what I can do.

Regards,
Andrew Yushev

чт, 1 июл. 2021 г. в 14:12, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Hi Andrey

Not sure about that. The App is working fine. This happens when I try to create Lock item on Parameters.

Thanks

**Comment by jam-py** [comment]
The exception raised is

Error while creating table: ORA-00972: identifier is too long

Please see:
http://www.dba-oracle.com/sf_ora_00972_identifier_is_too_long.htm#:~:text=Cause%3A%20An%20identifier%20with%20more,names%20which%20are%20too%20long
.

сб, 3 июл. 2021 г. в 02:55, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Hi Andrey,

I think I provided the export in here:
https://github.com/jam-py/jam-py/files/2939956/oracle_hr_schema_1.0.3_5.4.37_2019-03-07_15-31-02.zip

I started to hate testing Jam since a lot of issues are coming back
like it is my fault somehow :(
Ok, no worries, I will stop doing github issues.


Here is the import in clean sqlite3. The "Lock Item" will work. It
just does not work in Oracle.

The metadata have been successfully imported
Import log
Import: reading data
Import: checking data integrity
Import: analyzing changes
Import: waiting for connections to close
Import: applying changes to the database
CREATE TABLE "REGIONS" ( "REGION_ID" INTEGER PRIMARY KEY, "REGION_NAME" TEXT)
CREATE TABLE "COUNTRIES" ( "COUNTRY_ID" TEXT PRIMARY KEY,
"COUNTRY_NAME" TEXT, "REGION_ID" INTEGER)
CREATE TABLE "JOBS" ( "JOB_ID" TEXT PRIMARY KEY, "JOB_TITLE" TEXT,
"MIN_SALARY" INTEGER, "MAX_SALARY" INTEGER)
CREATE TABLE "DEPARTMENTS" ( "DEPARTMENT_ID" INTEGER PRIMARY KEY,
"DEPARTMENT_NAME" TEXT, "MANAGER_ID" INTEGER, "LOCATION_ID" INTEGER)
CREATE TABLE "EMPLOYEES" ( "EMPLOYEE_ID" INTEGER PRIMARY KEY,
"FIRST_NAME" TEXT, "LAST_NAME" TEXT, "EMAIL" TEXT, "PHONE_NUMBER"
TEXT, "HIRE_DATE" TEXT, "JOB_ID" TEXT, "SALARY" INTEGER,
"COMMISSION_PCT" INTEGER, "MANAGER_ID" INTEGER, "DEPARTMENT_ID"
INTEGER)
CREATE TABLE "LOCATIONS" ( "LOCATION_ID" INTEGER PRIMARY KEY,
"STREET_ADDRESS" TEXT, "POSTAL_CODE" TEXT, "CITY" TEXT,
"STATE_PROVINCE" TEXT, "COUNTRY_ID" TEXT)
CREATE TABLE "JOB_HISTORY" ( "EMPLOYEE_ID" INTEGER PRIMARY KEY,
"START_DATE" TEXT, "END_DATE" TEXT, "JOB_ID" TEXT, "DEPARTMENT_ID"
INTEGER)
CREATE INDEX "DEPT_LOCATION_IX" ON "DEPARTMENTS" ("LOCATION_ID" )
CREATE UNIQUE INDEX "EMP_EMAIL_UK" ON "EMPLOYEES" ("EMAIL" )
CREATE INDEX "EMP_DEPARTMENT_IX" ON "EMPLOYEES" ("DEPARTMENT_ID" )
CREATE INDEX "EMP_JOB_IX" ON "EMPLOYEES" ("JOB_ID" )
CREATE INDEX "EMP_MANAGER_IX" ON "EMPLOYEES" ("MANAGER_ID" )
CREATE INDEX "EMP_NAME_IX" ON "EMPLOYEES" ("LAST_NAME" , "FIRST_NAME" )
CREATE INDEX "LOC_CITY_IX" ON "LOCATIONS" ("CITY" )
CREATE INDEX "LOC_STATE_PROVINCE_IX" ON "LOCATIONS" ("STATE_PROVINCE" )
CREATE INDEX "LOC_COUNTRY_IX" ON "LOCATIONS" ("COUNTRY_ID" )
CREATE INDEX "JHIST_JOB_IX" ON "JOB_HISTORY" ("JOB_ID" )
CREATE INDEX "JHIST_EMPLOYEE_IX" ON "JOB_HISTORY" ("EMPLOYEE_ID" )
CREATE INDEX "JHIST_DEPARTMENT_IX" ON "JOB_HISTORY" ("DEPARTMENT_ID" )

**Comment by platipusica** [comment]
Very, very weird behavior with Create Lock item....It looks like it is firing creation of T_LOCKS table and then reporting back that the table already exist!

Have a look, deleted T_LOCKS, table, it is not in System Group, tried to add a new T_LOCKS, reports error, but the TABLE IS THERE!

![Screenshot from 2021-07-05 20-45-12](https://user-images.githubusercontent.com/9026100/124473709-3959f700-ddd2-11eb-944f-5235f9be9cb1.png)

![Screenshot from 2021-07-05 20-45-41](https://user-images.githubusercontent.com/9026100/124473740-40810500-ddd2-11eb-8be7-0523bc7ac663.png)
![Screenshot from 2021-07-05 20-48-30](https://user-images.githubusercontent.com/9026100/124473839-63131e00-ddd2-11eb-9831-71663000b860.png)

**Comment by jam-py** [comment]
Dean, unfortunately I have a bad cold because of the air conditioner at
work.
It was very hot here last week.
And I don't have Oracle installed on my computer at home.
I'll try to check it next week or I'll remove Oracle support.
It seems that there are no users of Oracle and it is tested very badly.


пн, 5 июл. 2021 г. в 15:49, platipusica ***@***.***>:
