### ISSUE TITLE
German char bug

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#214]
Hi,

pls try this in sqlite3:

CREATE TABLE `Straße` (`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
`Straße` TEXT )

Actually, none of german chars will work:
geschäftlich
Mindeststückzahl
.
.

This is on table Import:

![Screenshot from 2021-07-31 20-26-39](https://user-images.githubusercontent.com/9026100/127739870-69146ef9-89cb-4ab4-b36e-c119fd278a1c.png)

I think the best is to update documentation since table Import will not work, and this is a fix:
ß = ss
ä = a
etc...

Cheers

**Comment by jam-py** [comment]
Hi,

You should not use german characters in field names.
Please see
https://stackoverflow.com/questions/3373234/what-sqlite-column-name-can-be-cannot-be/45775719

Regards,
Andrew Yushev


сб, 31 июл. 2021 г. в 15:41, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Hi Andrew, 

I think Jam can't force the user not to use local characters. This is perfectly fine even with mysql:

```
mysql> CREATE TABLE Straße (ID INTEGER, Straße TEXT );
Query OK, 0 rows affected (0.04 sec)

mysql> desc Straße;
+---------+------+------+-----+---------+-------+
| Field   | Type | Null | Key | Default | Extra |
+---------+------+------+-----+---------+-------+
| ID      | int  | YES  |     | NULL    |       |
| Straße  | text | YES  |     | NULL    |       |
+---------+------+------+-----+---------+-------+
2 rows in set (0.01 sec)

```

I would propose to document this as per above.

Cheers

**Comment by jam-py** [comment]
Hi, @platipusica 

You must take into account that these names are also used in pthon and javascript code.
Please see 
https://jam-py.com/docs/admin/items/field_editor_dialog.html

Cheers
