### ISSUE TITLE
jam-project.py not working on Windows 10, Std. Python 3.9 install

### ISSUE THREAD

**Issue by bcurrens** [jam-py/jam-py#216]
I've installed jam.py.  When I run pip list is shows jam version 0.0.4 and jam.py as 5.4.113.  This is on a Windows 10 environment with a standard Python 3.9 install, i.e. C:\Program Files\Python39.  I've created a directory and run the following from an admin command shell:  $ python jam-project.py.  Note, that both C:\Program Files\Python39 and C:\Program Files\Python39\Scripts are in my system path.  I can't get past the error below:

python: can't open file 'C:\Users\bcurrens\OneDrive - Infor\SYNC\Code\Python\BVD\JamDemo\jam-project.py': [Errno 2] No such file or directory

If I copy jam-project.py into my newly created directory and run from there I get this:

Traceback (most recent call last):
  File "C:\Users\bcurrens\OneDrive - Infor\SYNC\Code\Python\BVD\JamDemo\jam-project.py", line 7, in <module>
    import jam
  File "C:\Program Files\Python39\lib\site-packages\jam\__init__.py", line 1, in <module>
    import choice, misc, pitch, plot, shuffle, soxsynth
ModuleNotFoundError: No module named 'misc'

**Comment by platipusica** [comment]
Hello,

People used it with success in Win10. Try search Google mailgroup.

Is your python actually working as Admin user?  Not visible from anything.

To test this, download stand alone Jam from here:
https://groups.google.com/g/jam-py/c/tN8DS-hBXsk/m/ZL3sNhBjBQAJ

Does it work?

**Comment by spitoglou** [comment]
Hello,

I think you should find where the jam-project.py is and try executing it from there, e.g. if it is in the `C:\Program Files\Python39\Scripts` directory you should navigate in your new project directory and try:
```
python "C:\Program Files\Python39\Scripts\jam-project.py"
```
... or something like that. I hope this works...

**Comment by bcurrens** [comment]
Hello @spitoglou,

Thanks for your suggestion.  I've run the jam-project.py directly from the C:\Program Files\Python39\Scripts directory.  When I do this, I get a ModuleNotFoundError: No module named 'misc'.  This seems odd because when I look into the C:\Program Files\Python39\Lib\site-packages\jam folder there is a misc.py file located there.

**Comment by bcurrens** [comment]
Hello @spitoglou,

If I modify __init__.py by removing misc, then I get a missing module shuffle.  So, I suspect there is something causing an issue the import jam library not resolving properly.

**Comment by platipusica** [comment]
Im afraid your problem has nothing to do with Jam.

Please demonstrate that Python actually works, since there is a path issue here...

**Comment by bcurrens** [comment]
@platipusica my python environment is working fine, i know this because i am actively using it daily.  let's just set this aside for now.
