### ISSUE TITLE
Can't upload text files other than txt or csv

### ISSUE THREAD

**Issue by noeldum** [jam-py/jam-py#219]
My application need to upload text file with dpv extension. I figured out jam-py does not allow that and return the error below.

**ERROR - machine.dpv - Unable to upload a file. This file type is not allowed**

from wsgi.py around line 753

```
if not ext in consts.upload_file_ext:
           r['error'] = '%s - %s' % (request.form.get('file_name'), consts.lang['upload_not_allowed'])
           self.log.error(r['error'])
```

and in common.py

```
 'UPLOAD_FILE_EXT': '.txt, .csv',
```
Is there a way to get around this?

Adding my extension in common.py is not a solution as not portable. 

jampy 5.4.113 python 3.8.10

**Comment by platipusica** [comment]
Sure it can.

I would suggest searching the mailgroup, it was discussed. 

On Builder/Parameters, see the option?

**Comment by noeldum** [comment]
Found it. Thank you.

I was not aware of the google mailgroup. Will use that for my queries from now on.
https://groups.google.com/g/jam-py

**Comment by platipusica** [comment]
No worries.

Before u go, where did you found about Jam?

**Comment by noeldum** [comment]
doing a github search I think. That was a while ago.

I think the mailgroup link should be put on the main page of the github project. It is only hidden somewhere on the website at the moment.

**Comment by platipusica** [comment]
Fair enough, will update tmrw.

Cheers

**Comment by jam-py** [comment]
Hi, the extension of uploaded file types are set in the project parameters:

[image: image.png]

пн, 30 авг. 2021 г. в 15:51, platipusica ***@***.***>:
