### ISSUE TITLE
The best way the create an App with existing tables?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#22]
Hi Andrew, 

what would be the best way to create an App with existing tables? 

Cheers

Dean

**Comment by jam-py** [comment]
Hi, Dean

I started to develop the import of existing tables. I think it will take
about 10 days.

You can try do it this way:

1. Create a project with existing database. And to be on the safe side
create a backup.

2. In the catalogs and journals groups delete the primary key field – id,
if your primary key fields differs for different table, and deleted flag
field if you don't need it.

3 Go to Project node in the project tree, click on the Database button and
set DB manual mode check box so the database won't be changed when you add
items and their fields.

4. Create items and their fields, specifying the appropriate type.

2017-01-23 11:33 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Ok, 

tried that. 

This export is using Oracle HR schema (included in XE). When created new Zaposlenici table (with id and deleted flag), it will create a sequence and works well.
When trying to use existing Employees table (deleted: id, del flag), cant insert into the table due to a sequence ( ORA-02289: sequence does not exist).

Any ideas?

[HR_1.0.0_4.0.48_2017-01-24_10-11-02.zip](https://github.com/jam-py/jam-py/files/725476/HR_1.0.0_4.0.48_2017-01-24_10-11-02.zip)

**Comment by jam-py** [comment]
Hi, Dean

I see the problem. I need some time to solve it. I will inform you.

Regards


2017-01-24 5:19 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by jam-py** [comment]
Did you use sequences to generate values for primary key fields in your
database?

2017-01-24 14:58 GMT+03:00 Andrew Yushev <yushevaa@gmail.com>:

**Comment by dbabicwa** [comment]
Hi,
the HR database comes pre installed, hence did not do anything.

**Comment by jam-py** [comment]
OK

2017-01-25 10:08 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Ah, I get it, jam is using:

def get_sequence_name(table_name):
    return set_case('%s_GEN' % table_name)

def next_sequence_value_sql(table_name):
    return set_case('SELECT %s.NEXTVAL FROM DUAL' % \
        get_sequence_name(table_name))

Looks like the only thing we need to do is to create (rename) with table_name_GEN sequence for existing sequences. Unfortunately, there is no way to know the sequence name in Oracle.

D.

**Comment by jam-py** [comment]
Hi, Dean.

I am working on it right now.
There are several problems that I am solving and one of them is sequences.
There could be triggers that generate PK values internally so we don't need
to do anything or as you write we must explicitly specify sequences. All
these are quite complicated. I hope to finish it before the end of the
week.

Andrew

2017-02-06 10:28 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by jam-py** [comment]
Hi Dean

I have made a field for an item sequence as you suggested. There is an Import button in manual mode now to facilitate importing of fields for oracle. The work is not finished yet. Sorry it took took long - a lot of work. I am interested to know your opinion - i have no expirience with Oracle. But I am leaving on holiday for 10 days.. 

A.

**Comment by dbabicwa** [comment]
Hi Andrew
no worries, your time is appreciated around the World, I am sure. It is a great project.
Will have a look and let you know.
Enjoy your holiday!

Cheers

**Comment by dbabicwa** [comment]
Quick question though, was 'import' published yet?  Can't find it. Thanks

**Comment by dbabicwa** [comment]
Hi Andrew

just pinging about the 'import' status :) Can I test it already?

Thanks

**Comment by jam-py** [comment]
Hi, Dean

I was very busy after my vacation. There was a very urgent work. I've done
almost nothing. I am very sorry.
I've almost finished with this work now . So I think I'll finish the oracle
import by next monday. I will immediately inform you.

I am realy sorry.


2017-03-28 9:56 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
It is absolutely ok Andrew, I am sorry if being too pushy :)
