### ISSUE TITLE
Change values in a table

### ISSUE THREAD

**Issue by teotenn** [jam-py/jam-py#220]
More than issue it is a question, but I could not find where to post it. I hope you can help me.

I have a table that the user interacts with. They need to see all records, but edit only the ones they are entering in the current session. For that I have created a boolean column Locked, when False, user can edit the record, when True, user cannot. So far it works well but I need to change manually False to True each time. What I want is that all the values will change automatically to True each time a user starts a session. Or it could even be on load page. I just could not find how to do this programmatically. 

Any hint will be welcome.

**Comment by platipusica** [comment]
Hi there, 

Is the user editing current records or creating a new ones ever time?

**Comment by platipusica** [comment]
I would suggest to ask question on mail group, or search Docs for multi tenancy.
Maybe that would work for u.

**Comment by jam-py** [comment]
Hi,

The session has an uuid attribute.
It is not documented, I'll correct it.
https://jam-py.com/docs/refs/server/abstr_item/at_session.html
You can create a field in the table to store it and then use it in the
on_apply event handler.

Regards,
Adrew Yushev

сб, 2 окт. 2021 г. в 16:05, platipusica ***@***.***>:
