### ISSUE TITLE
Jam.py installer bigger than Django install?

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#222]
Hi Andrew, 

could you please reconsider how Jam is packaged for pip? Is is noticeably bigger than years ago, for example:
  Downloading jam.py-1.0.1.tar.gz (5.1 MB)

  Downloading jam.py-5.4.115.tar.gz (15.7 MB)

I think this is because DOCS sources are packaged in Jam, but that goes than into the pip cache where absolutely no one is using it, or even know that is there.

I would recommend to remove completely DOCS, **because there are RaspberryPi users who have limited space.** Django has no docs at all in the package. Docs are the most visited pages on Jam-py.com anyway.

Cheers

**Comment by jam-py** [comment]
Dean, I hoped that there would be some people that you take part in the
docs development,
and other packages such as Django have docs in their packages.

[image: image.png]

вт, 23 нояб. 2021 г. в 05:13, platipusica ***@***.***>:

**Comment by jam-py** [comment]
Dean, There absolutely no problem with docs at all.
You created it out of nothing.
Downloading a 15MB file nowadays is a matter of a split second.
Even more installation of pip doesn't copy docs at all.

пт, 26 нояб. 2021 г. в 05:53, platipusica ***@***.***>:
