### ISSUE TITLE
regression with deleted flag

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#223]
Hi, 
I am not able to select deleted field on table Import as it was possible in v4. Pls see the pics, same database, same table:

![Screenshot from 2021-12-09 10-49-30](https://user-images.githubusercontent.com/9026100/145325715-b35a8f58-5a30-41ce-816c-87a72881780e.png)

![Screenshot from 2021-12-09 10-46-21](https://user-images.githubusercontent.com/9026100/145325940-7ffa717a-195a-4f1d-ace6-9232ae77147f.png)

The form is empty, no fields.

Let me know if you are interested in reporting the issues or not.

**Comment by jam-py** [comment]
Hi, try to add deleted as boolean
чт, 9 дек. 2021 г. в 05:54, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Thx, that worked.
