### ISSUE TITLE
Exception has occurred: AttributeError

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#226]
Hi, Andrew

This error I has get just after start new 7.0.2 project:

Exception has occurred: AttributeError
module 'jam.common' has no attribute 'DEFAULT_LOCALE'
  File "D:\dev\jampy\odrzavanje\odr-v0.50\jam\langs.py", line 163, in get_locale_dict
    raise Exception('Language with id %s is not found' % language)

Problem is langs.py 166 
    result = jam.common.DEFAULT_LOCALE

I tink this is probably :
    result = jam.common.consts.DEFAULT_LOCALE

Regards,

**Comment by jam-py** [comment]
Hi,

Have you succeeded to install the package?
What OS and Python version do you use?

Regards

вт, 5 июл. 2022 г. в 23:54, rrad0812 ***@***.***>:

**Comment by rrad0812** [comment]
OK, Andrew
I would try with 7.0.2.

I don’t have time to new or updated versions.

I think, you don’t published bad versions, do you it? 😊

Pozdrav, 
------------------------
Radosav
+381 65 2006831

Od: jam-py
Poslato: petak, 08. jul 2022. 09:46
Za: jam-py/jam-py
Cc: rrad0812; Author
Tema: Re: [jam-py/jam-py] Exception has occurred: AttributeError (Issue#226)

Hi, Radosav

I am very glad to have a message from you!

It is too early to use this version for development.
The main things are done, but we still need to test and write documentation.
In addition, we still need to upgrade bootstrap to version 5.

Regards,
Andrew


ср, 6 июл. 2022 г. в 23:32, rrad0812 ***@***.***>:
