### ISSUE TITLE
Empty browser page

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#229]
Hi,
Version jampy 7.0.2.
Only empty page on my mozilla browser.
All attempts already do.
On server console dont error!
on browser console:
Error: Loading module from “http://localhost:8080/jam/js/jam.js” was blocked because of a disallowed MIME type (“text/plain”)?!?
What I should to do?

Radosav

**Comment by platipusica** [comment]
Hi Rad,

![firefox](https://user-images.githubusercontent.com/9026100/193502835-909f59ef-462f-40e9-ab93-71106456e3d3.png)

Maybe cache?

**Comment by rrad0812** [comment]
I find solutions.
To change MIME type of .js files to "application/javascript"
REG.EXE ADD "HKEY_CLASSES_ROOT\.js" /v "Content Type" /t REG_SZ /d "application/javascript" /f

Radosav

**Comment by jam-py** [comment]
Yes, it can be cache.
Try doing a hard reload.

пн, 3 окт. 2022 г. в 07:42, platipusica ***@***.***>:

**Comment by rrad0812** [comment]
Hi,

I find solution, already  https://github.com/jam-py/jam-py/issues/229#issuecomment-1265937853. 

Thank you.
