### ISSUE TITLE
V7 BUG: data picker when create new project

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#235]
Hi.

Data picker don't show calendar correctly when create new project:

<img width="497" alt="data-picker" src="https://user-images.githubusercontent.com/63108648/225741651-8d79ca06-8f4a-4f22-a040-ee56a572fc8a.PNG">

**Comment by crnikaurin** [comment]
Also, when try to manualy enter date-time field in edit form, there is error shown:

<img width="450" alt="date-time_error" src="https://user-images.githubusercontent.com/63108648/225741836-81b1d04d-f0ed-4fe6-9e25-b764dce39c7c.PNG">

**Comment by jam-py** [comment]
Thank you for the feedback!
Fixed it.

чт, 16 мар. 2023 г. в 23:13, crni_kaurin ***@***.***>:
