### ISSUE TITLE
V7: pull-right and pull-left class on buttons don't react

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#240]
- [ ] view..form with buttons_on_top class don't push delete button on right

<img width="978" alt="buttons on top" src="https://user-images.githubusercontent.com/63108648/227003765-19e31957-573e-49c5-9d1f-364802540d79.PNG">

- [ ] parameter form file extensions button should show on left:

<img width="448" alt="parameter form" src="https://user-images.githubusercontent.com/63108648/227003960-12537c00-fe67-4ed4-9d99-9e2bb5e66d49.PNG">

**Comment by crnikaurin** [comment]
- [ ] default date type field width is to big (pic above)

**Comment by jam-py** [comment]
In v7 buttons in footer and header are located on one side

ср, 22 мар. 2023 г. в 22:22, crni_kaurin ***@***.***>:
