### ISSUE TITLE
V7: history modal form don't change height dynamically

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#241]
History modal form are shorter that accordions with log record:

<img width="487" alt="history" src="https://user-images.githubusercontent.com/63108648/227011054-efc5c23d-850c-491b-8afd-cfe34e6ca070.PNG">

**Comment by jam-py** [comment]
Unfortunately I can not reproduce it.
Can you specify you environment (os, browser and so on)

ср, 22 мар. 2023 г. в 22:08, crni_kaurin ***@***.***>:

**Comment by crnikaurin** [comment]
Hi Andrew.

I using WIN 10 OS and Mozzila Firefox. On Chrome is everything ok.

Danijel
