### ISSUE TITLE
V7: strange behavior page scroll on builder when table is long - Mozilla Firefox

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#242]
[builder_page scroll.webm](https://user-images.githubusercontent.com/63108648/227015535-7e77e1d3-0220-4c3a-b38c-b917867d98cc.webm)

This hapend on Mozzila Firefox when scroll page slider is shown.

**Comment by jam-py** [comment]
I fixed the bug.
Please check it out.

Besides, I found other bugs related to tables.
If you have time, can you test tables?

in the demo project the on_view_form_created event handler had commented
lines

    // item.paginate = false;
    // item.table_options.show_paginator = false;
    // item.table_options.show_scrollbar = true;

if you uncomment them one by one or in some combination you will get
different table behavior.
It would be good to test it on different devices.

Btw, tables in jan.py use virtual scrolling, so when item.paginate is false
the can display data with unlimited number of records.
