### ISSUE TITLE
V7: bulider - view_form setting

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#244]
In this form, Delete, Edit and New buttons are redundant and don't have function:

[builder_view_form_settings.webm](https://user-images.githubusercontent.com/63108648/227607389-54ff2364-4649-4bd5-9db0-cbeb8d4ead46.webm)

**Comment by jam-py** [comment]
I fixed it
пт, 24 мар. 2023 г. в 21:16, crni_kaurin ***@***.***>:
