### ISSUE TITLE
V7: builder - clone_item btn and move up and down don't work

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#245]
Clone btn:

[builder_copy_item.webm](https://user-images.githubusercontent.com/63108648/227608178-e337d905-5aab-47e8-a768-c21d7b0927dd.webm)

**Comment by crnikaurin** [comment]
Move up and down btns:

[builder_move_up_down_btn.webm](https://user-images.githubusercontent.com/63108648/227608487-2a1d100d-78ce-4863-876b-4d8bcdcebb45.webm)

**Comment by jam-py** [comment]
Hi,

I fixed the copy button.
Can you check it?

Regards

пт, 24 мар. 2023 г. в 21:22, crni_kaurin ***@***.***>:

**Comment by crnikaurin** [comment]
Hi.

Clone button works.

Still the are move up and down buttons to fix.

**Comment by crnikaurin** [comment]
Move up and down buttons works but table don't refresh after that. I need to refreshe page in broswer to reolad data.
