### ISSUE TITLE
How to initialise a default view?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#25]
Hi Andrew, 

I can find a way to initialise a default page? For example, how was Demo->Invoices Master-Child view initialised as a default page?

Thanks

**Comment by jam-py** [comment]
There is on_page_loaded event handler in the task client module. It creates
dynamic menu and imitates clicking on menu buttons:

    $('#menu').children(":first").find('a').click();
    $('#submenu').children(":first").find('a').click();

But there is a more simple way. You can use the view method of an item.
For example, execute the following in the console to view customers data in
the demo:

task.customers.view($("#content"))

or

task.customers.view()

to view it in a modal form.﻿

The best


2017-03-30 9:46 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Thx, got it working.

I've built a first small app similar to Demo with sqlite3 DB and populated the rows with million records. The app is really fast, like lightening fast search through > million rows in a master-child view.

The DB is now 87Mb and growing as I still work on it. Shall we put the app somewhere for downloads?

**Comment by jam-py** [comment]
I don't know where to put it. My site is on a virtual hosting. I have
online demo on one of the Manuscript Solution servers, but I'm
uncomfortable asking them.
May be some time later.
I've made import for Oracle DB. Please test it when you have time.
To import tables create a new Item group and then set DB manual mode by
clicking on Database button (select Project node first).
Select the group. There will be an Import button at the bottom. Click it
and select a table to import. There will be a Generator name input to type
in sequence name.


2017-04-03 8:27 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Cool, thanks!

Will do and report back.

**Comment by dbabicwa** [comment]
I checked, can't find the Import button anywhere.

**Comment by jam-py** [comment]
Can you send me a screenshort of the Admin when the group that you want
import table to is selected?

2017-04-05 10:04 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Np, not sure if this is the one:
![image](https://cloud.githubusercontent.com/assets/9026100/24697143/a5cd2bc2-1a1e-11e7-947a-dd30131a5607.png)

**Comment by jam-py** [comment]
The DB manual mode must be set
http://jam-py.com/docs/admin/project/database.html

2017-04-05 11:41 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Yes, it is set, the snippet cut it, the screen is the same...

**Comment by jam-py** [comment]
What is the jam version?

2017-04-05 11:58 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by jam-py** [comment]
![version](https://cloud.githubusercontent.com/assets/9674777/24703074/477c63f8-1a0a-11e7-9ad8-5fe0bdb6b9da.png)

![import](https://cloud.githubusercontent.com/assets/9674777/24703136/9c03397e-1a0a-11e7-8f2d-58a6b4d5268c.png)

**Comment by dbabicwa** [comment]
Ahh, forgotten to install it :) Thank you Andrew!

**Comment by jam-py** [comment]
Unfortunately I did not think at once. Maybe the browser is caching. You can try press F12 in browser,
right click on the refresh and select empty cashe and hard reload

**Comment by jam-py** [comment]
It's OK

**Comment by dbabicwa** [comment]
Just imported Countries table from HR schema, and can update/insert/delete! Good
