### ISSUE TITLE
V7: running server.py on win 10 raise error, app cant start

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#255]
Traceback (most recent call last):
  File "C:\Users\Danijel Home\Downloads\test\server.py", line 4, in <module>
    from jam.wsgi import create_application
  File "C:\Users\Danijel Home\AppData\Local\Programs\Python\Python311\Lib\site-packages\jam.py-7.0.8-py3.11.egg\jam\wsgi.py", line 17, in <module>
    from werkzeug.wsgi import peek_path_info, get_path_info
ImportError: cannot import name 'peek_path_info' from 'werkzeug.wsgi' (C:\Users\Danijel Home\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug-2.3.3-py3.11.egg\werkzeug\wsgi.py)

**Comment by platipusica** [comment]
Hi Danijel
I commented line 17 and was able to start it.
![v7](https://user-images.githubusercontent.com/9026100/236679146-0fe827b6-a0fd-41b0-af84-3e0816b4a4ff.PNG)

**Comment by platipusica** [comment]
I am also able to Add/Remove the details on Windows.

**Comment by crnikaurin** [comment]
Hi Dražen and thanks.

But how this affect on other functionality of Jam?

**Comment by jam-py** [comment]
Hi, I corrected the code.Can you check it please?

вс, 7 мая 2023 г. в 21:53, crni_kaurin ***@***.***>:

**Comment by crnikaurin** [comment]
Hi Andrew. You fixed bug, thank you!
