### ISSUE TITLE
How to detach jam.js from layout?

### ISSUE THREAD

**Issue by svaraborut** [jam-py/jam-py#26]
Hi, I really like your work. The python backend is sweet and data interaction JS is well structured. I would like to use it for a project I'm working on; but reading jam.js file I noticed is tightly bound with tables, forms & fields. 

What I would like to do, is use my own template (JS code + html) to make view/edit forms, remove bootstrap-modal, replace bootstrap with a new one and use "Details" data to make custom tables and lists rendered with my template. 

How should I approach this with Jam.Py?

**Comment by jam-py** [comment]
Hi, you can specify templates for any forms in the templates div
of index.html and write you code in the item's events. As for boostrap, I
plan to replace it with a new one when I have time.

2017-04-07 16:47 GMT+03:00 svaraborut <notifications@github.com>:

**Comment by jam-py** [comment]
You asked a very important question, so I wrote a faq topic explaining it:
http://jam-py.com/docs/faq/faq_forms.html.
