### ISSUE TITLE
V7, Edit Form issues

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#264]
Looks like some issue but can't figure why different to Demo! Except, this App is using UTF8 chars, so the browser automatically
offered RTL. 
But only Forms with Tabs have issues!

How to debug this?

**Comment by platipusica** [comment]
Found it, this CSS code messes the Forms:
```
body {
  direction: rtl;
}
```
However, the rtl is needed :(

**Comment by platipusica** [comment]
Some examples:
https://getbootstrap.com/docs/5.0/getting-started/rtl/
https://getbootstrap.com/docs/5.0/examples/checkout-rtl/

**Comment by platipusica** [comment]
Demo the same issue:

![Screenshot from 2023-06-26 16-07-23](https://github.com/jam-py/jam-py/assets/9026100/3bc70222-19ab-49a7-880e-a95088697aa2)

CSS:
```
body {
  direction: rtl;
}
```
index:
<html lang="er" direction="rtl">

**Comment by platipusica** [comment]
Hi Andrew,
nothing to do with RTL, it is the TABS ! When Tabs on Customer do not exist, all is good:

![Screenshot from 2023-06-27 19-53-07](https://github.com/jam-py/jam-py/assets/9026100/c52ef96f-d8fa-40ba-897a-fa94de26712e)

**Comment by jam-py** [comment]
Hi, Drazen

Too much work right now.
I'll try to check it this week.

Regards,
Andrew

вт, 27 июн. 2023 г. в 14:53, platipusica ***@***.***>:

**Comment by platipusica** [comment]
HI Andrew, 

any updates on this? None of v7 Demo apps can use Tabs...

**Comment by platipusica** [comment]
Using:
<html lang="ar" dir="rtl">

Demo still has issue as on first Pic, V7.0.14

**Comment by jam-py** [comment]
Hi, Drazen

Can you explain briefly what the problem is.
Do you have any ideas on how to solve it?

I am sorry but I'm completely confused by all these photos, links and
messages.

Regards,
Andrew



вт, 8 авг. 2023 г. в 12:22, platipusica ***@***.***>:

**Comment by platipusica** [comment]
Fixed.

**Comment by platipusica** [comment]
Fixed.
