### ISSUE TITLE
Sharing my first project developed with jam-py:)

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#27]
Hi Andrew and everyone

I just updated the site with my latest project data developed with jam-py. Still WIP but if anyone is interested, here it is:

... (pls see below).

Over 1 million random records in Suppliers and Parts table, will try to populate other tables in a similar fashion. Also, might move this site to somewhere else so keep an eye on here. The App is read only, but you can search, etc...

Cheers

**Comment by dbabicwa** [comment]
Project:

[SimpleAssets_1.0.0_4.0.48_2017-04-03_15-24-39.zip](https://github.com/jam-py/jam-py/files/916426/SimpleAssets_1.0.0_4.0.48_2017-04-03_15-24-39.zip)

I'll add the DB as well, admin.sqlite and SimpleAssets.sqlite

**Comment by jam-py** [comment]
Hi, Dean.

Good work! 
May be to protect it? Anyone can go to Admin and remove database name and it won't work. 

How is the import for oracle DB?  

Cheers

**Comment by dbabicwa** [comment]
Thanks Andrew

not a problem, all is read only :)

Not at work this week, next week maybe.

D.

**Comment by dbabicwa** [comment]
Ah well, my cloud provider decided to terminate my instances, meaning lost this VM :(

**Comment by dbabicwa** [comment]
As promised, here is a small database and admin.sqlite.

Basically copy this into a new project and set the project DB to SimpleAssets.sqlite. Extract SimpleAssets_1.0.0_4.0.48_2017-04-03_15-24-39.zip into the project. Not tested yet.

[SimpleAssets.zip](https://github.com/jam-py/jam-py/files/941638/SimpleAssets.zip)
[admin.zip](https://github.com/jam-py/jam-py/files/941639/admin.zip)

**Comment by jam-py** [comment]
Thanks, I'll try.

2017-04-20 11:41 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Here is a screenshot, app developed with jam.py-4.0.48:

![jam_3](https://cloud.githubusercontent.com/assets/9026100/25320446/bbd86700-28d9-11e7-99fd-e78c6a19ec25.JPG)

**Comment by dbabicwa** [comment]
App updated to jam.py-4.0.70:

![jam_4](https://cloud.githubusercontent.com/assets/9026100/25652418/b4cfbe16-301a-11e7-9ba8-ea3247e6ab4d.png)
![jam_5](https://cloud.githubusercontent.com/assets/9026100/25652423/b898faf8-301a-11e7-95c0-2d4b103d5443.JPG)


Note the number of Parts pages! The search will now work across the database and is extremely fast.

**Comment by dbabicwa** [comment]
Hi Andrew and others :)

I have a problem with the above demo after moving to v4.0.72 (and updating JS, etc) which I can't figure out why is happening.
Basically on a form with a Currency field (Journals\Assets with Parts), after I type any number in Quantity I get the message "...must be an integer". The opposite for Price "..must be a currency":
![screenshot from 2017-05-20 20 41 45](https://cloud.githubusercontent.com/assets/9026100/26276184/d3c6d6a0-3da4-11e7-94c1-8a8c3f57a4d3.png)

Here is the updated project:

[admin.sqlite_SimpleAssets_1.0.4_4.0.72_2017-05-20_20-32-53.zip](https://github.com/jam-py/jam-py/files/1016191/admin.sqlite_SimpleAssets_1.0.4_4.0.72_2017-05-20_20-32-53.zip)
[SimpleAssets_1.0.4_4.0.72_2017-05-20_20-32-53.zip](https://github.com/jam-py/jam-py/files/1016192/SimpleAssets_1.0.4_4.0.72_2017-05-20_20-32-53.zip)

The database is posted above, and the procedure how to recreate the project.

Cheers

**Comment by dbabicwa** [comment]
Created Dashboard:
![screenshot from 2017-05-21 21 49 33](https://cloud.githubusercontent.com/assets/9026100/26284519/c261686e-3e6f-11e7-8700-4019b98ed69b.png)

Also, found a bug with deleting Journals/Assets with Parts.

**Comment by jam-py** [comment]
Hi, Dean

There are some errors in your project:

1. in the assetsparts.asset_parts detail client module insted of
lookup_item.unit_price.value should be lookup_item.price.value:

function on_field_changed(field, lookup_item) {
var item = field.owner;
if (field.field_name === 'quantity' || field.field_name === 'unit_price') {
item.owner.calc_total(item);
}
else if (field.field_name === 'part' && lookup_item) {
item.quantity.value = 1;
item.unit_price.value = lookup_item.price.value;
}
}

2 in the assetsparts client module insted of  unitprice should be
unit_price:

    function calc_total(item) {
        item.amount.value = item.round(item.quantity.value *
item.unit_price.value, 2);
        item.gst.value = item.round(item.amount.value *
item.owner.gstrate.value / 100, 2);
        item.total.value = item.amount.value + item.gst.value;
    }

And I reworked the exception handling when inplace editor is used so
developer can find the reson of an error.
It will be in the next realse.

By the way demo is using Chart.js library: http://www.chartjs.org/, that
can be used to create any kind of charts.

Regards,
Andrew

**Comment by dbabicwa** [comment]
Thanks Andrew, 

as always very helpful and this fixed it.

The Deletion of Journals/Assets with Parts is an interesting one. It looks like if I remove the column Categories from the Tables parts_table, I can delete in Journals. 
However, if not deleted, it does not work. 

This is interesting because on Journals delete master record, it is failing with "Error: no such column: SIMPLEASSETS_ASSET_PARTS.CATEGORY" - but the column is there!

To repeat:
- download the above latest zips, try to delete one Master record. It will fail. Delete Category column in the Child table (parts_table). Now delete the Master record and it works.

Now, if I add Category column again with all lookups, it is not showing on Journals and can delete records.

Interesting:

- looks like if I delete only Product column it will delete records even though Category is there!

Again, if I add Product column again with all lookups, it is not showing on Journals and can delete records.

Something is not right.  Hope my findings helps!

Cheers

**Comment by dbabicwa** [comment]
Found it!

Setting the Order on Details (or former Tables) for a table WILL prevent deleting Master records in Journals view on this application!

**Comment by dbabicwa** [comment]
Fixed and updated project:


[admin.sqlite_SimpleAssets_1.0.5_4.0.72_2017-05-23_15-44-55.zip](https://github.com/jam-py/jam-py/files/1021367/admin.sqlite_SimpleAssets_1.0.5_4.0.72_2017-05-23_15-44-55.zip)
[SimpleAssets_1.0.5_4.0.72_2017-05-23_15-44-55.zip](https://github.com/jam-py/jam-py/files/1021368/SimpleAssets_1.0.5_4.0.72_2017-05-23_15-44-55.zip)

The database is posted above, and the procedure how to recreate the project. 
![jam_6](https://cloud.githubusercontent.com/assets/9026100/26344586/c8143a5c-3fd2-11e7-8ab1-3ca9219f5ed3.JPG)

**Comment by dbabicwa** [comment]
HI Andrew, 

the above import does not work with v5.1.1
Steps: download the above DB and export, create a new project, set the DB to SimpleAssets.sqlite. import. 
Master-child failing with:
Uncaught TypeError: Cannot read property 'create_table' of undefined

Dean

**Comment by dbabicwa** [comment]
[test_1.0.0_5.1.1_2017-12-13_16-18-23.zip](https://github.com/jam-py/jam-py/files/1554695/test_1.0.0_5.1.1_2017-12-13_16-18-23.zip)

**Comment by jam-py** [comment]
Hi, Dean

Add the following line to the shared on_edit_form_created 

item.shared_groups.open();

or add to this module the following code:

var ScrollTimeOut;

function on_after_scroll(item) {
    clearTimeout(ScrollTimeOut);
    ScrollTimeOut = setTimeout(
        function() {
            item.shared_groups.open(true);
        },
        100
    );
}

I am working on wizards that will help to avoid such problems.

Andrew

**Comment by dbabicwa** [comment]
Thanks Andrew
the code fixed test_1.0.0_5.1.1_2017-12-13_16-18-23.zip

It did not fix the above imported project, and not seeing data. But if I set the filter, than I see it but not the details.

**Comment by jam-py** [comment]
The error in the line
item.parts_table.create_table(
is due to renaming 'assetsparts' detail 'parts_table' to 'asset_parts'.
Change this line to
item.asset_parts.create_table(

**Comment by dbabicwa** [comment]
Cheers, will have a look.

**Comment by platipusica** [comment]
Update project to 5.4.11, working well with above SimpleAssets.zip database.

[SimpleAssets_1.0.6_5.4.11_2018-06-13_21-46-56.zip](https://github.com/jam-py/jam-py/files/2098347/SimpleAssets_1.0.6_5.4.11_2018-06-13_21-46-56.zip)
