### ISSUE TITLE
Please update bootstrap

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#283]
Hi,
It looks like the bootstrap version is quite old, v2.3.2, while the current one is v5.
I would be thankful if you could update it, it would go a long way in improving the looks of the UI.

**Comment by platipusica** [comment]
Check the devel branch.
It is all there ;)

**Comment by ddavidebor** [comment]
Fantastic. Is it advisable to switch? I see master has 100+ commits that are not in develop, it seems the to branches are running in parallel. Are there any major features not in develop, or any major incompatibility?

**Comment by platipusica** [comment]
Not ready yet.

**Comment by ddavidebor** [comment]
Allright, really looking forward to it!

**Comment by platipusica** [comment]
:)
The current v5 is quite capable tho. I would suggest to get going with the
project since might be a while due to holiday season.
