### ISSUE TITLE
v7 login.html and custom changes (branding?)

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#284]
Hi Andrew,

I noticed ..../lib/python3.8/site-packages/jam/html/login.html

How to apply custom branding and message like this:

https://sem.pythonanywhere.com/

Will login.html in app folder take over this one? 

Thanks

**Comment by crnikaurin** [comment]
Yes, I also have same question. What about reset password button on login form.

It would be usefull to show error on login faliure.

**Comment by crnikaurin** [comment]
Solved: https://groups.google.com/g/jam-py/c/DwALkbBsFcw
