### ISSUE TITLE
Reports enhancement: remove column

### ISSUE THREAD

**Issue by crnikaurin** [jam-py/jam-py#288]
Hi Andrew.

I think that would be useful if we can remove for example 'A' column in report with on_parsed event. First column sometimes needs to be completely removed so users don't need to remove it manually later.

**Comment by crnikaurin** [comment]
Best option is to use jam reports for specific pdf reports and export xlsx with pandas code

**Comment by Nurb432** [comment]
Happen to have an example of doing the export with pandas from within the system?

**Comment by platipusica** [comment]
https://sem.pythonanywhere.com/
Journals/Sales Order - Export csv

**Comment by Nurb432** [comment]
thank you.  Id rather do this than trying to do it via libreoffice templates.

**Comment by platipusica** [comment]
Export to csv via Libreoffice? No need for LO to do that.

**Comment by Nurb432** [comment]
> Export to csv via Libreoffice? No need for LO to do that.

That is the only way i saw so far was to create a report.  I guess i need to read more then.

**Comment by platipusica** [comment]
The csv export with pandas has nothing with reports templates tho.
One way to export is with no pandas at all:
https://jampyapplicationbuilder.com/docs/how_to/export_import_csv_files.html?highlight=csv

**Comment by Nurb432** [comment]
> The csv export with pandas has nothing with reports templates tho.

ya i knew that.  But ill check out both options. using LO is overkill for simple user spawned exports so having another way, is great. Thanks much.
