### ISSUE TITLE
How to integrate Help tab?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#29]
Hi Andrew,

sorry to bug you, but this might be obvious for you and maybe not so much for others :)
I am trying to understand how to make Help tab in some efficient way, lets say something like About on Demo.
For example, with a links from Table of Content, etc. Like from here: 
[SimpleAssets](http://simpleassets.sourceforge.net/simpleassets/index.php?action=help)

I will try to move the above app to jam-py...

Thanks

**Comment by jam-py** [comment]
Hi,

If you using default menu on on_page_loaded, then

$("#menu").append($('<li><a href="
http://simpleassets.sourceforge.net/simpleassets/index.php?action=helpversion"
target="_blank">Help</a></li>'));

see in demo

$("#menu").append($('<li><a href="http://jam-py.com/"
target="_blank">Jam.py</a></li>'));

**Comment by dbabicwa** [comment]
Ah, yes, I do know that.

I was more interested in making a Help as ie About, but not referencing external pages at all. So I did add almost everything in index.html using <h3> etc, but does not look good...
So what's the better way? Making a static help.html page and linking as above, or...

**Comment by jam-py** [comment]
You can try to do this way

    $("#menu").append($('<li></li>').append($('<a
href="#">Help</a>').click(function(e) {
        e.preventDefault();
        task.message(
            $('<iframe src="
http://simpleassets.sourceforge.net/simpleassets/index.php?action=help"
name="help" style="width: 100%; height: 100%"></iframe>'),
            {title: 'Help', margin: 0, width: $(window).width() - 50,
height: $(window).height() - 100}
        );
    })));

**Comment by dbabicwa** [comment]
Cheers for that!
Will try do demonstrate tomorrow, it's not about external sources but integrated Help in the app. Like, how would you do it? :)

**Comment by dbabicwa** [comment]
Something like this. At the moment, this is in index.html which I think is ugly but have no idea how to make it better :(

![jam_3](https://cloud.githubusercontent.com/assets/9026100/25320356/e69f699e-28d8-11e7-95ef-600d763b3307.JPG)

**Comment by jam-py** [comment]
Try to remove text_center: true from task.message and you can use css to
format the html.

As for the search it is very slow for such tables it's better to use
filters and create indexes for them

Regards

2017-04-24 5:31 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Cool, thx, will do!
