### ISSUE TITLE
Method with existing database ?

### ISSUE THREAD

**Issue by fliot** [jam-py/jam-py#299]
This is clearly not an issue, but a question,
I well understood how to create up scratch new tables, and foreign keys, etc,
But it is possible to "import" table structure, if this table (or a full schema) already exist into the database ?
Thanks in advance.

**Comment by platipusica** [comment]
https://msaccess.pythonanywhere.com/
Click  on About, video...

**Comment by platipusica** [comment]
Or:
https://jam-py.com/docs/admin/intergation_with_existing_database.html

**Comment by fliot** [comment]
Fabulous,
Great thanks
