### ISSUE TITLE
Pip needs updating

### ISSUE THREAD

**Issue by Kentoseth** [jam-py/jam-py#3]
Latest package is said to be 1.0.7 on Pip, see here:

https://pypi.python.org/pypi/jam.py/1.0.7

Please update it to 1.0.8

**Comment by jam-py** [comment]
I updated jam.py to latest version 2.01.


2015-06-05 3:55 GMT+03:00 Moe <notifications@github.com>:

**Comment by Kentoseth** [comment]
Thanks. Closing issue.
