### ISSUE TITLE
Let's put Oracle issues in here?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#30]
As promised, I've done some initial tests with Oracle tables import.
Imported the table and can see the content. The table has 42Mil rows, 17 columns:

![rhnpackagefile](https://cloud.githubusercontent.com/assets/9026100/25220847/a977d4ac-25e5-11e7-9b44-47ac80368b5f.JPG)

# 1:
Now trying to search. Looks like index.html must be updated as per catalogs-view/search example. Did that but no luck. The App just exits after pressing enter in a search filed with a brief "Server error message" (I think coz very fast and can't see it), and than showing initial App view. No errors in the log file.
The search filed is marked as default/required. Primary filed is package_id.

Cheers

**Comment by jam-py** [comment]
Are there some errors on the server side?

**Comment by dbabicwa** [comment]
No errors anywhere...I'll do more tests tomorrow tho, so not to worry, might be some simple fix...

**Comment by dbabicwa** [comment]
Yes, I see the screen msg now, it says 'Server request error' briefly and goes into the default view. As a test, I created sqlite new Item and a table, search works well. So only Oracle imported table not working I think.

**Comment by dbabicwa** [comment]
Confirmed issue with Search and newly created Item and a small table on local Ora instance.

**Comment by dbabicwa** [comment]
[admin.zip](https://github.com/jam-py/jam-py/files/946220/admin.zip)
[test_ora_search_1.0.0_4.0.68_2017-04-21_14-56-23.zip](https://github.com/jam-py/jam-py/files/946221/test_ora_search_1.0.0_4.0.68_2017-04-21_14-56-23.zip)

Here is the export. it is using HR schema provided by default with XE.

**Comment by jam-py** [comment]
Dean, You created a satellite group, but it doesn't have a search
functionality that is defined in client module of the catalogs group.

To add it, selects Groups node in project tree, click on satellite and then
on Client module button. In the editor
type in the following code:

function on_view_form_created(item) {
    item.task.catalogs.on_view_form_created(item);
}

Regards

**Comment by dbabicwa** [comment]
Ok, thanks for looking into this. I did add as you suggested and Search does work on a small table, ie the one in above zip.
But, with huge table 42mil rows, the Search hangs, as per below. It might be timeout related or something, duno, not many will have that big tables and I don't expect this in production, just a thought of scaling the app :)
As you can see below, there are 2mil pages, which is a lot, and it takes about 30-40secs to open a second page. 

![screenshot from 2017-04-23 21 17 49](https://cloud.githubusercontent.com/assets/9026100/25313863/8ca23b24-286a-11e7-8aee-d8b8b4c26e93.png)

So I think number 1. is solved, let's see whet else I'll find in next few days :+1:
