### ISSUE TITLE
V5 and v7 MSSQL error with lookup field

### ISSUE THREAD

**Issue by caccia86** [jam-py/jam-py#304]
Hi,
I'm working with a MSSQL database and in my project I also use a lookup field. I encount a problem with the filter function avaible in jam.py interface.
The error it's show below:

![image](https://github.com/jam-py/jam-py/assets/148060442/af48d2f3-52b6-4a41-87cb-7fc2b7e9366c)

![image](https://github.com/jam-py/jam-py/assets/148060442/aa79a595-b20a-48ae-90e5-2e71dc865565)

![image](https://github.com/jam-py/jam-py/assets/148060442/35aa35b8-c7ec-4ee8-9cc0-710502fe30cb)
 
With the SQL profiler I saw an incorrect query and I report it below:
```
SELECT b."id",
       b."deleted",
       b."campo2",
       b."descr",
       campo2_lookup
FROM   (SELECT "test_tabella_slave"."id",
               "test_tabella_slave"."deleted",
               "test_tabella_slave"."campo2",
               "test_tabella_slave"."descr",
               TEST_TABELLA_MASTER_10."campo1"         AS CAMPO2_LOOKUP,
               Row_number()
                 OVER (
                   ORDER BY "test_tabella_slave"."id") AS RowNum
        FROM   "test_tabella_slave" AS "TEST_TABELLA_SLAVE"
               LEFT OUTER JOIN "test_tabella_master" AS TEST_TABELLA_MASTER_10
                            ON "test_tabella_slave"."campo2" =
                               TEST_TABELLA_MASTER_10."id"
        WHERE  Cast(Cast(TEST_TABELLA_MASTER_10."campo1" AS DECIMAL(20, 10)) AS
                    VARCHAR
                    (20))
               LIKE '%sda%'
               AND "test_tabella_slave"."deleted" = 0) AS b
WHERE  rownum >= 1
       AND rownum < 24
ORDER  BY rownum 
```

I think the problem is this istruction 

> WHERE  Cast(Cast(TEST_TABELLA_MASTER_10."campo1" AS DECIMAL(20, 10)) AS VARCHAR (20))

For the MSSQL databases it could be necessary to fix the convert_like function.
Thanks in advance.

**Comment by platipusica** [comment]
I concur with this, reported here as well:

https://groups.google.com/g/jam-py/c/oH36stjvtMk

**Comment by platipusica** [comment]
Merged, please test.
Thanks
