### ISSUE TITLE
Virtual table example or...?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#31]
Hi Andrew, 

I am a fan of real app examples so sorry if asking to many questions. The idea is to build a few apps and publish it so people can run it and study, built more and share :) Eventually.

So, one question comes to my mind: how to use a virtual table? Or, is a virtual table a proper way for doing this:
- on demo, how to do it if we want to see Albums or Artists in Journals (or somewere else), sold to Customers? So direct opposite to Demo Invoices and since this information is already there in the underlying tables, in theory we should not need any new tables created.  For example, let's show Albums **sold** (or Artists) with number of sold Tracks, Total, etc. with the child table Customers. I think this might be a Report, but report is not searchable...We do have a number of Tracks sold already, the question is to which Customer :)

Cheers

Dean

**Comment by jam-py** [comment]
Hi Dean,

The good question. I'll try to do this type of item in the next release.

When a virtual table flag is set the item doesn't have a database table. This can be used when you need
some structures for editing or displaying some table. This way the View Dialog is done in Administrator.

**Comment by dbabicwa** [comment]
Hi Andrew, 
how is this going? Would you be able to provide an example with doing this?

Thanks!

**Comment by jam-py** [comment]
Hi, Dean
I made a lot of changes including this. I am testing now. I will try to
post new version today.

Cheers


2017-05-10 7:36 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Heya

still trying to figure out a virt table :) Created Journal and Details virt table, added one filed into both referencing Asset and Part as INT.
Than created client_module for Journal such as:
`function on_view_form_created(item) {

    var height = $(window).height() - $('body').height() - 200 - 10;
    
    if (height < 200) {
        height = 200;
    }
    show_parts(item);
    
    item.selections = [];    
    
    item.create_table(item.view_form.find(".view-master"), {
        height: height,
        sortable: true,
        show_footer: true,    
        row_callback: function(row, it) {
            var font_weight = 'normal';
            if (it.total.value > 10) {
                font_weight = 'bold';
            }
            row.find('td.total').css('font-weight', font_weight);
        }
    });    

    if (item.can_delete()) {
        item.view_form.find("#delete-btn")
            .off('click.task')
            .on('click', function() { delete_records(item) } );
    }
    
    item.parts_table.create_table(item.view_form.find(".view-detail"), {
            height: 200 - 4, 
            dblclick_edit: false, 
            column_width: {'parttag': '10%'}
    });
    
    item.open(true);
}
function show_parts(item) {
    var parts = item.task.assetsparts.copy()
    parts.open(
        {
            fields: ['asset']
        }
    )
}
`

Any ideas how to proceed?

**Comment by jam-py** [comment]
Hi, Dean

When you create an item with the virtual_table attribute set to true, the
Admin doesn't create a table in the project database.

Such items can be used in the following way.

1. First of all you have two modules - on the server and on the client. You
can use them to defined some functions, this functions could be accessed in
other modules of the project.
So, for example, if you create a lib item and define a function
do_something in its client module

function do_something(item) {
   ...// some code
}

this function can be accessed in other modules via task attribute of the
item (you can define any arguments for this functions):

item.task.lib.do_something(item)

This is works the same way on the server. Please note, that on the client
you have to load the module first, when the Dynamic JS modules loading
attribute in the project parameters is set.


2. You can use a default html templates or define new ones, to create
forms. This way the dashboard of the demo works.


3. You can add field to such item and add the records dynamiclly on the
client. For example, you can create an email item with name, email and mess
fields. Then you can add Send email button to the customers view form and
use the following code in the customers client module:

function on_view_form_created(item) {
    //... some code here
    item.view_form.find('#email-btn').click(function() {
        item.task.email.open({open_empty: true});
        item.task.email.append_record();
    });
}

When user clicks this button, a new record will be appended to the email
item dataset and an edit form of the email will be created. You don't have
to create inputs, check if values are filled in and so on. I am writing
such example in the demo app now.

You as well can add several records to the item dataset. That will be
displayed when you create a table using create_table method.

item.open({open_empty: true});
for (var i = 0; i < 10; i++) {
    item.append();
    item.some_field.value = 'record '+ i;
    item.post();
}

In the Admin this is used in view, edit, order, detail dialogs.


4. If you have some external database you can create an virtual_table item
with the same fields as in this database table and the same table name, and
then write the on_open event handler in the server module (for sqlite db):

import jam.db.db_modules as db

def on_open(item, params):
    item = item.copy()
    res = []
    mess = ''
    sql = item.get_select_statement(params, db.get_db_module(db.SQLITE))
    try:
        connection = sqlite3.connect(db_path) // path to sqlite db
        cur = connection.cursor()
        cur.execute(sql)
        res = cur.fetchall()
    except Exception, e:
        print ('%s: on_open error %s') % (item.item_name, e.message)
    finally:
        if cur:
            cur.close()
        connection.close()
    return res, mess

this code will generate the sql query for this db table the same way as for
project db and return dataset that will be displayed on the client

You have to create a group for this item without common fields.

Kind regards,
Andrew


2017-05-26 11:12 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Ok, will try!

Thanks
