### ISSUE TITLE
v4.0.72 weird behaviour with FF on Admin/Groups

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#32]
Hi there

congrats on ver 72, looks great!

I noticed some weird behaviour with Firefox (51.0.1 Linux, 52.0.2 Win) on Admin/Groups/Catalogs/Etc. When trying to move an item down/up, the scrolling movement is pretty hectic :)

Not a big deal tho.

Cheers

**Comment by dbabicwa** [comment]
Just checked, still issue in 4.0.78

**Comment by jam-py** [comment]
I see will correct it in the next release.


понедельник, 5 июня 2017 г. пользователь dbabicwa написал:

**Comment by jam-py** [comment]
I have corrected this behaviour. I will publish in the next release.
