### ISSUE TITLE
can jam-py be used as a module/plugin in other python web frameworks?

### ISSUE THREAD

**Issue by LeiYangGH** [jam-py/jam-py#324]
such as djiango or flask.
i want to reuse the existing authentication in flask, and also like the great job jam-py does.

**Comment by platipusica** [comment]
Thanks for the question.
Jam.py IS a framework, just like Flask/Django is.
The Auth for Flask in general should work for Jam but must be customized FOR  Jam.
If OAuth is used for Flask app, nothing is stopping the developer to add a new app for Jam, like in here:
https://ipam2.pythonanywhere.com/

BR
