### ISSUE TITLE
possible to set root path for reverse proxy?

### ISSUE THREAD

**Issue by LeiYangGH** [jam-py/jam-py#326]
i'm newbie and following basic totorial https://jam-py.com/docs/intro/new_project.html, and https://jam-py.com/docs/how_to/deploy/index.html.

i have (nginx) reverse proxy to handle ssl, etc, and already have several applications running behind my website at different root paths.
it it possible to let jam-py run at a customized root path, such as `/jam`? so i can just add it to proxy without impacting existing applications.

**Comment by platipusica** [comment]
I can't see why not.
I would suggest searching here, ie:
https://github.com/jam-py/jam-py/issues/67

**Comment by LeiYangGH** [comment]
thanks, but the example in that issue is  writing ` location / {`, which implies jam is on the root `/`.

**Comment by platipusica** [comment]
Ok,

so why not changing it to /xyz?

Does reverse proxy care? The problem would be /static content, not Jam.

**Comment by LeiYangGH** [comment]
yes, `/static` is one of the problematic path, can it be solved without complex rewrite rules?

**Comment by platipusica** [comment]
That depends on what /static is used for.

Maybe Nginx is not the right server.

We well know how to configure Apache not to mount it to /root. If Nginx has
issue with that, thats a question for them I think.

Cheers

**Comment by LeiYangGH** [comment]
can you just show how to configure jam to `127.0.0.1:8080/jam` in apache?

**Comment by platipusica** [comment]
I would suggest to actually start using the framework to find if is right for the job at hand.

Again, please search here for Apache:
https://github.com/jam-py/jam-py/issues/35

The WSGIScriptAliasMatch is what is used for non root.
 >400 apps are hosted this way.
But that is advanced setup.

**Comment by LeiYangGH** [comment]
thanks! though the apache setup mainly introduces how to configure two jams in two server domains(which is impossible for me), i'm not going to argue it anymore.
indeed, i think jam.py is great work and want to use it, while i'm developing with existing database and found there are pretty much things to configure(when importing some tables, some datatypes(e.g. TINYINT) doesn't have built in support, and column name conflicts with the framework(e.g. active), maybe i found the wrong tool for my business... 
thank you for your time!

**Comment by platipusica** [comment]
> thanks! though the apache setup mainly introduces how to configure two jams in two server domains(which is impossible for me), i'm not going to argue it anymore. indeed, i think jam.py is great work and want to use it, while i'm developing with existing database and found there are pretty much things to configure(when importing some tables, some datatypes(e.g. TINYINT) doesn't have built in support, and column name conflicts with the framework(e.g. active), maybe i found the wrong tool for my business... thank you for your time!

Nah, column name does not conflicts at all. Tinyint is not supported on all databases, and to be fair Jam does not care. It is the FrontEnd which cares, so you force the business rule ;)

**Comment by platipusica** [comment]
To demonstrate:
https://resourcingandbilling.pythonanywhere.com/
Select Analyst, you'll see Active column. As well as on Clients, etc..

Good luck.

**Comment by LeiYangGH** [comment]
thanks! the demo looks really fascinating, deserve more learnings ^_^
