### ISSUE TITLE
Apache deployment 101.

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#35]
Hi everyone,

in the next few days I'll try to explain how to deploy jam-py app at Linux Apache http server. This will be a simple, one app deployment, not covering multi hosted ISP environment. So basically deploying straight into the ie an cloud server with open 22, 80 and 443 port.

Prerequisite is a signed certificate for the DNS server name (YOUR_SERVER DNS entry from below). One can use a self signed, etc, not covering those. Also, Python installed and sudo access (or root for Linux). I have no idea at all about the MS Servers, sorry.

Regards

Dean

PS
Opened trail Google cloud account.

**Comment by dbabicwa** [comment]
The https server is up and running!

https://jam.research.uwa.edu.au/

The App is in read only mode. You can access admin.html page, but can't change anything. 

Took me some fiddling with Google Cloud server, this is a micro Ubuntu instance, plain apache2 install with apt-get.

- install wsgi module for Apache
apt-get install libapache2-mod-wsgi

- enable ssl, wsgi module for apache:
a2enmod 
ssl wsgi

- create a custom file for jam-py app, ie /etc/apache2/sites-enabled/test.conf, for example (still wip)
`<IfModule mod_ssl.c>
<VirtualHost YOUR_IP:443>

    ServerName YOUR_SERVER
    ServerAlias
    ServerAdmin YOUR_EMAIL
                ErrorLog ${APACHE_LOG_DIR}/test-error-sec.log
                CustomLog ${APACHE_LOG_DIR}/test-access-sec.log combined
   #below is for cx_Oracle
    SetEnv LD_LIBRARY_PATH /u01/app/oracle/product/11.2.0/xe/lib
    SetEnv ORACLE_SID XE
    SetEnv ORACLE_HOME /u01/app/oracle/product/11.2.0/xe
   # finish cx_Oracle
    DocumentRoot /var/www/html/simpleassets
    SSLEngine on
    SSLCertificateFile  "/etc/ssl/private/your.crt"
    SSLCertificateKeyFile  "/etc/ssl/private/your.key"
    SSLCertificateChainFile "/etc/ssl/private/your_chain.crt"
    SSLCACertificateFile   "/etc/ssl/private/your_CA.crt"

    WSGIDaemonProcess  web user=www-data group=www-data processes=1 threads=5
    WSGIScriptAlias / /var/www/html/simpleassets/wsgi.py
    #WSGIProcessGroup  web

        <Directory /var/www/html/simpleassets>

        #WSGIProcessGroup web
        Options ExecCGI
        SetHandler cgi-script
        AddHandler cgi-script .py

        Order deny,allow
        Allow from all
        Require all granted
        <Files wsgi.py>
            Order deny,allow
            Allow from all

            # comment the following for ubuntu <13
            Require all granted
        </Files>

    </Directory>

    <Directory /var/www/html/simpleassets/static>

        WSGIProcessGroup web
        Options +ExecCGI
        AddHandler cgi-script .py
        Order deny,allow
        Allow from all

        # comment the following for ubuntu < 13
        Require all granted

    </Directory>

</VirtualHost>
</IfModule>
`

- I created /var/www/html/simpleassets folder where unzipped jam-py SimpleAssets project. The /var/www/html is the default Ubuntu folder for serving web pages. Install jam-py as usual.

- change ownership for your desired folder, ie for /var/www/html/simpleassets is:
`chown -R www-data:  /var/www/html/simpleassets`

- you are ready to go! Enable test.conf with:
`a2edsite test
systemctl restart apache2`






Regards

Dean

**Comment by dbabicwa** [comment]
Now, here is the question of how to run TWO jam-py instances on one https server?

Easy. 

One possible answer to this problem is the DNS. You might decide to set your DNS to ie second_instance.YOUR_SERVER name.
So the above test.conf file would be almost the same except YOUR_SERVER is now called second_instance.YOUR_SERVER

The /etc/apache2/sites-available/test3.conf file:

`<IfModule mod_ssl.c>
   <VirtualHost YOUR_IP:443>

    ServerName second_instance.YOUR_SERVER
    ServerAlias
    ServerAdmin YOUR_EMAIL
    ErrorLog ${APACHE_LOG_DIR}/test3-error-sec.log
    CustomLog ${APACHE_LOG_DIR}/test3-access-sec.log combined
    #below is for cx_Oracle
    SetEnv LD_LIBRARY_PATH /u01/app/oracle/product/11.2.0/xe/lib
    SetEnv ORACLE_SID XE
    SetEnv ORACLE_HOME /u01/app/oracle/product/11.2.0/xe
    #finish cx_Oracle
    DocumentRoot /var/www/html/simpleassets3
    SSLEngine on
    SSLCertificateFile  "/etc/ssl/private/your.crt"
    SSLCertificateKeyFile  "/etc/ssl/private/your.key"
    SSLCertificateChainFile "/etc/ssl/private/your_chain.crt"
    SSLCACertificateFile   "/etc/ssl/private/your_CA.crt"

    WSGIDaemonProcess  assets3 user=www-data group=www-data processes=1 threads=5
    WSGIScriptAlias / /var/www/html/simpleassets3/wsgi.py
        <Directory /var/www/html/simpleassets3>

        Options +ExecCGI
        SetHandler wsgi-script
        AddHandler wsgi-script .py

        Order deny,allow
        Allow from all
        Require all granted
        <Files wsgi.py>
            Order deny,allow
            Allow from all

            # comment the following for ubuntu <13
            Require all granted
        </Files>

    </Directory>

    <Directory /var/www/html/simpleassets3/static>

        # comment the following for ubuntu < 13
        Require all granted

    </Directory>

    </VirtualHost>
</IfModule>
`

The jam-py application second_instance is now in ie /var/www/html/simpleassets3, and WSGIDaemonProcess is adjusted to new daemon, called assets3

**Comment by dbabicwa** [comment]
I updated the server with above configuration files and https://jam2.research.uwa.edu.au is now running with different application.

As mentioned, the only difference in this two configuration files are:
diff /etc/apache2/sites-available/test.conf /etc/apache2/sites-available/test2.conf
4c4
<     ServerName jam.research.uwa.edu.au
---
>     ServerName jam2.research.uwa.edu.au
7,8c7,8
<                 ErrorLog ${APACHE_LOG_DIR}/test2-error-sec.log
<                 CustomLog ${APACHE_LOG_DIR}/test2-access-sec.log combined
---
>                 ErrorLog ${APACHE_LOG_DIR}/test-error-sec.log
>                 CustomLog ${APACHE_LOG_DIR}/test-access-sec.log combined
19,20c19,20
<     WSGIDaemonProcess  web2 user=www-data group=www-data processes=1 threads=5
<     WSGIScriptAlias / /var/www/html/demo/wsgi.py
---
>     WSGIDaemonProcess  web user=www-data group=www-data processes=1 threads=5
>     WSGIScriptAlias / /var/www/html/simpleassets/wsgi.py

I think www-data is not really needed, but will leave here as a reference.

**Comment by dbabicwa** [comment]
One thing though, the Google Cloud instance changes the external facing IP on every reboot, hence the above links will go away if I don't update the DNS. That is life - C'est la vie.

**Comment by platipusica** [comment]
Please note, 
one can have a number of different virtualenv Python installations and Jam.py versions, for example :
```
    WSGIApplicationGroup %{GLOBAL}
    #WSGIDaemonProcess prod user=www-data group=www-data processes=1 threads=1
    WSGIDaemonProcess prod1 python-home=/var/www/html/redmuch/jam-prod python-path=/var/www/html/redmuch/jam-prod/lib/python3.8/site-packages:/var/www/html/redmuch user=www-data group=www-data processes=1 threads=1
 WSGIProcessGroup prod1
    WSGIScriptAlias / /var/www/html/redmuch/wsgi.py
```

The important part is WSGIProcessGroup and python-path to point at correct Python virtualenv, in this case jam-prod created with:
```
python3 -m venv jam-prod
```

**Comment by platipusica** [comment]
It is possible to have a wildcard Apache configuration for any Jam application in virtualenv. For example, having /var/www/jam/jam/$1/wsgi.py in the config file will use $1 variable as folder name provided in the link and regex /([^/]+) will map variable to a folder.
Virtual Python is installed in /var/www/demo/jam-dev

```
UseCanonicalName Off
<VirtualHost *:80>
        ServerName YOUR_SERVER
        ServerAlias *.YOUR_SERVER

WSGIApplicationGroup %{GLOBAL}
WSGIDaemonProcess  demo  lang='en_US.UTF-8' locale='en_US.UTF-8' python-home=/var/www/demo/jam-dev python-path=/var/www/demo/jam-dev user=www-data group=www-data processes=1 threads=5
WSGIProcessGroup demo
WSGIScriptAliasMatch /([^/]+) /var/www/jam/jam/$1/wsgi.py

<Directory "/var/www/jam/jam/.*">
        Options +ExecCGI
        SetHandler wsgi-script
        AddHandler wsgi-script .py
        Order deny,allow
        Allow from all
        Require all granted

       <Files wsgi.py>
            Order deny,allow
            Allow from all

            # comment the following for ubuntu <13
            Require all granted
        </Files>

</Directory>
</VirtualHost>
```

**Comment by platipusica** [comment]
Update for jammy jellyfish ubuntu, it needs 

```
WSGIApplicationGroup %{GLOBAL}
```
in the above VirtualHost.
