### ISSUE TITLE
Demo app :: Filter by customers doesn't writing selected customer

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#38]

**Comment by dbabicwa** [comment]
v4.0.78 I assume? 
Tested this on Invoices, the Filter is showing for example: "Customer: selected:2 " - if you select 2 customers, and this is working well. 
I can't reproduce this. Rad please add your steps to reproduce.

Thx

**Comment by jam-py** [comment]
Hi,

About searching on  an integer field. The search is done in the cutalogs
client module and uses search method that has a search type parameter. For
integer fields it is set to "eq". That is this is exact search. This method
is not documented yet.

As for emails, this is just an example. You can implement whatever
fuctionality you need.

I am on avacation until 14. It is not very convinient to send messages for
me now.

Kind regards,
Andrew

пятница, 9 июня 2017 г. пользователь dbabicwa написал:

**Comment by rrad0812** [comment]
Sorry, but I for me was selected:%d. ( v 4.0.78 )
Today that is OK, selected:2
Memory leakage ???
