### ISSUE TITLE
Demo app :: Don't do 'Send mail' on next to level ( when drop in customer lookup )

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#39]

**Comment by dbabicwa** [comment]
Hi Radosav, 

you mean not to show "Send email" on forms called from the Master form? Ie Customers called from Invoices...

**Comment by rrad0812** [comment]
No, all is all right with presentation, button 'Send mail', on form 'Customer', when form is open from 'Invoices' form, don't call 'Send mail' function.

Now, I see, on Customer form when it call as lookup, has not option for selected more customers.
Whatever, Андреw enjoy on ''каникули''. :)

**Comment by jam-py** [comment]
Hi, everybody!

I wanted to disable sending emails in customers, when it is opened as lookup item to select customer in invoice, removed multiple selections and fogot about buttons.

I have corrected the code. The customers client module looks now this way:

function init_table(item, options) {
    if (!item.view_form.hasClass('modal')) {    
        item.selections = [];    
    }
}

function on_view_form_created(item) {
    if (!item.view_form.hasClass('modal')) {    
        item.view_form.find('#email-btn')
            .click(function() {
                if (item.task.mail.can_create()) {
                    item.task.mail.open({open_empty: true});
                    item.task.mail.append_record();
                }
                else {
                    item.warning('You are not allowed to send emails.');
                }
            })
            .show();
        item.view_form.find('#print-btn')
            .click(function() {
                item.task.customers_report.customers.value = item.selections;
                item.task.customers_report.print(false);
            })
            .show();
    }
} 

The buttons now are enabled and visible when Customers view form is not modal.

Thank you Radosav, ''каникули" were great!
