### ISSUE TITLE
Dockerizing Jam.py (without success)

### ISSUE THREAD

**Issue by Kentoseth** [jam-py/jam-py#4]
```
FROM ubuntu:14.04

# Prerequisites

RUN \
  sudo apt-get update && \
  sudo apt-get -y upgrade && \
  sudo apt-get install -y python2.7 python2.7-dev python-pip && \
  sudo apt-get clean

RUN \
  sudo apt-get install -y ubuntu-artwork dmz-cursor-theme ca-certificates xdot python-gtk2 python-gtk2-dev python-gtksourceview2

RUN \
  sudo pip install jam.py
```

The above is the dockerfile and can be saved as "Dockerfile".

When running it, trying to use the X-server, this is the docker-command:

> sudo docker run -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY [IMAGE-NAME]

I've so far had no luck containerizing this. There are no errors, but after running "jam-project.py" in the container itself, no pop-up dialogue-box appears.

Is there something I am missing (possibly from the ubuntu-packages that need installing)?

**Comment by jam-py** [comment]
I'v made major rework of the framework and removed gtk from it completely. I have noy yet changed documentation. I am very sorry. I'm working on it now.Please read install file.  Andrew Yushev   07.06.2015, 05:36, "Moe" <notifications@github.com>:FROM ubuntu:14.04

# Prerequisites

RUN \
  sudo apt-get update && \
  sudo apt-get -y upgrade && \
  sudo apt-get install -y python2.7 python2.7-dev python-pip && \
  sudo apt-get clean

RUN \
  sudo apt-get install -y ubuntu-artwork dmz-cursor-theme ca-certificates xdot python-gtk2 python-gtk2-dev python-gtksourceview2

RUN \
  sudo pip install jam.py
The above is the dockerfile and can be saved as "Dockerfile".When running it, trying to use the X-server, this is the docker-command:sudo docker run -i -t -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY [IMAGE-NAME]I've so far had no luck containerizing this. There are no errors, but after running "jam-project.py" in the container itself, no pop-up dialogue-box appears.Is there something I am missing (possibly from the ubuntu-packages that need installing)?—Reply to this email directly or view it on GitHub.

**Comment by Kentoseth** [comment]
Hi Andrew,

I'd like to help with the documentation then.

If we can Dockerize Jam.py, it will make installing it much easier for Mac/Linux users (as simple as running the Dockerfile).

Is v.2.01 (the recent version you updated on pip and the github repo) the version without GTK and has the major changes?

**Comment by jam-py** [comment]
Hi, Moe,
I will be very glad if you help me with documentation and it would be great to Dockerize Jam.py.
But I am leaving on vacation and I be back only on the 3 of july. I'll send you message when I be back.
The lastest version is 2.0.3. All is the same as with gtk, only Administrator is run in the browser.
Just run the server.py and the in the browser adress bar input 127.0.0.1:8080 to run project and
127.0.0.1:8080/admin.html to work in Administrator. To imply the changes made in Administrator
press F5 to see them in the project. Please try Demo project in the demo directory.
Kind regards,
Andrew Yushev

**Comment by jam-py** [comment]
Hi, Moe,
You have promised to help me with documentation. Don't you rethink?
I really need help.
Best, 
Andrew

**Comment by Kentoseth** [comment]
I did promise that.

I am planning on Dockerizing Jam.py version 2.0.3 and I can make this my starting contribution to Jam.py.

This should also make it easier to install Jam.py across different Linux distributions.

**Comment by jam-py** [comment]
OK 06.07.2015, 23:12, "Moe" <notifications@github.com>:I did promise that.I am planning on Dockerizing Jam.py version 2.0.3 and I can make this my starting contribution to Jam.py.This should also make it easier to install Jam.py across different Linux distributions.—Reply to this email directly or view it on GitHub.
