### ISSUE TITLE
How to build a Docker image?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#42]
Hi Andrew

would it be possible to build an docker image of the built application? If so, how?

Thanks

**Comment by jam-py** [comment]
Hi, Dean.

I am sorry, I have no experience with docker.

2017-06-19 11:27 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Ok, no worries.

**Comment by dbabicwa** [comment]
I experimented a bit and found the solution.

To create a Docker image of the jam-py application, let's say Demo application, we need two files:
Dockerfile
requirements.txt

The Dockerfile:

`#Use an official Python runtime as a base image
FROM python:2.7-slim

# Set the working directory to /app
WORKDIR /app/jam.py-4.0.78/demo1 

# Copy the current directory contents into the container at /app
ADD . /app/jam.py-4.0.78/demo1

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME jam

# Run app.py when the container launches
CMD ["python", "server.py"]
`

The requirements.txt consists on only one line:
jam.py

Run Docker:
`sudo docker build -t jam .

sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jam                 latest              7f2a49fd8b0e        12 minutes ago      208 MB

sudo docker run -p 80:8080 jam
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
`

**Comment by JhoanR23** [comment]
> I experimented a bit and found the solution. Used this site as an Orientation with [Docker:](https://docs.docker.com/get-started)
> 
> To create a Docker image of the jam-py application, let's say Demo application (source location for the below files and commands), we need two files: Dockerfile requirements.txt
> 
> The Dockerfile:
> 
> ```
> #Use an official Python runtime as a base image
> FROM python:2.7-slim
> 
> # Set the working directory to /app
> WORKDIR /app/jam.py-4.0.78/demo1 
> 
> # Copy the current directory contents into the container at /app
> ADD . /app/jam.py-4.0.78/demo1
> 
> # Install any needed packages specified in requirements.txt
> RUN pip install -r requirements.txt
> 
> # Make port 80 available to the world outside this container
> EXPOSE 8080
> 
> # Define environment variable
> ENV NAME jam
> 
> # Run app.py when the container launches
> CMD ["python", "server.py"]
> ```
> 
> The requirements.txt consists on only one line: `jam.py`
> 
> Run Docker:
> 
> ```
> sudo docker build -t jam .
> Sending build context to Docker daemon 2.196 MB
> Step 1/7 : FROM python:2.7-slim
>  ---> 4ba53c70eb04
> Step 2/7 : WORKDIR /app/Downloads/jam.py-4.0.78/demo1
>  ---> f0e5dbb3531c
> Removing intermediate container 5ce14eb7afab
> Step 3/7 : ADD . /app/Downloads/jam.py-4.0.78/demo1
>  ---> 78446d01a38a
> Removing intermediate container 6d22d7c97d86
> Step 4/7 : RUN pip install -r requirements.txt
>  ---> Running in 646f5689087b
> Collecting jam.py (from -r requirements.txt (line 1))
>   Downloading jam.py-4.0.78.tar.gz (6.8MB)
> Building wheels for collected packages: jam.py
>   Running setup.py bdist_wheel for jam.py: started
>   Running setup.py bdist_wheel for jam.py: finished with status 'done'
>   Stored in directory: /root/.cache/pip/wheels/bf/08/2b/5957b3a229165a5b5c4c3eb9b3af895b2589ccdcfaa45537c2
> Successfully built jam.py
> Installing collected packages: jam.py
> Successfully installed jam.py-4.0.78
>  ---> a979ff63761a
> Removing intermediate container 646f5689087b
> Step 5/7 : EXPOSE 8080
>  ---> Running in 41f81057595e
>  ---> 416ab65f798d
> Removing intermediate container 41f81057595e
> Step 6/7 : ENV NAME jam
>  ---> Running in 15ab7cec5472
>  ---> 7cfa0d04770f
> Removing intermediate container 15ab7cec5472
> Step 7/7 : CMD python server.py
>  ---> Running in 9b7495e49d2a
>  ---> 7f2a49fd8b0e
> Removing intermediate container 9b7495e49d2a
> Successfully built 7f2a49fd8b0e
> 
> sudo docker images
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> jam                 latest              7f2a49fd8b0e        12 minutes ago      208 MB
> .
> .
> .
> 
> sudo docker run -p 80:8080 jam
>  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
> ```
> 
> We should be able now to access the host on port 80 as usual. The Docker image is 208MB in size which we can upload to a chosen Repository and deploy.
> 
> Comments welcome!
> 
> Enjoy

this dosen't include the libreofficie to do reporting dose it?

**Comment by platipusica** [comment]
Correct, it does not.

**Comment by platipusica** [comment]
```
docker pull platipusica/jam.py:latest
```

**Comment by arisobel** [comment]
Dear @platipusica - thanks very much.
I have tryed your image and it worked like a charm.

based on some iamges I saw and on a lot of Chat GPT chatting :-D, I got the below:
But when I have tried to run in my server I've got some Issues.

The best woud be to hacve you image and make 2 adaptations.

**- Not making based Demo - only a empty App.**
**- Installing mysql (libs) connection - for Mysql database **

I have the bellow, not working so well

<pre>
FROM python:3.8-slim

# Atualizar o apt e instalar dependências necessárias
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    libssl-dev \
    libffi-dev \
    libmariadb-dev \
    git \
    libreoffice \
    libreoffice-common \
    libreoffice-writer \
    gcc \
    python3-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instalar bibliotecas Python
RUN pip install --no-cache-dir mysql-connector-python mysqlclient

# Instalar o jam-py
RUN pip install jam-py-v7 gunicorn

# Criar o diretório de trabalho /app
RUN mkdir /app
WORKDIR /app

# Adicionar o código da aplicação ao diretório /app
COPY ./src /app

# Expor a porta 8081 para acessar a aplicação
EXPOSE 8080

# Iniciar o servidor
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "wsgi:application"]
</pre>

I put it on Dockerhub 
docker pull arisobel/jam-py-lion:latest


I have also seen, old imagens, with libreoffice
https://hub.docker.com/r/tetricky/jam-py
but witout clue how it was built.

Other point is that, to try to serve the app with a server , and not with the development server, I (with help og GPT) tried to integrate with gunicorn.

@platipusica - can you help to adapt your image to allow Mysql and not to build Demo, only a empty app?


**THANKS**
