### ISSUE TITLE
Creating jam project in Windows

### ISSUE THREAD

**Issue by aeroaks** [jam-py/jam-py#43]
Hi,

I am using version 4.0.80 on Windows. I created and virtual environment and installed jam.py using pip. I can check this by running python inside the environment and running `import jam`. But when I try to run `jam-project.py` then I get the following error:

```
...Scripts\jam-project.py", line 7, in <module>
    import jam
ImportError: No module named 'jam'
```

**Comment by dbabicwa** [comment]
Hi mate, 

which Win and python? Maybe not relevant question but did you install jam at all?  

Cheers

**Comment by aeroaks** [comment]
Windows 10 and Python 3.5.3

```
D:\workspace\explore\jam_py_db\src
λ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
jam.py (4.0.80)
pip (9.0.1)
setuptools (36.0.1)
six (1.10.0)
wheel (0.29.0)

D:\workspace\explore\jam_py_db\src
λ jam-project.py
Traceback (most recent call last):
  File "C:\Users\Akshay\.virtualenvs\jam_py_db-moj6wsAC\Scripts\jam-project.py", line 7, in <module>
    import jam
ImportError: No module named 'jam'
```

**Comment by dbabicwa** [comment]
Ok, thanks

my understanding is that jam is not ready yet for python  3.5.x, but will leave for Andrew to reply.

D.

**Comment by aeroaks** [comment]
If I run it like this:
` <path to venv>\Scripts\python.exe <path to venv>\Scripts\jam-project.py `

Then it works!

**Comment by dbabicwa** [comment]
Sure it does, cheers

My suggestion would be to dive in as is, py3 is not necessarily needed to get a great results with jam. Than, when the dust settles, go with the latest!
