### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by aeroaks** [jam-py/jam-py#44]
I am trying out the repo and found out that repo is not supported to run in Python 3. 

What is the roadmap ahead keeping in mind that the support for Python 2 will end in 2020.

**Comment by dbabicwa** [comment]
That's three years from now. Plenty of time. 
Of course, it would be great if some developers would volunteer their's time in a journey and a major release ahead of jam-py. It's a great framework, and proven in production.
Till than I'll leave for Andrew to answer.

**Comment by jam-py** [comment]
Hi, 

Thank you Dean.
I worked on the support for Python 3. But to finish it I first must rework the localization. I plan to 
realize it in a 2-3 month.

Andrew Yushev
