### ISSUE TITLE
Oracle and MSSQL support?

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#5]
Hi Andrew,
thank you for your effort in building jam-py. I think it is great and found no issues with installation on Linux Mint Cinnamon.
I did compile cx_Oracle for Python with Oracle XE and this is working well. However, I can't figure out how to use Oracle with jam-py.
And suggestion with this? 
Thank you and greetings from Perth (AU).
Dean

**Comment by jam-py** [comment]
Hi Dean,
I am now working on a system that will allow to add new database to
the framework
easily. I plan to publish new version next week. I will informed when it is
ready.
Kind regards,
Andrew

2015-07-28 7:13 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Fantastic!
For people who would like to try running cx_Oracle this is great news. I think to compile cx, one should just set ORACLE_HOME, ORACLE_SID and LD_LIBRARY_PATH to ORACLE_HOME/lib and this should work with: pip install cx_Oracle (if using sudo, this vars will go away, resulting in error :)

I am trying to figure out how to run jam_py with mod_wsgi, any input on that?

Cheers

**Comment by jam-py** [comment]
Hi Dean, 
I never run jam_py with mod_wsgi. But it's build on web.py and there is link on webpy.org http://webpy.org/cookbook/mod_wsgi-apache. May be it will help.
I released version 2.04. It supports mysql (testing is needed). To add new database add the new module to db folder of framework and register it in db_modules module.
Andrew

**Comment by dbabicwa** [comment]
Hi, 
to help a bit I think the project wasn't labelled correctly (or I might be wrong:) When pulled with git clone  https://github.com/jam-py/jam-py.git
in 1.0.5 demo folder has client, admin, main etc files. In 2.04 this files are missing.
I also noticed there is no data showing when running a server.py and jam-project.py doesn't do anything in a new version.
There is a bug when downgrading to version 1.0.5 in jam-project.py since the installer will not overwrite the file and will keep the 2.04.
Also, when running a client.py the system doesn't recognise a default system lang, and is showing "Server not accessible" - on Cyrillic (which I can read but others can't:) Please fix somehow coz this can put off the users. There are some (и) characters in User_guide_en as well :)

I think before this is fixed I can't do much. Can you help?

Spasiba

Dean

**Comment by jam-py** [comment]
Hi, Dean.

Users experienced some problems with gtk. It's hard to install it in windows for example. Further more as I've heard it's no more developed. And I personally don't like it myself. So I removed in completely in version 2.01. It's now “all in the browser framework” and don't support desktop any more. To run a project input  127.0.0.1 in the browser address bar after starting server.py. I developed Administrator in the javascript so you can run it in a browser by typing 127.0.0.1/admin.html. To imply the changes made in Administrator press F5 to see them in the project. 
I didn't have time to update docs and site yet. But I plan to start doing it next week.

If you still interested in the framework, you can try Demo project in the demo folder.  Thank you for  your comments. 

Pozhaluysta

Andrew

**Comment by jam-py** [comment]
Dean, please use the latest version 2.0.4

**Comment by dbabicwa** [comment]
Cool, thanks!
this is working now. Shame about the gtk though since was working really nice on linux. 

The biggest question of all: how to use the users/roles since there is no "Login" option? 

Btw, on 1.0.5 the Print invoice to PDF was working, with 2.0.4 it is not. 

Cheers
D.

**Comment by jam-py** [comment]
To use users and roles check the Safe mode checkbox in the Project parameters. To convertion be working the LibreOffice should be closed on the server (no open documents).
Best,
Andrew

**Comment by dbabicwa** [comment]
Thanks, I tested this but wasn't really paying attention to Admin password so did the:
sqlite3 admin.sqlite .dump |grep admin 
to get the password after I checked the Safe mode and exited (because couldn't login after that) :+1: 

Than I did this: under Roles I disabled everything for User except "Customers" role. However, I can still see the Journals and Reports tab as User. Under Catalogs I see Customers, and this is fine.

I think it would be great if other tabs (Journals and Reports), are not visible. I don't know if is designed to be like that, however I'm still testing 1.0.5. from home. At work I do have 2.0.4 and will test on Monday.

BR

Dean

**Comment by dbabicwa** [comment]
Hi Andrew,
would you be able to add mysql dump into the project so we can try it? I've tried:
wget http://www.redmine.org/attachments/download/7484/sqlite3-to-mysql.py

to convert the sqlite3 but can't make it to work with jam-py. This is the error:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 1: invalid continuation byte

Thanks!

**Comment by jam-py** [comment]
Hi, Dean.

You can change the interface of the project. Select Task node in the project tree and then click on Client module button. The code editor opens and you can see event handlers. In the on_page_loaded event handle there is the code that creates menus when page is loaded. You can change the way it behaves. Each item in the client has the following methods:
can_view,
can_create,
can_edit,
can_delete
You can check if there are no reports and journals that you can view and in this case don't create corresponding menu items.

As far as MySql database concerned. Try to do the following way:
1. Run the Demo Administrator. Press the Export button and save the the file with export somewhere on the disk.
2. Create empty mysql database
3. Create new project with this database (set encoding to utf8)
4. Press the Import button and select file that you saved in the paragraph 1. The Administrator should create database structures the same as in the Demo project and copy all the code.
5. Copy from Demo directory demo.sqlite into your project folder.
6. In the Administrator of the new project select Task node in the project tree and then click on Server module button and copy the following code:

from jam.db.db_modules import *

def on_created(task):
 	task.copy_database_data(SQLITE, db_database='demo.sqlite')

Press F5 in the project browser tab. The database data will be copied from Demo. Remove the code you copied.

If there will be some problems inform me please.

Best,
Andrew

**Comment by dbabicwa** [comment]
No probs, thanks
However "4. Press the Import button and select file that you saved in the paragraph...".
This is a problem since we don't know the MySQL database structure (as per above BLOB error). Hence would be great if you provide the demo database :)
But back to the original question: MSSQL and Oracle? I see the code for it but don't know how to test.
Or not yet ready?

**Comment by jam-py** [comment]
I am sorry, Dean. I confused MSSQL with MYSQL and added MYSQL to the
framework. There is a lot of urgent work right now so I won't be able to do
it in the near future (must install databases and do on). But you can add
them yourself. If you don't mind I will right and send you a detailed
instruction.

2015-08-11 9:19 GMT+03:00 dbabicwa <notifications@github.com>:

**Comment by dbabicwa** [comment]
Ah, ok, no worries! Thank you!

**Comment by jam-py** [comment]
To add a new database.

It's better to create a new project with jam-project.py script in an empty directory and then copy there the jam folder from package directory. Go to db folder in jam directory. There is a db_modules.py file. To register a new database change it the following way:

# -*- coding: utf-8 -*-

SQLITE, FIREBIRD, POSTGRESQL, MYSQL, MSSQL = range(1, 6)
DB_TYPE = ('Sqlite', 'FireBird', 'PostgreSQL', 'MySQL', 'MS SQL')

def get_db_module(db_type):
    db = None
    if db_type == SQLITE:
        import sqlite as db
    elif db_type == FIREBIRD:
        import firebird as db
    elif db_type == POSTGRESQL:
        import postgres as db
    elif db_type == MYSQL:
        import mysql as db
    elif db_type == MSSQL:
        import mssql as db
    return db

in the code above the mssql database was registered. Now we need to create mssql.py with new database definition. Copy postgres .py, for example, to  mssql.py.
After that we need to modify mssql.py:

# change to new database module
import psycopg2 

# define parameters needed to create a connection 
NEED_DATABASE_NAME = True 
NEED_LOGIN = True
NEED_PASSWORD = True
NEED_ENCODING = False
NEED_HOST = True
NEED_PORT = True

# jam.py has limited set of field types, define fields that correspond to these types in
# the FIELD_TYPES dictionary
JAM_TYPES = TEXT, INTEGER, FLOAT, CURRENCY, DATE, DATETIME, BOOLEAN, BLOB = range(1, 9)
FIELD_TYPES = {
    INTEGER: 'INTEGER',
    TEXT: 'VARCHAR',
    FLOAT: 'NUMERIC',
    CURRENCY: 'NUMERIC',
    DATE: 'DATE',
    DATETIME: 'TIMESTAMP',
    BOOLEAN: 'INTEGER',
    BLOB: 'BYTEA'
}

# after defining connect function try to create new project with this database the      
# Adminstrator checks the connection  
def connect(database, user, password, host, port, encoding):
    return psycopg2.connect(database=database, user=user, password=password, host=host,          port=port)

# for databases such as SQLITE 
def get_lastrowid(cursor):
    return None

# bellow we define the how statements are generated by framework 
LEFT_OUTER_JOIN = 'LEFT OUTER JOIN'
LIKE = 'ILIKE'

# offset, limit is defined at start of the select statement
def limit_start(offset, limit):
    return ''

# otherwise
def limit_end(offset, limit):
    return 'LIMIT %d OFFSET %d' % (limit, offset)

def create_table_sql(table_name, fields, foreign_fields=None):
    result = []
    seq_name = '%s_id_seq' % table_name
    result.append('CREATE SEQUENCE "%s"' % seq_name)
    sql = 'CREATE TABLE "%s"\n(\n' % table_name
    for field in fields:
        if field['field_name'].lower() == 'id':
            sql += '"ID" %s PRIMARY KEY DEFAULT nextval(\'"%s"\')' % \
            (FIELD_TYPES[field['data_type']],
            seq_name)
        else:
            sql += '"%s" %s' % (field['field_name'], FIELD_TYPES[field['data_type']])
        if field['size'] != 0 and field['data_type'] == TEXT:
            sql += '(%d)' % field['size']
        sql +=  ',\n'
    sql = sql[:-2]
    sql += ')\n'
    result.append(sql)
    result.append('ALTER SEQUENCE "%s" OWNED BY "%s"."ID"' % (seq_name, table_name))
    return result

def delete_table_sql(table_name):
    result = []
    result.append('DROP TABLE "%s"' % table_name)
    return result

def create_index_sql(index_name, table_name, fields, desc):
    return 'CREATE INDEX "%s" ON "%s" (%s)' % (index_name, table_name, fields)

def create_foreign_index_sql(table_name, index_name, key, ref):
    return 'ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s(ID) MATCH SIMPLE' % \
        (table_name, index_name, key, ref)

def delete_index(table_name, index_name):
    return 'DROP INDEX "%s"' % index_name

def delete_foreign_index(table_name, index_name):
    return 'ALTER TABLE %s DROP CONSTRAINT %s' % (table_name, index_name)

def add_field_sql(table_name, field):
    result = 'ALTER TABLE "%s" ADD COLUMN "%s" %s'
    result = result % (table_name, field['field_name'], FIELD_TYPES[field['data_type']])
    if field['size']:
        result += '(%d)' % field['size']
    return result

def del_field_sql(table_name, field):
    return 'ALTER TABLE "%s" DROP COLUMN "%s"' % (table_name, field['field_name'])

def change_field_sql(table_name, old_field, new_field):
    if FIELD_TYPES[old_field['data_type']] != FIELD_TYPES[new_field['data_type']] \
        or old_field['size'] != new_field['size']:
        raise Exception, u"Don't know how to change field's size or type of %s" % old_field['field_name']
    result = 'ALTER TABLE "%s" RENAME COLUMN  "%s" TO "%s"' % (table_name, old_field['field_name'], new_field['field_name'])

# converts the statements to the appropriate register
def set_case(string):
    return string.lower()

literal for parameters in update and insert statements
def param_literal():
    return '%s'

# bellow are the functions that define generators for primary keys
def get_sequence_name(table_name):
    return '%s_id_seq' % table_name

def next_sequence_value_sql(table_name):
    return set_case("select nextval('%s')" % get_sequence_name(table_name))

def restart_sequence_sql(table_name, value):
    return set_case('alter sequence %s restart with %d' % (get_sequence_name(table_name), value))


This schema works fine with previously registered databases, may be there will be problems with new ones. In this case write to me,  I'll try to adapt the framework

**Comment by dbabicwa** [comment]
Whow :) Extensive :) Thanks for doing it.
Will try next week and report back. 

D.

**Comment by dbabicwa** [comment]
Hi Andrew,

I tried:
6. In the Administrator of the new project select Task node in the project tree and then click on Server module button and copy the following code:

This looks ok but:

Import: reading changes
Import: analyzing changes
CREATE TABLE "DEMO_CUSTOMERS"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"ADDRESS" VARCHAR(70),
"CITY" VARCHAR(40),
"COMPANY" VARCHAR(80),
"COUNTRY" VARCHAR(40),
"EMAIL" VARCHAR(60),
"FAX" VARCHAR(24),
"FIRSTNAME" VARCHAR(40),
"LASTNAME" VARCHAR(20),
"PHONE" VARCHAR(24),
"POSTALCODE" VARCHAR(40),
"STATE" VARCHAR(40),
"SUPPORT_REP_ID" INT,
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_TRACKS"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"ALBUM" INT,
"BYTES" INT,
"COMPOSER" VARCHAR(220),
"GENRE" INT,
"MEDIA_TYPE" INT,
"MILLISECONDS" INT,
"NAME" VARCHAR(200),
"TRACK" VARCHAR(500),
"TRACKS_SOLD" INT,
"UNITPRICE" DOUBLE,
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_ALBUMS"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"ARTIST" INT,
"TITLE" VARCHAR(160),
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_ARTISTS"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"NAME" VARCHAR(120),
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_GENRES"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"NAME" VARCHAR(120),
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_MEDIA_TYPES"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"NAME" VARCHAR(120),
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_INVOICES"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"CUSTOMER" INT,
"INVOICEDATE" DATE,
"SUBTOTAL" DOUBLE,
"TAX" DOUBLE,
"TAXRATE" DOUBLE,
"TOTAL" DOUBLE,
PRIMARY KEY("ID"))

CREATE TABLE "DEMO_INVOICE_TABLE"
(
"DELETED" INT,
"ID" INT NOT NULL AUTO_INCREMENT,
"OWNER_ID" INT,
"OWNER_REC_ID" INT,
"AMOUNT" DOUBLE,
"QUANTITY" INT,
"TAX" DOUBLE,
"TOTAL" DOUBLE,
"TRACK" INT,
"UNITPRICE" DOUBLE,
PRIMARY KEY("ID"))

CREATE INDEX "DEMO_INVOICE_TABLE_IDX" ON "DEMO_INVOICE_TABLE" ("OWNER_ID", "OWNER_REC_ID")
CREATE INDEX "DEMO_INVOICES_IDX" ON "DEMO_INVOICES" ("DELETED", "INVOICEDATE")
Import: waiting for connections to close
Import: applying changes to the database
Import: applying changes to admin.sqlite
Import: copying files
Import: deleteing tmp files.
.
.

  File "demo", line 4, in on_created
    task.copy_database_data(SQLITE, db_database='demo.sqlite')
AttributeError: 'Task' object has no attribute 'copy_database_data'

Any ideas what is wrong? Using jam.py-3.3.1-py2.7.egg!

Thanks

**Comment by jam-py** [comment]
Hi, I am sorry, I've changed the method name to the 'copy_database'. Try
task.copy_database(SQLITE, db_database='demo.sqlite')

**Comment by dbabicwa** [comment]
No problem, I did try, different issue:
  File "/home/dbabic/Downloads/jam.py-3.3.1/demo/demo", line 2, in on_created
    task.copy_database(SQLITE, db_database='demo.sqlite')
NameError: global name 'SQLITE' is not defined

**Comment by dbabicwa** [comment]
Got it:
coping table customers: 100%
coping table tracks: 29%
coping table tracks: 58%
coping table tracks: 87%
coping table tracks: 100%
coping table albums: 100%
coping table artists: 100%
coping table genres: 100%
coping table media_types: 100%
coping table invoices: 100%
coping table invoice_table: 45%
coping table invoice_table: 90%
coping table invoice_table: 100%

It is:
from jam.db.db_modules import *

def on_created(task):
    task.copy_database(SQLITE, 'demo.sqlite')

Awesome! Spasiba!
