### ISSUE TITLE
Builder HTML page contains hardcoded Russian literals

### ISSUE THREAD

**Issue by gschizas** [jam-py/jam-py#51]
[The builder.html page ](https://github.com/jam-py/jam-py/blob/6b4a0763abfa5178f1636b5bd060d1e843d96ce4/jam/builder.html#L413-L419) contains hardcoded literals for "login" and "password" in the respective input tag placeholders, even though the rest of the page is in English. The логин and пароль should be replaced with "Username" and "Password" respectively.

**Comment by jam-py** [comment]
Thank you George. I corrected it.
Andrew Yushev
