### ISSUE TITLE
jam.py interaction with API to different systems

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#59]
Hi Andrew, 

hope everything is going well.

I am interested if API interaction from jam.py is possible into the different systems? How would we use that to let's say import some data, manipulate and insert into the jam tables?

Thanks

D.

**Comment by jam-py** [comment]
Hi, Dean

Everything is well.

There is no limitation on jam.py interactions with different systems. You can do anything that is possible with Python. 
For more details please see the following video:
Client-server interactions - https://youtu.be/nLOhdA2FX0I
Working with data on the server - https://youtu.be/dDK78lIjHHY

Besides theses you can process a request or get some data from other application or service:
http://jam-py.com/docs/faq/general/faq_request_from_other_application.html

Kind regards,
Andrew

**Comment by dbabicwa** [comment]
Cool

thanks!

**Comment by dbabicwa** [comment]
Hi Andrew, 

to be able to run above example, some packages must be installed. Maybe to add this to the Doco?

cat req.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib2
import json
import time

def send(url, request, params):
    a = urllib2.urlopen(url + '/' + request, data=json.dumps(params))
    r = json.loads(a.read())
    return r['result']['data']

if __name__ == '__main__':
    url = 'http://127.0.0.1:8082/ext'
    while True:
        result = send(url, 'get_sum', [1, 2, 3])
        print result
        time.sleep(10)


On the server console:
python req.py 1 2 3
6
6
6
6
6
.
.
jam output:
/server.py 8082
 * Running on http://0.0.0.0:8082/ (Press CTRL+C to quit)
127.0.0.1 - - [16/Jan/2018 15:45:03] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:45:13] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:45:23] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:45:33] "POST /api HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:45:33] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:45:43] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:45:53] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:46:03] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:46:13] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:46:23] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:46:33] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:46:43] "POST /ext/get_sum HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2018 15:47:04] "POST /api HTTP/1.1" 200 -

**Comment by jam-py** [comment]
Hi, Dean 
You are right. This code is for Python 2. I will correct docs when I release the next version.
Andrew
