### ISSUE TITLE
Docker Container: Unable to visit server.py

### ISSUE THREAD

**Issue by Kentoseth** [jam-py/jam-py#6]
I worked through the regular setup of going into a new folder (eg. folder1) and then typing:

`jam-project.py`

then I navigate to the folder: `cd folder1` and type:

`python server.py`

Which results in:

    /folder1# python server.py
    http://0.0.0.0:8080/

Now this being a docker container, I should be able to navigate to:

`localhost:8080`

and I should get a result, but I get "Problem Unable to Connect"

I also tried:

`localhost:8080/index.html` but still get the same problem.

Is there any way to resolve this?

**Comment by jam-py** [comment]
I am sorry but I don't know what is a docker container is. Try to input 127.0.0.1:8080 in a web browser.
