### ISSUE TITLE
Safe mode, and python3 password problem

### ISSUE THREAD

**Issue by gregers666** [jam-py/jam-py#60]
Hello,

Python3 needs encoding before hashing password - adm_server.py cannot change it.

2985         d.f_psw_hash.value = hashlib.md5(d.f_password.value).hexdigest()
->
2985         d.f_psw_hash.value = hashlib.md5(d.f_password.value.encode("utf8")).hexdigest()

Switching to 'safe mode' kills application - the problem lies here:

584 form_header = this.task.templates.find('.modal-header').clone(), // <- this doesn't work
->
584                 form_header = '', // temporary fix

and plus sign here

10105                 '<div ' + classStr + ' ' + divStyleStr + '>' + text
->
10105                 '<div ' + classStr + ' ' + divStyleStr + '>' + text +

Anyway it's a great app! Thanks a lot!

Sincerely
Grzegorz

**Comment by platipusica** [comment]
Awesome find!

Thanks for reporting! 

Cheers

**Comment by jam-py** [comment]
Thank you, Grzegorz!

Fixed the bugs

With kind regards, 
Andrew Yushev
