### ISSUE TITLE
How to save a txt file on a server from a DB tables?

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#61]
Hi Andrew, 

if I have a few tables with PK/FK, how would I save the complete tables as text file on a server (to specific path, not in temp or similar)? 
The problem is, the FK content text field MUST be at the bottom of the file as last entry. Same with other FK which must be at the Beginning of the file!

Something like:
Title (text, FK table 2.) - lines containing # at the beginning as a comment
Content (text, PK table 1) - tab spaced lines
Fusnote (text, FK table 3) - multiple lines containing # at the beginning as a comment, last line containing @ as first character.

This is a plain text file (non UTF pure asci since only email addresses as content) , tab or space spaced, and will be used on a  Linux server for processing (as called Linux command from the Jam - if possible).

And thoughts? Did not start yet, since not sure if possible...

Thx

D.

**Comment by jam-py** [comment]
Hi, Dean

I do not quite understand the algorithm, but there is usually no problem with saving data from db tables to files with Python in Jam.py.
Try to use server function, save file to static folder and then you can download it by link.
I will be happy to help if necessary.

Andrew

**Comment by platipusica** [comment]
Hi Andrew

that is the thing, I have no idea how to use the server function to
save the file. I would need to save the file when the user clicks the
button.

Basically, the order is important in the saved file, like:

-header
-main text
-footer

The header would come from one table, main from the another, footer third table.

There will be a few main tables but only one header and footer table
(coz the contain headers for all tables, same as footers)

Simple :)

**Comment by jam-py** [comment]
Hi, Dean

May be you will create some sample project and send it to me, so i will show how to save tables to file.

Andrew

**Comment by platipusica** [comment]
As provided by Andrew, the below code will write two files on the OS, taking the file location from the database table named 
```
import os
import subprocess

def save_to_file(item, item_id):
    body = item.task.wasp.copy()
    header = item.task.aliases_table_head.copy()
    footer = item.task.aliases_table_footer.copy()
    file_name = item.task.file_path.copy()
    
    text = ''
    file = ''
    
    header.set_where(header_for=1) 
    header.open()
    text += header.header.value + '\n'
    
    #body.set_where(id=item_id)
    body.open()
    for b in body:
        if body.used.value:
            text += body.alias.value + '\t' + body.to_mail.value + '\n' 
        
    
    footer.set_where(footer_for=1) 
    footer.open()
    text += footer.footer.value
    
    text = text.decode('utf8').encode('ascii')

    file_name.set_where(aliases_file_for=1)
    file_name.open()
    file = file_name.aliases_file_path.value
   
    
    with open(file, 'wb') as f:
        f.write(text)
        
    command = "postmap %s" % (file)
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    for line in p.stdout.readlines():
        print line,
   ```
