### ISSUE TITLE
textarea undocumented? 

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#62]
In demo:

demo.catalogs.mail:17: item.edit_form.find('textarea.mess').height(120);

Looks like textarea is actually blob? How would one use a textarea with a text field, and not a blob?

Cheers

D.

**Comment by jam-py** [comment]
I plan to add some checkbox in the Builder.

You can do it now by writing init_inputs function in the Client module:

function init_inputs(item, options) {
    item.field_name.data_type = task.consts.BLOB;
}

for field_name field.

Andrew
