### ISSUE TITLE
Table Name on Item group bug in 5.3.3

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#63]
Steps to confirm:
- create a new Item Group - the id and deleted are not populated automatically (do we need to do that?). Also, it has different behavior than on ie Catalogs, where id&deleted is not listed as fields we can modify.

- create any table.

The Item group will show, tables will not show.

D.

**Comment by jam-py** [comment]
Hi, Dean

I created a new Item Group and added a new item.
I works well. There were no problem.
I used Jam.py version 5.3.3.
Can you send me a project?

Common id and deleted fields are not mandatory. You can 
specify them for each item.

Kind regards,
Andrew

**Comment by platipusica** [comment]
Hmm,
I just checked on different PC and you're right, no issues. On old one, firefox and chrome is not showing any tables...Will send you tmrw.

D.
