### ISSUE TITLE
Clickable icons?

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#65]
Hi Andrew, 

not sure if this was discussed before, how would I make an icon and assign a click action to it?

Cheers

D.

**Comment by jam-py** [comment]
Hi, Dean
You must add a button in the html template in the index.html file. For
example:

<button type="button" id="ok-btn" class="btn">
    <i class="icon-ok"></i>
</button>

The icons you can use see there:
http://getbootstrap.com/2.3.2/base-css.html#icons

After that you find this button in the corresponding form
and assign an event handler to it using JQuery:

function on_view_form_created(item) {
    item.view_form.find('#ok-btn').click(function() {
         item.append_record();
    })
}

I plan to create in future actions that can be displayed as buttons or menu
items.
But now you must do it this way

With regards,
Andrew

2018-04-09 10:15 GMT+03:00 platipusica <notifications@github.com>:

**Comment by platipusica** [comment]
Ok, thanks!
