### ISSUE TITLE
Large (rich) text format how to? Ie a Help.

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#66]
Hi, 

another question, what would be the best way to design a Help?

Let's say we put everything into the DB, but how than to display a reach content, with formatting,  Icons, images etc?

Cheers

D.

**Comment by jam-py** [comment]
You can create the help and add a link to it.
As the link to jam.py from demo application.

Andrew

2018-04-09 10:20 GMT+03:00 platipusica <notifications@github.com>:
