### ISSUE TITLE
Languages -  RTL Support

### ISSUE THREAD

**Issue by sm2x** [jam-py/jam-py#69]
are languages with Right-to-Left Orientation supported (Arabic, Farsi, Hebrew, etc.)
how can it be achieved please

**Comment by platipusica** [comment]
Jam is working towards internationalization for the new release including the translation module.

If you attach needed translations within this file, it will be possible to try it before the release and include as such.

Cheers

D.
[English_en-US_2018-04-12_09-46-58.lang.txt](https://github.com/jam-py/jam-py/files/1930993/English_en-US_2018-04-12_09-46-58.lang.txt)

**Comment by jam-py** [comment]
I will add Right-to-Left Orientation support in the next release
(approximately next  week)

2018-04-20 9:34 GMT+03:00 platipusica <notifications@github.com>:

**Comment by sm2x** [comment]
very glad to know, RTL will be supported
