### ISSUE TITLE
Extend Field Objects

### ISSUE THREAD

**Issue by sm2x** [jam-py/jam-py#70]
how can i create/add field types such as these please:
- capture image still from live webcam/camera and/or upload/link image from local or remote source
- signature pad
- barcode field
- nfc/rfid field
- rich text editor

**Comment by platipusica** [comment]
Not sure if the Jam.py purpose is to include all arbitrary fields. 
You need to ask yourself is xyz platform (even commercial one),  is the right tool for the job on hand? 

So, pls explain what exactly would you like to achieve and we'll go from there.

**Comment by jam-py** [comment]
Jam.py task object on the client has upload method:
http://jam-py.com/docs/refs/client/task/m_upload.html
so you can upload an images or file of some other type to the folder on the
server,
save file name in table and later get it.
As for rich text editor, there are javascript libraries that you can use.


2018-04-20 9:40 GMT+03:00 platipusica <notifications@github.com>:

**Comment by sm2x** [comment]
well im impressed what i saw in jam.py, and thinking if i can use it to develop rich applications such as ERP, CRM, etc.
