### ISSUE TITLE
Create Objects Dynamically

### ISSUE THREAD

**Issue by sm2x** [jam-py/jam-py#71]
how to create and add objects dynamically on the fly, use case in point, if i wish to create a new Menu Category button to group my items on a Restaurant POS, do you think jam.py is suitable to build such Hospitality POS app?

**Comment by jam-py** [comment]
Jam.py creates a dynamic menu in the on_page_loaded event handler of the
task object.
You can remove this code and create any menu you need


2018-04-20 7:22 GMT+03:00 sm2x <notifications@github.com>:

**Comment by jam-py** [comment]
I think I didn't understand your question.
There is a new feature that is undocumented yet.
It allows to create dynamic fields for virtual (that don't have
corresponding DB table) items
and can be used to represent master-detail data in the table format.



2018-04-20 10:13 GMT+03:00 Andrew Yushev <yushevaa@gmail.com>:

**Comment by sm2x** [comment]
sorry for the confusion about "menu", im talking about Food Menu in a Restaurant, 
this is what im planning to build
![pos-mockup](https://user-images.githubusercontent.com/6595333/39086085-1d717fd0-45bf-11e8-9844-d9975b5843be.jpg)

so my question is how can i dynamically create those menu items as button or clickable labels using
jam.py
