### ISSUE TITLE
Oracle History table issue, v.5.4.4 

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#74]
Hi Andrew, 

the H. table was created, but when changing the filed:

Error: ORA-01722: invalid number
 command: INSERT INTO "TEST_HISTORY" ("ITEM_ID", "ITEM_REC_ID", "OPERATION", "CHANGES", "USER", "DATE") VALUES (:f1, :f2, :f3, :f4, :f5, :f6)
 params: [7, 'HR', 2, <cx_Oracle.BLOB with value <cx_Oracle.LOB object at 0x7f3f300be198>>, '', datetime.datetime(2018, 5, 19, 23, 4, 47, 732195)]
127.0.0.1 - - [19/May/2018 23:04:47] "POST /api HTTP/1.1" 200 -
 .
.
Table:
SQL> desc TEST_HISTORY;
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 ITEM_ID					    NUMBER
 ITEM_REC_ID					    NUMBER
 OPERATION					    NUMBER
 CHANGES					    BLOB
 USER						    VARCHAR2(30)
 DATE						    TIMESTAMP(6)

Regards

D.

**Comment by jam-py** [comment]
Dean,
I fixed Oracle bugs. I will publish a release this week
Andrew
