### ISSUE TITLE
Detail of a detail

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#78]
Hi, 

Is it supported to have details inside details? 

Regards,
Davide

**Comment by platipusica** [comment]
Hi Davide,

do you mean master->child->child? If not, can you explain a bit further please?

Thx
Dean

**Comment by jam-py** [comment]
Yes, Jam.py supports it. But this requires a little coding. I'm making an example.
It will be ready a little later.
Regards,
Andrew

**Comment by ddavidebor** [comment]
@platipusica I mean having a detail containing another detail.

For example, following the demo logic: an invoice, containing albums, containing tracks.

**Comment by jam-py** [comment]
Hi, Davide
It is a link to an app demonstrating master-detail-detail: 
https://drive.google.com/file/d/1fE7RjPAZ4MtakO37EN4wpe2J15ubQSpZ/view?usp=sharing
See polls.js and questions.js, please.
If you have any questions, I'll be happy to answer.
Andrew

**Comment by ddavidebor** [comment]
Thanks! I will close the issue for now and eventually re open if i have questions. Thank you very much

**Comment by musahi-0128** [comment]
Hello, I was opening a new issue in #290. @platipusica redirect me to this one. @jam-py @ddavidebor I would like to get the file on this link, maybe you still have it?
> https://drive.google.com/file/d/1fE7RjPAZ4MtakO37EN4wpe2J15ubQSpZ/view?usp=sharing
I want to understand how details in details work and following example in the docs gives me nothing, but real example might be easier for me to follow.
Thanks!
