### ISSUE TITLE
Jam.py 5.4.16 - Search box dont doing on utf-8 chars

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#79]
serbian letters čćžšđ don't pass in search box, 
ie.  result by search is not correct.

**Comment by platipusica** [comment]
Rad, 

which database please? On Oracle the NLS... must be set...

D.

**Comment by rrad0812** [comment]
Hi, D.
Database is SQLite.
Language Serbian.

Regards,

**Comment by jam-py** [comment]
Radosav,
I am not able to fix this because I can repeat this situation.
Can you send me your project?

**Comment by rrad0812** [comment]
Hi, Andrew
Yes, of course.

**Comment by jam-py** [comment]
Hi, Radosav

Thank you for the app. I think I found the problem - it is that search in sqlite is case sensitive now.
I fixed it and publish in the next release.
I can correct it by replacing

def upper_function():
    pass

with

def upper_function():
    return 'UPPER'

Andrew

**Comment by rrad0812** [comment]
Confirm.
What to say.
I was not even at the end of my mind.

With respect,
Radosav
