### ISSUE TITLE
Row level locking

### ISSUE THREAD

**Issue by dbabicwa** [jam-py/jam-py#8]
Hi Andrew, 
in Demo appl is there a way to do a row level locking? Can you provide an example of how to do this?

Thank you!

Dean

**Comment by dbabicwa** [comment]
Just a note, I am using MySQL. Thanks

**Comment by jam-py** [comment]
Hi Dean, 
there is no row level locking. You should implement it yourself.

Best,
Andrew

**Comment by jam-py** [comment]
Dean, can you specify a bit what you mean by locking. When to lock, when to unlock? What to do if a user performs some operation that locks a row, then closes the browser and fogets about it?
