### ISSUE TITLE
Jam.py 5.4.16 - Question mark buble is not translated

### ISSUE THREAD

**Issue by rrad0812** [jam-py/jam-py#80]

**Comment by jam-py** [comment]
Hi, Radosav.
I'm sorry, I do not understand what you mean.

**Comment by rrad0812** [comment]
Hi,
Jam-py, 5.4.16, my new project, SQLite, Serbian language
When mouse going across question mark next to search box apperance buble
with english text.

Regards,

**Comment by jam-py** [comment]
I see it now. I'll correct it in the next release.
Thank you
