### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#81]
Hi,

Is there a way to implement some sort of basic multi-tenancy? for example, to have users with separate data.

Davide

**Comment by platipusica** [comment]
Hi Davide, 

this is the chicken and egg question for Python applications. If not mistaking, even Django can't do that.

But, the good news is the developers started working on Users separation, the example is here: https://github.com/platipusica/jampy-posfixaliases

The users for this App are NOT the framework users (except Admin), but the database table users, ie:
CREATE TABLE "ALS_USERS"
(
"ID" INTEGER PRIMARY KEY,
"DELETED" INTEGER,
"NAME" TEXT,
"LOGIN" TEXT,
"PASSWORD" TEXT,
.
.
HOpe this helps.

D.

**Comment by jam-py** [comment]
Hi, Davide
I do not understand what do you mean. Can you give an example?
Andrew

**Comment by ddavidebor** [comment]
@jam-py  for example: each row has a field owner_user_id. Each user is allowed only to see or edit only the rows owned by them.

This would be for example a basic requirement for building a SaaS app on top of Jampy, with separate data but a common database.

**Comment by jam-py** [comment]
It can be implemented. The app that Dean meationed does somthing like this.
If you create some app I can add the code that realises this functionality.

**Comment by ddavidebor** [comment]
@jam-py here it is
[dblibsviewer_1.0.0_5.4.16_2018-08-02_19-52-32.zip](https://github.com/jam-py/jam-py/files/2254965/dblibsviewer_1.0.0_5.4.16_2018-08-02_19-52-32.zip)

**Comment by jam-py** [comment]
I added user_id field to Components, an invisible user_id filter and this code to components.js:

function on_view_form_created(item) {
    if (task.user_info.user_id) {
        item.filters.user_id.value = task.user_info.user_id;
    }
}

function on_before_post(item) {
    item.user_id.value = task.user_info.user_id;
} 

Here is the app:
[dblibs.tar.gz](https://github.com/jam-py/jam-py/files/2256601/dblibs.tar.gz)

**Comment by ddavidebor** [comment]
But this way the filtering is triggered user-side and there is no security whatsoever

**Comment by jam-py** [comment]
To do this on the server remove the user_id filter, code from all_components.js ,
set the required attribute of user_id to false and add the following code to all_components.py:

def on_open(item, params):
    user_id = item.session['user_info']['user_id']
    if user_id:
        params['__filters'].append(['user_id', item.task.consts.FILTER_EQ, user_id])
    sql = item.get_select_statement(params)
    return item.task.execute_select(sql), ''

def on_apply(item, delta, params):
    user_id = item.session['user_info']['user_id']
    if user_id:
      for d in delta:
          d.edit()
          d.user_id.value = user_id
          d.post()

[dblibs.tar.gz](https://github.com/jam-py/jam-py/files/2259349/dblibs.tar.gz)

**Comment by ddavidebor** [comment]
Thanks this is extremely useful i'll work on that
The framework is really well structured! Pleasure to work on.

You should consider perhaps adding something like this directly at the framework level. To have a good framework for SaaS apps there is not much more to do than what jam.py already has, just good pluggable auth(allowing for OAuth2 or saml), data ownership, and perhaps some work on the roles to improve onto the data ownership.

**Comment by jam-py** [comment]
Thank you Davide.

I'll think about adding it at the framework level.
But first I'll create a this topic in faq.

2018-08-04 21:37 GMT+03:00 Davide Bortolami <notifications@github.com>:
