### ISSUE TITLE
Authentication integration

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#82]
Hi,

Considering JamPy is quite business oriented, has even an autentication integration be implemented? (AD, Kerberos, Oauth)

Regards,
Davide

**Comment by platipusica** [comment]
Hi there,

please use Trello: https://trello.com/b/CJ8y16Hx/jampy-in-general

AD is documented there.

Thanks

Dean

**Comment by jam-py** [comment]
There is a on_login event of the task on the server that you can use for it:
http://jam-py.com/docs/refs/server/task/on_login.html

**Comment by ddavidebor** [comment]
@platipusica it's set to private. Can you enable d@fermiumlabs.com?

**Comment by ddavidebor** [comment]
@jam-py that's a straightforward implementation! thanks

**Comment by matejak** [comment]
Hello, I have checked those docs, and it looks like that the solution @ddavidebor is happy about relies on modifying the code of the project before it is deployed.
Is my understanding correct, or is it possible to implement authentication support without modifications to the existing code?

**Comment by platipusica** [comment]
Hi Matej, 

welcome. No, no need for any changes and in fact LDAP example is here:

[LDAP_1.0.1_5.4.113_2021-08-25_03-13-56.zip](https://github.com/jam-py/jam-py/files/7042931/LDAP_1.0.1_5.4.113_2021-08-25_03-13-56.zip)

Import App, turn on Safe Mode and ldap will kick in.

You can read about this in here and even try it (msg from 09 August):
https://groups.google.com/g/jam-py/c/EYeotvabCWU

Cheers
