### ISSUE TITLE
Smart Urls

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#84]
It would be nice if it was possible to share links related to data in jam.py, for example if the url of the page instead of just being / would pinpoint to the right task and record.

This could be done in the following way:
- every time a record is opened, the url is updated trough a javascript function to the url domain.it/task/[task]/[record-key]/[detail]
- when the page is loaded, the app looks up the current url and tries to open the right task+record+detail

What do you think? this idea is 100% client side. The server just needs to tolerate the different urls

**Comment by jam-py** [comment]
I plan to to a "Open in new page" check box in View and Edit form dialogs.
If it is checked the client will send the server a url with get parameters
of the item ID and a record id for edit forms.
I'll do it in September.

2018-08-10 12:57 GMT+03:00 Davide Bortolami <notifications@github.com>:

**Comment by platipusica** [comment]
Hi guys

Davide, are you referring to something like SLUGs?

I would suggest to have it as an option, off by the default.

This is a candidate for further development as an extension, or a module.
Something to thing off, since not everyone needs it.

Regards

D.

**Comment by ddavidebor** [comment]
@platipusica well you need more of a structured path than a slug to reach a record that is inside a task.
