### ISSUE TITLE
Prebuilt "attachments" details

### ISSUE THREAD

**Issue by ddavidebor** [jam-py/jam-py#85]
I think building an "attachments" detail or a single "attachment" form field is a pretty common scenario, I'm finding myself doing it quite a lot. 

Maybe it makes sense to officially build a similar detail and field type, this way it can be improved in the future, especially UI-wise, without reinventing the wheel every time.

**Comment by jam-py** [comment]
I want to create an image and file field types, that save file name
information and upload
file to the static folder on the server. You can do it now, but it requires
some coding. With this addition
no coding will be needed.


2018-08-10 13:12 GMT+03:00 Davide Bortolami <notifications@github.com>:

**Comment by jam-py** [comment]
Thanks for the good ideas

2018-08-10 14:00 GMT+03:00 Andrew Yushev <yushevaa@gmail.com>:

**Comment by platipusica** [comment]
Guys

If I may (I’m bored on holidays), it depends of what is uploaded :)

If Jam will grow heaps, speed might be an issue. As Django moved away all
Python 2 code, I think the best for Jam might be to do the same. The speed
reports are quite positive atm for Django.

than, Andrew might suggest the way how to extend Jam.py without hurting the
Jam “core” much, so he can concentrate on the rest 99% of the code.

The extensions than can be built and approved by the code maintainer. They
can be even sold on the market as ie SLUGs, geo locating, captcha etc etc


Thoughts ?

**Comment by ddavidebor** [comment]
@jam-py Many JS libraries to have "pretty" uploads have already a good support for images (with preview, in a few cases also crop). For example i know of https://www.dropzonejs.com/ which has nice previews.

(BTW, for multiple upload, dropzone.js is quite neat!)

The difference between image and file could be client-only.

Also, I suggest moving from storing the files with the file name to a UUID. This way any possible bug due to file system naming compatibility becomes a non-issue and the storage could be easily moved to external systems such as Amazon S3.  You could store a serialized json object instead of the file name if more metadata is required. UUID never collide so you don't have to check if the file already exists.

**Comment by platipusica** [comment]
Yep,

All good thoughts. Someone got to do it though and Andrew can't do
everything by himself.

As discussed with him, the necessity for Jam are testing utilities and
running them before releasing anything new. If not tested it should not be
released. We are all professionals with a limited time and can't continue
to act as testers or even early adopters.

It is up to Andrew to decide about the priorities...

**Comment by jam-py** [comment]
Done
