### ISSUE TITLE
ctrl shortcut and mac os

### ISSUE THREAD

**Issue by marcjammet** [jam-py/jam-py#86]
Hello,
Thank you for this amazing framework.
My users are Mac users and all ctrl shortcuts does not work on chrome or safari.
Is there a way to map to another like cmd (former apple key)

**Comment by jam-py** [comment]
Hi, Marc

Please try to replace event.ctrlKey with event.metaKey in the client module
of the task.

function on_view_form_keyup(item, event) {
    if (event.keyCode === 45 && event.metaKey === true){
        if (item.master) {
            item.append_record();
        }
        else {
            item.insert_record();
        }
    }
    else if (event.keyCode === 46 && event.metaKey === true){
        item.delete_record();
    }
}

function on_edit_form_keyup(item, event) {
    if (event.keyCode === 13 && event.metaKey === true){
        item.edit_form.find("#ok-btn").focus();
        item.apply_record();
    }
}

I will change the code in the next version.

Regards,
Andrew Yushev





вс, 16 сент. 2018 г. в 19:21, Marc Jammet <notifications@github.com>:

**Comment by marcjammet** [comment]
Thank you for your quick reply.
I put your code in the client module but still ctrl acting on key.
Sorry about that but, I did not specified that I am concerned by clicking in table head to be able to search.
ctrl + key is ok
ctrl + click is not
and metaKey does not replace ctrl at least in the code you give me

**Comment by jam-py** [comment]
Marc, please try to update to latest version. there is no need to click on
table head to select the search field.
If you have any problem, send me a message

пн, 17 сент. 2018 г. в 11:59, Marc Jammet <notifications@github.com>:

**Comment by marcjammet** [comment]
Thank you it’s perfect now.

Cordialement
--
Marc Jammet
--
Mob : +33 6 85 96 15 16
eMail:  marc@cogito.tel
Tweet:  @CogitoDigital
Web :   http://cogito.digital                                                          
Le 17 septembre 2018 à 13:18:00, jam-py (notifications@github.com) a écrit:

Marc, please try to update to latest version. there is no need to click on
table head to select the search field.
If you have any problem, send me a message

пн, 17 сент. 2018 г. в 11:59, Marc Jammet <notifications@github.com>:
