### ISSUE TITLE
Hungarian lang file

### ISSUE THREAD

**Issue by Jmos** [jam-py/jam-py#9]
[lang.zip](https://github.com/jam-py/jam-py/files/277969/lang.zip)
the zip file contain modified langs.py file also

**Comment by jam-py** [comment]
Thanks, I will include it in the next release. Can I ask you to update it if I'll make some changes?

**Comment by Jmos** [comment]
Re: [jam-py/jam-py] Hungarian lang file (#9)


Hello jam-py,

Yes of corse 

Tuesday, May 24, 2016, 5:00:39 PM, you wrote:





Thanks, I will include it in the next release. Can I ask you to update it if I'll make some changes?
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub





-- 
Best regards,
Tel:  + 36 20 776 95 14
 Meggyeshazi                            mailto:janos.meggyeshazi@gmail.com
