### ISSUE TITLE
After create table from db manual, can't delete 

### ISSUE THREAD

**Issue by zenithbb** [jam-py/jam-py#90]
create a table by import the data from exist data table, the table can't be delete. the desire result should be : delete the table in jam, but keep the database table

**Comment by jam-py** [comment]
Please, set manual mode on and then delete table and turn off  manual mode
When manual mode is on, database doesn't change.
Regards,
Andrew Yushev

пн, 3 дек. 2018 г. в 17:52, zenithbb <notifications@github.com>:

**Comment by zenithbb** [comment]
Thank you, done!
