### ISSUE TITLE
Detail view from import data table 

### ISSUE THREAD

**Issue by zenithbb** [jam-py/jam-py#91]
I have self define the view, let me call it VIEW_A, one column "Location Number" import from existed database table, and then I have another table which include the detail of "Location Number", for each Location I have few rows, the detail table include the column "Site Number" which associated to "Location Number", How can I use this association to show the detail view in VIEW_A, for detail table, I am not allowed to change the database

**Comment by ljudva** [comment]
Hi,

It would be way easier to just create a new project with required tables, export and attach here. Than we can take a close look. 
B/c not really clear where the problem is.

Thx

**Comment by zenithbb** [comment]
My question is, how the journal group table items associated to detail table

**Comment by jam-py** [comment]
Hi,

You can import first table to journals or catalogs or any group of the item
type and the second table
to details or group of the detail type and add the second to the first as
shown in this video:
https://youtu.be/sbvxE-vEfsM

The other way is to do it programmatically, see the tracks client module in
the demo app

Regards,
Andrew Yushev

вт, 4 дек. 2018 г. в 19:36, zenithbb <notifications@github.com>:

**Comment by platipusica** [comment]
Automatically, if the details Table is placed under Journals. The
Details assoc. are:
"MASTER_ID" INTEGER,  <-- this is the Journals Table ID
"MASTER_REC_ID" INTEGER,  <--- this is Table record ID

As Andrey mentioned, this can be forced by the code, so no need to
place table there. But, you still need this fields, so if you can't
touch the database, magic won't happen...

Hope this helps.

**Comment by jam-py** [comment]
I am sorry, my previous answer was wrong.
I can not create this master-detail reliation with standard method.

You can do it the following way
I assume that we have 'view_a' item that has 'location_number' field
and 'view_b' item that has 'site_number' field.

Then in view_a client module add the following code:

`
function on_view_form_created(item) {
    if (!item.lookup_field) { 
        item.table_options.height -= 200;
        item.view_b = task.view_b.copy();
        item.view_b.paginate = false;
        item.view_b.create_table(item.view_form.find('.view-detail'), {height: 200});
    }
}

var scroll_timeout;

function on_after_scroll(item) {
    if (!item.lookup_field && item.view_form.length) {
        clearTimeout(scroll_timeout);
        scroll_timeout = setTimeout(
            function() {
                if (item.rec_count) {
                    item.view_b.set_where({site_number: item.location_number.value});
                    item.view_b.open(true);
                }
                else {
                    item.view_b.close();
                }
            },
            100
        );
    }
}

`
Please update you package to the latest version.

Regards,
Andrew Yushev

**Comment by jam-py** [comment]
I am sorry the code appears unformated.

**Comment by zenithbb** [comment]
> I am sorry the code appears unformated.

You are so kind
I will try and try to understand

**Comment by zenithbb** [comment]
Hello, Jam-py

I made more test in Postgres, can you check below is the problem?
if location_number and site_number are both text, then the SQL will be like ...... where "table"."site_number"=123456 instead of where "table"."site_number"='123456', the will cause fail:  ERROR:  operator does not exist: text = integer at character 9180, HINT:  No operator matches the given name and argument types. You might need to add explicit type casts
