### ISSUE TITLE
discussion  about if we can have more than one detail view 

### ISSUE THREAD

**Issue by zenithbb** [jam-py/jam-py#92]
I am wondering if we can have more than one detail view for one journal, maybe be organised in tab view

**Comment by jam-py** [comment]
Hello,

I can have more  than one detail now.
May be you need to upgrade the package.

Regards,
Andrew Yushev

пн, 10 дек. 2018 г. в 17:33, zenithbb <notifications@github.com>:

**Comment by platipusica** [comment]
Hi all,

I've posted the video about the Master-Details table on FaceBook group.

I forgotten to add on the Vid, it is possible to reorganise tabs ie
"Demo Table 2", than "InvoiceTable", than "Demo Table 1".

Thanks done on Journals/Details.

Enjoy.
