### ISSUE TITLE
Readonly does not work for image fields

### ISSUE THREAD

**Issue by bfranske** [jam-py/jam-py#93]
In Jam.py 5.4.37 when an image field is marked read-only you are still able to change the image by double clicking on it. Use case is that thumbnail images will be created and copied into the static directory and filenames stored into the database image field by an automatic batch processing program, the images should be viewable through jam.py but users should not be able to change them even if they have write permission to other fields.

**Comment by jam-py** [comment]
I corrected the code. If read_only is set for image fields, the double
click can not be used to change the image.
You can set the read_only to true and add the following code in the client
module:

function on_edit_form_created(item) {
    if (task.user_info.user_id === 1) {
        item.photo.read_only = false;
    }
}

so the users with user_id equal to 1 would be able to change the image.

ср, 6 февр. 2019 г. в 20:16, bfranske <notifications@github.com>:
