### ISSUE TITLE
Automatically scale images in view form

### ISSUE THREAD

**Issue by bfranske** [jam-py/jam-py#94]
When working with image fields in a database the current way things are is to just show a portion of the image on the view form. It would be much more useful to use an image library to automatically scale the images and create thumbnails so that a smaller sized version of the entire image can be seen.

**Comment by jam-py** [comment]
I will do this.
Now you can  pick row line attr value so the image fits the cell.

ср, 6 февр. 2019 г. в 20:28, bfranske <notifications@github.com>:
