### ISSUE TITLE
Support for textareas on edit forms

### ISSUE THREAD

**Issue by bfranske** [jam-py/jam-py#95]
I have some text fields in my database which contain a few hundred characters. I would like to have these display as textareas with heights and widths specified instead of as a regular text box which needs to be scrolled. Could a setting be added to the 'interface' screen for the field where it can be switched from a text box to a textarea and height/width can be specified?

**Comment by jam-py** [comment]
To display the text in textarea create a field with the type LONGTEXT.
I plan to add a possibility to set the height, the width is defined by
layout (the width of the form).
You can set the height of the textarea in the on_edit_form_shown event
handler in the item client module:
function on_edit_form_shown(item) {
    item.edit_form.find('textarea.info').height(400)
}
info here is the name of the field.



ср, 6 февр. 2019 г. в 20:33, bfranske <notifications@github.com>:
