### ISSUE TITLE
Extract models from an existing database

### ISSUE THREAD

**Issue by arisobel** [jam-py/jam-py#99]
Hi congrats for the great Framework.

At web2py we have such script
https://github.com/web2py/web2py/blob/master/scripts/extract_mssql_models.py

A way like this would allow to quickly bring a Legacy project to live in jam-py

Ari Sobel - Brazil

**Comment by jam-py** [comment]
Hi, Ari

Thank you for the idea!

Andrew Yushev

**Comment by MaxMorais** [comment]
@arisobel I believe jam-py already support that

http://jam-py.com/docs/admin/intergation_with_existing_database.html
